### ISSUE TITLE
watchPosition functions not implemented 

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/capacitor-background-geolocation#1]
I'm sure you are aware as the Capacitor version is WIP but thought I'd add a reminder as it was highlighted while migrating my cordova plugin codebase that used those functions.

**Comment by christocracy** [comment]
Yes, I'm aware that `watchPosition` is missing.  Why are you using `watchPosition`?  That function is generally not needed.

**Comment by alexcroox** [comment]
In my fleet tracking app I wanted to know immediately where the user was without waiting for the usual background geolocation onLocation to fire if the user hadn't moved the required amount yet to trigger it etc.

**Comment by christocracy** [comment]
You can use `getCurrentPosition` to get the current location.

**Comment by alexcroox** [comment]
Thanks, I was utilising the watchPosition interval to regularly poll while a certain screen was visible and active. I can switch to `getCurrentPosition` with my own setInterval for now thanks

**Comment by christocracy** [comment]
`watchPosition` implemented in latest release `0.0.12`.
