### ISSUE TITLE
Feature Request: adding checkPermissions to list of provided access functions

### ISSUE THREAD

**Issue by benkarbist** [transistorsoft/capacitor-background-geolocation#102]
## Your Environment
* Plugin version: 4.9.0
* Platform: iOS or Android
* Device OS version:
* Device manufacturer / model:
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Actual Behavior

I could not find a function that allow to check the permission status for this plugin. Currently I have to install the Geolocation plugin to access this functionality. It would be great if this function could be added.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs:
- onProviderChange
- getProviderState
- requestPermission

Calling .start() automatically requests permission.
