### ISSUE TITLE
When refreshing token, it takes refresh_expires_in as refresh_token

### ISSUE THREAD

**Issue by vquiles** [transistorsoft/capacitor-background-geolocation#103]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* Device OS version: Android 12
* Device manufacturer / model: Emulator
* Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/android: 3.8.0
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
      reset: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      useSignificantChangesOnly: true,
      disableElasticity: false,
      distanceFilter: 200,
      elasticityMultiplier: 3,
      motionTriggerDelay: 30000,
      maxDaysToPersist: 0,
      maxRecordsToPersist: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      preventSuspend: true,
      foregroundService: true,
      notification: {
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
        title: i18n.global.t("geolocation.notification.title"),
        text: i18n.global.t("geolocation.notification.text"),
      },
      url: `${process.env.API_URL}/${endpointsEnum.USER}/${endpointsEnum.POSITION}`,
      method: "PUT",
      httpRootProperty: ".",
      locationTemplate:
        '{"lat":<%= latitude %>,"lon":<%= longitude %>,"timestamp":"<%= timestamp %>"}',
      authorization: {
        strategy: "JWT",
        accessToken: userStore.accessToken,
        refreshToken: userStore.refreshToken,
        refreshUrl: `${process.env.KEYCLOAK_URL}realms/${process.env.KEYCLOAK_REALM}/protocol/openid-connect/token`,
        refreshPayload: {
          client_id: process.env.KEYCLOAK_CLIENT_ID,
          grant_type: "refresh_token",
          refresh_token: "{refreshToken}",
        },
      },
      locationAuthorizationRequest: "Always",
      backgroundPermissionRationale: {
        title: `${i18n.global.t(
          "geolocation.rationale.title1"
        )} {applicationName} ${i18n.global.t("geolocation.rationale.title2")}`,
        message: i18n.global.t("geolocation.rationale.message"),
        positiveAction: `${i18n.global.t(
          "geolocation.rationale.positiveAction"
        )} {backgroundPermissionOptionLabel}`,
        negativeAction: i18n.global.t("geolocation.rationale.negativeAction"),
      },
    }
```

## Expected Behavior
Every time a token is refreshed, {refreshToken} must be updated with the attribute "refresh_token" from the response.

## Actual Behavior
When refreshing a token, if the response has any other attribute started with "refresh" it gets the first one. In this case, it takes the "refresh_expires_in" attribute and uses it as the following refreshToken.

## Steps to Reproduce
1. Just wait until the token expires twice.

## Context
I'm using Keycloak as an authorization server. Keycloak returns the following info every time a refresh token is performed:
```
{
    "access_token": "XXXXXXXXXXXXXXXXXXXX",
    "expires_in": 60,
    "refresh_expires_in": 86391961,
    "refresh_token": "ZZZZZZZZZZZZZZZZZZZ",
    "token_type": "Bearer",
    "not-before-policy": 0,
    "session_state": "fbadd0b0-a3d6-44be-8cbe-51f697c7e3f6",
    "scope": "profile email"
}
```

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> RFC6749

This isn’t conforming to OAUTH. 

This is simply conforming to JWT.  OAUTH *uses* JWT.

**Comment by vquiles** [comment]
> 

> > RFC6749
> 
> This isn’t conforming to OAUTH.
> 
> This is simply conforming to JWT. OAUTH _uses_ JWT.

I think you are not right https://www.rfc-editor.org/rfc/rfc6749. But doesn't matter who's right, the behaviour of the plugin in this case is improvable as choosing "refresh_expires_in" over "refresh_token" isn't logical.

**Comment by christocracy** [comment]
You don’t understand.  This plugin is *not* doing Oath authorization.  There is no standard for the naming of params returned by an auth server so it uses regular expressions to “guess” the myriad number of different combinations server can provide.

This has performed well for over two years.

you are free to manage your own Authorization, using the onHttp event handler to detect status 401 as your cue to send an http request to your auth server to refresh your token.

in the meantime, I’ll see what I can do.

**Comment by christocracy** [comment]
Try installing from branch `authorization-refresh`.

- First clone and build the repo in a `/tmp` folder *outside* your app:
```
$ git clone https://github.com/transistorsoft/capacitor-background-geolocation.git
$ cd capacitor-background-geolocation
$ git checkout origin/authorization-refresh
$ npm run build
```

- Now `cd /path/to/your/app` and install the local clone:

```
$ npm install /path/to/capacitor-background-geolocation
```

**Comment by vquiles** [comment]
> Try installing from branch `authorization-refresh`.
> 
> * First clone and build the repo in a `/tmp` folder _outside_ your app:
> 
> ```
> $ git clone https://github.com/transistorsoft/capacitor-background-geolocation.git
> $ cd capacitor-background-geolocation
> $ git checkout origin/authorization-refresh
> $ npm run build
> ```
> 
> * Now `cd /path/to/your/app` and install the local clone:
> 
> ```
> $ npm install /path/to/capacitor-background-geolocation
> $ npx cap sync
> ```

Thank you very much, I really appreciate it. 

I'm out for the weekend but I'll try it as soon as possible.
