### ISSUE TITLE
Enhancement: Documentation Updates

### ISSUE THREAD

**Issue by brian-weasner** [transistorsoft/capacitor-background-geolocation#104]
## Your Environment
* Plugin version: `8.4.3`
* Platform: `iOS`

## Expected Behavior
Location Http Post Object should Mirror the Individual interfaces that make up the location object.

## Actual Behavior
- `location.activity` does not match `MotionActivityEvent` (for Post Schema or Location Interface)
    - [`MotionActivityEvent`](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/motionactivityevent.html) has property `activity` and `confidence`
    - Both [HTTP POST Schema](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/location.html#http-post-schema) and [Javascript Callback Schema (typescript location interface)](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/location.html#javascript-callback-schema) have the properties `type` and `confidence`

- `location.activity.type` can be the value of `'unknown'`
	- This is documented in [HTTP POST Schema](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/location.html#http-post-schema)
	- However it is not obvious that this can be the value of `'unknown'`, as [Motion Activity Object](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/motionactivityevent.html) only states that it can be `still, walking, on_foot, running, on_bicycle, in_vehicle`
	- This seems to only ever be `'unknown'` on iOS devices.

- `location.battery.level` can be the value of `-1`
	- This is documented in [HTTP POST Schema](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/location.html#http-post-schema) that the value is a double (which could mean "any" double value)
	- However it is not obvious that this can be a value of `-1` as [Battery Level](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/battery.html#level) only states that `0.0 = empty; 1.0 = full charge.`
	- This seems to only ever be `-1` on iOS devices.

## Steps to Reproduce
1. Setup an endpoint to receive the location http post object
2. Log some locations with different iOS devices
3. See that `location.activity` always has property of `type` instead of `activity` to denote the Activity Type
4. See that sometimes battery is `-1`
5. See that sometimes activity type is `'unknown'`

## Context
Reason I ask for updates to documentation here is that I have validation setup to make sure that the data that is being saved to our system matches the given interfaces the background geolocation plugin exposes.

## Debug logs
N/A

**Comment by brian-weasner** [comment]
Update: `location.battery.level` can be `-21474836` on an Android device, which seems to correlate with [`Integer.MIN_VALUE`](https://developer.android.com/reference/java/lang/Integer#MIN_VALUE) but truncated.

**Comment by tanuj-g** [comment]
@brian-weasner are you able to resolve this issue, I am continuously getting providerChange events from some specific samsung phones and the common pattern is those updates having the location.battery.level = -21474836
