### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by aotourdeveloper1** [transistorsoft/capacitor-background-geolocation#106]
*****************************************************************
FATAL EXCEPTION: main 
Process: com.aotour.driver, PID: 7856
android.app.RemoteServiceException: Bad notification for startForeground
*****************************************************************

Error in Android Studio console

## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* Device OS version: 12
* Capacitor info: 
  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.4.1

## Expected Behavior
The expected process is that at the time of starting the geolocation the app does not stop and continues in the view with the map

## Actual Behavior
The app starts the geolocation, asks for the authorization for the location in the second in the configuration, but when authorizing, the app exits and the android studio console throws the error.

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am trying to integrate the plugin with my app to record all the locations

## Debug logs

<details>
	<summary>Logs</summary>
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aotour.driver, PID: 7856
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

![image](https://user-images.githubusercontent.com/115663529/195439789-39a7331d-de2f-4453-87bf-2e70af06a3ba.png)
![Captura de pantalla 2022-10-12 151918](https://user-images.githubusercontent.com/115663529/195439872-55285937-bd8f-4d7a-bb14-d9c9d1310826.png)

</details>

**Comment by christocracy** [comment]
**YOU CAN EDIT an issue.  You don't need to create a new one.**.

Also, you **didn't post the config** you're providing to `BackgroundGeolocation.ready`!

<img width="920" alt="Screen Shot 2022-10-12 at 4 23 10 PM" src="https://user-images.githubusercontent.com/14999/195440598-055a2860-15d6-4e77-b3d0-71b6f8a83ad7.png">

**Comment by aotourdeveloper1** [comment]
Here my BackgroundGeolocation.ready

![image](https://user-images.githubusercontent.com/115663529/195441958-5b15cef6-c870-4d53-b27f-ba22691f475c.png)

**Comment by christocracy** [comment]
Please stop with the screenshots.  Code **is text**.  Post text and learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by aotourdeveloper1** [comment]
BackgroundGeolocation.ready({
      transistorAuthorizationToken: token,
      reset: false,
      debug: true,
      locationAuthorizationRequest: 'Always',
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      distanceFilter: 10,
      stopTimeout: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      autoSync: true,
      maxDaysToPersist: 14,
    }).then(async (state) => {
      // Store the plugin state onto ourself for convenience.
      console.log('- BackgroundGeolocation is ready: ', state);
      this.zone.run(() => {
        this.state.enabled = state.enabled;
        this.state.isMoving = state.isMoving;
        this.state.geofenceProximityRadius = state.geofenceProximityRadius;
        this.state.trackingMode = state.trackingMode;

        if ((state.schedule.length > 0)) {
          BackgroundGeolocation.startSchedule();
        }
      });
    }).catch((error) => {
      console.warn('- BackgroundGeolocation configuration error: ', error);
    });

**Comment by christocracy** [comment]
- Do you know what `reset: false` does?  99% of use-cases do not require that.
- `notificationTitle` and `notificationText` are deprecated.  See API docs `Config.notification`.

I suspect you are blindly copy/pasting code from the /example (a *very* bad idea) without understanding exactly what it is you're doing.

I suggest you stop what you're doing and create yourself a simple *Hello World* app to experiment with the code in isolation of your app until you learn how to use this plugin.  Use the [simple example in the README](https://github.com/transistorsoft/capacitor-background-geolocation#example-2--angular) as a guide.  **NOT** the /example app.

**Comment by christocracy** [comment]
Learn to [syntax highlight code-blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)

**Comment by aotourdeveloper1** [comment]
I was able to compile the app.
The problem it presented was because it did not have the app icon, that is, it had been deleted and the green android icon appeared.
i removed the android platform from the project and generated it again so that the icons and such would be generated.

Icon:
![WhatsApp Image 2022-10-13 at 9 17 10 AM](https://user-images.githubusercontent.com/115663529/195622187-89cf27a0-8abc-4fcf-ad38-8ccdb9c53ef8.jpeg)

**Comment by aotourdeveloper1** [comment]
Good day.

One question, how is the payment system with your platform?

Is it an annual subscription, monthly or one-time payment for the key?

I remain pending.



Cordialmente,

SAMUEL D. GONZÁLEZ MENDOZA
Jefe de Sistemas

***@***.***


www.aotour.com.co<http://www.aotour.com.co/>

***@***.***

Oficina Barranquilla: Carrera 53 # 68b -87 C.C. Gran Centro Oficina 1-138 Oficina Bogotá: Carrera 20 N° 37 - 67.
[image003]

De: Chris Scott ***@***.***>
Enviado el: miércoles, 12 de octubre de 2022 4:05 p. m.
Para: transistorsoft/capacitor-background-geolocation ***@***.***>
CC: SISTEMAS - AOTOUR ***@***.***>; Author ***@***.***>
Asunto: Re: [transistorsoft/capacitor-background-geolocation] Bad notification for startForeground (Issue #106)


Learn to syntax highlight code-blocks<https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting>
