### ISSUE TITLE
stopSchedule function not implemented

### ISSUE THREAD

**Issue by ThisIsTheRepoYouAreLookingFor** [transistorsoft/capacitor-background-geolocation#11]
TypeError: _transistorsoft_capacitor_background_geolocation__WEBPACK_IMPORTED_MODULE_2__.default.stopSchedule is not a function

**Comment by christocracy** [comment]
Oops, did I forget to implement a method.  Will take about 5 min once I return from vacation.

**Comment by christocracy** [comment]
`stopSchedule` is now implemented in master.  Please try installing the plugin from master and I'll push a new release.

**Comment by JohnyBoy1234** [comment]
I think your fix is correct. 
I was not able to npm install the plugin directly from GitHub though but that's a separate issue (build failed).

**Comment by brian-weasner** [comment]
Hello @christocracy 
StopSchedule is implemented however I believe it is incorrectly implemented, as it requires a return value of the current state, which is not currently being returned. Looking at the code it looks like it just needs 
```java
           TSConfig config = TSConfig.getInstance(getContext());
            try {
                call.resolve(JSObject.fromJSONObject(config.toJson()));
            } catch (JSONException e) {
                call.reject(e.getMessage());
            }
```
added to: https://github.com/transistorsoft/capacitor-background-geolocation/blob/f83aa878701aa8f5ab766c50211027cedb42054b/android/src/main/java/com/transistorsoft/bggeo/capacitor/BackgroundGeolocationPlugin.java#L227

Let me know if you want a separate issue for this and/or a Pull Request with those changes added.

Thanks,
- Brian

**Comment by brian-weasner** [comment]
In the meantime, I am just gonna make a call to getState after the call to stopSchedule resolves.

**Comment by christocracy** [comment]
You are correct.  I'll push `4.4.3` today.

**Comment by christocracy** [comment]
Probably Monday, latest.

**Comment by christocracy** [comment]
`4.4.3` is published.

**Comment by brian-weasner** [comment]
Confirmed, it works. Thank you for your quick resolution with this!
