### ISSUE TITLE
startForegroundService() not allowed due to mAllowStartForeground false

### ISSUE THREAD

**Issue by paullex** [transistorsoft/capacitor-background-geolocation#115]
## Your Environment
* Plugin version: 4.9.1
* Platform: Android
* Device OS version: Android 12
* Device manufacturer / model: SM-G991U
* Capacitor info (`npx cap doctor`):
* 💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
let config: Config = { 
  
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
          distanceFilter: 100,
          stationaryRadius: 0,
          maxRecordsToPersist: 3,
          debug: false,
          autoSync: true,
          autoSyncThreshold: 13,
          batchSync: true,
          stopDetectionDelay: 1,
          stopTimeout: 5,
          disableElasticity: false,
          isMoving:true,
      
          stopOnTerminate: false,
          stopOnStationary: false,
          startOnBoot: true,
      
          url: `${this._providerService.getGpsHost()}/gps`,
          headers: {
            'Authorization': `Bearer ${this._providerService.getApiToken('GPS_API_TOKEN')}`,
            'Content-Type': 'application/json'
          },
          extras: {
            "userId": this.userId,
            "driverName": this.driverName,
            "companyId": this.companyId,
            "companyName": this.companyName
          },
          locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>, "timestamp": "<%= timestamp %>", "speed": <%= speed %>, "is_moving": <%= is_moving %>}',
          locationAuthorizationRequest: 'Always',
          disableLocationAuthorizationAlert: this.platform.is('ios') ? true : false,
          locationAuthorizationAlert: {
            titleWhenNotEnabled: "Location-services is not enabled",
            titleWhenOff: "Location-services is OFF",
            instructions: "You must enable 'Always'",
            cancelButton: "Cancel",
            settingsButton: "Settings"
          },
          backgroundPermissionRationale: {
            title: "Allow HaulEx to access to this device's location in the background?",
            message: "To make sure the app works correctly on trip section, please enable 'Always' location permission",
            positiveAction: "Change to 'Always'",
            negativeAction: "Cancel"
          }    
        
```

## Expected Behavior
Gps plugin starts to work in background when app is hidden(not terminated) on Android OS.

## Actual Behavior
Error is thrown when app starts to utilise the plugin in the background and no gps coordinates are collected. 

## Steps to Reproduce

1. User opens the app with all permissions allowed previously
2. switches to other windows leaving app in the background
3. Error occurs when user leaves the geofence

## Context

Make sure the plugin works in the background

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service app.dieseldispatch.DieselDispatch/com.transistorsoft.locationmanager.service.BackgroundTaskService
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    at android.os.Parcel.readParcelable(Parcel.java:3346)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
    at android.os.Parcel.createException(Parcel.java:2422)
    at android.os.Parcel.readException(Parcel.java:2405)
    at android.os.Parcel.readException(Parcel.java:2347)
    at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6969)
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1927)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1893)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:798)
    at com.transistorsoft.locationmanager.service.AbstractService$a.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8751)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

</details>

**Comment by christocracy** [comment]
Are you sure that error came from `v4.9.1`?

**Comment by paullex** [comment]
Yes, it is a current version of the plugin we are using in production app

**Comment by paullex** [comment]
1. User launches the app
2. If he is logged in, he is brought to the home page, if not - at login page.
3. Once the authorisation is completed, he is asked to give location permissions and sets them to 'Always'. The gps plugin ready method is called with the configuration stated above.(Ready is called only once - when logging in, it is not called on every restart of the app)
4. User has finished using the app and leaves the app.
5. User moves out the geofence and the tracking is suppose to start, but instead the error above is thrown and gps plugin does not collect coordinates in the background.

**Comment by christocracy** [comment]
Are *you* reproducing *yourself*?

**Comment by JackMcKew** [comment]
Writing here to say I resolved this error by editing the `AndroidManifest.xml` to add the record:

`android:foregroundServiceType="location"`

Specifically to the `activity` with the tag `android:name="com.example.app.MainActivity"`

Other service types listed: https://developer.android.com/about/versions/10/features#fg-service-types

**Comment by christocracy** [comment]
`android:foregroundServiceType` is an attribute of [`<service>`](https://developer.android.com/guide/topics/manifest/service-element), not [`<activity>`](https://developer.android.com/guide/topics/manifest/activity-element).

The plugin already adds `android:foregroundServiceType="location"` to its required services (unless you're using an older version of the plugin (you didn't specify which version you're using).

**Comment by JackMcKew** [comment]
Currently using version `4.9.5`.

Interesting that you mention a `<service>` tag as I do not have one in my `AndroidManifest.xml` whatsoever. Referencing the [Changelog](https://github.com/transistorsoft/capacitor-background-geolocation/blob/HEAD/CHANGELOG.md#460--2022-04-29) is leading me to believe that I should have 2 `<service>` tags.

**Comment by christocracy** [comment]
The Android Setup docs are correct: they **do not** direct you to add `<service>` elements to your manifest.

**Comment by JackMcKew** [comment]
Should I expect to find `android:foregroundServiceType="location"` somewhere within the generated app then?

**Comment by christocracy** [comment]
The plug-in has its own AndroidManifest with all its required elements defined.
