### ISSUE TITLE
Android permissions popup displays before permission rationale popup

### ISSUE THREAD

**Issue by kinggolf** [transistorsoft/capacitor-background-geolocation#116]
## Your Environment
* Plugin version: 4.9.2
* Platform: Android 
* Device OS version: running on Android Studio emulator Pixel 4 API 30
* Device manufacturer / model:
* XCode version: N/A
* Capacitor info (`npx cap doctor`)
```
Installed Dependencies:

  @capacitor/cli: 3.8.0
  @capacitor/core: 3.8.0
  @capacitor/android: 3.8.0
  @capacitor/ios: 3.8.0
```
* Plugin config provided to `#ready`:
```
  private trackingConfig: Config = {
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    notification: {
      title: 'Move Details',
      text: 'Do the Unexpected',
    },
    stopOnTerminate: false,
    startOnBoot: true,
    backgroundPermissionRationale: {
      title:
        "Allow {applicationName} to access this device's location even when closed or not in use.",
      message:
        'This app collects location data to enable recording your trips from dispatches to job sites and back.',
      positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
      negativeAction: 'Cancel',
    },

    let state: State;
    state = await BackgroundGeolocation.ready(this.trackingConfig);
    if (state.enabled) {
      console.warn('BACKGROUND GEOLOCATION ALREADY ACTIVE');
    }
    if (!state.enabled) {
      console.warn('STARTING BACKGROUND GEOLOCATION');
      state = await BackgroundGeolocation.startGeofences();
      BackgroundGeolocation.onProviderChange((event) => {
        this._authorizationStatus.next(
          event.status === BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS
        );
      });
    }
```

## Expected Behavior
permission rationale popup should present first - otherwise app is rejected by PlayStore

## Actual Behavior
This is the order of popups on initial install & start up of app.
1st
<img width="355" alt="Screenshot 2022-11-02 at 8 28 44 PM" src="https://user-images.githubusercontent.com/9776423/199646860-82ecde10-1450-49c1-ab6e-aee26c86e211.png">
2nd
<img width="355" alt="Screenshot 2022-11-02 at 8 28 54 PM" src="https://user-images.githubusercontent.com/9776423/199646876-967b5ceb-469b-4266-9359-fa33bf975daf.png">
3rd
<img width="413" alt="Screenshot 2022-11-02 at 8 29 09 PM" src="https://user-images.githubusercontent.com/9776423/199646886-c9bddfa3-2b74-4a30-8040-c37ebdc2f740.png">
4th
<img width="360" alt="Screenshot 2022-11-02 at 8 29 25 PM" src="https://user-images.githubusercontent.com/9776423/199646899-25e7f2dc-0cd4-4071-b098-080db604f622.png">

## Steps to Reproduce
android/variables.gradle
```
ext {
    minSdkVersion = 21
    compileSdkVersion = 31
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion =  '7.0.0'
    // capacitor-background-geolocation variables
    googlePlayServicesLocationVersion = '20.0.0'
}
```

## Context
Initiate bg geolocation calling ```BackgroundGeolocation.startGeofences()```

## Debug logs
I am not getting errors.

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```diff
+  targetSdkVersion = 31
```

**Comment by christocracy** [comment]
What are you expecting?  You know that Android has made location permissions far more restrictive lately, right?  They’ve basically followed the same pattern of iOS now.

**Comment by kinggolf** [comment]
I was expecting the `backgroundPermissionRationale` to present first. This one:
<img width="361" alt="Screenshot 2022-11-03 at 8 28 33 AM" src="https://user-images.githubusercontent.com/9776423/199776762-bd0f409a-a197-455f-a499-9e2a020efc3c.png">

Do I need to build my own popover to explain this up front to the user similar to your sample app:
![Screenshot_20221103-091342](https://user-images.githubusercontent.com/9776423/199777040-fdd7dbe0-e4ef-4a1a-9ce3-1627a7e4cefa.jpg)
And use `BackgroundGeolocation.getProviderState()` on app start to detect whether or not I need to display my custom popover?

**Comment by christocracy** [comment]
> I was expecting the backgroundPermissionRationale to present first. This one:

Your expectations are incorrect.  What you see happening is exactly what’s supposed to happen.

> Do I need to build my own popover to explain this up front to the user similar to your sample app:

Yes.  Before your app requests any location permission, you must show your own dialog explaining exactly why you need the permissions you’re about to request.  If you don’t, Google Play will reject your app.

**Comment by kinggolf** [comment]
Got it, thanks!
Yep, we learned this the hard way, our app was rejected by PlayStore.
Thanks again.

**Comment by christocracy** [comment]
Did you see [my blog](https://link.medium.com/3x9sanwWEub)

> targetSdkVersion = 31

Do you know that this [now the Play Store minimum](https://developer.android.com/google/play/requirements/target-sdk)?

personally, I develop and test with `33` (including `compileSdkVersion 33`).  You should too.
