### ISSUE TITLE
Privacy Policy link in README.md 404s

### ISSUE THREAD

**Issue by thebalaa** [transistorsoft/capacitor-background-geolocation#117]
## Your Environment
* Plugin version: All
* Platform: Both
* Device OS version: Any
* Device manufacturer / model: All
* XCode version: Any
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```bash <!-- syntax-highlighting:  paste your code below -->
curl -I https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/PRIVACY_POLICY.md
```

## Expected Behavior
Privacy policy link in README.MD references an up to date privacy policy.

## Actual Behavior
Privacy policy link in README.md is broken.

## Steps to Reproduce

1. Click Privacy Policy link in this repo's README.md

## Context
I would like to gain awareness of this plugin's privacy policy.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
HTTP/2 404
server: GitHub.com
date: Sat, 05 Nov 2022 14:01:10 GMT
content-type: text/html; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
...
```

</details>

**Comment by christocracy** [comment]
This plugin does not capture or upload *any* data to transistorsoft.com or any other 3rd party.
