### ISSUE TITLE
BackgroundGeolocation.onProviderChange() not triggered on Android after increasing permission level

### ISSUE THREAD

**Issue by xyboox** [transistorsoft/capacitor-background-geolocation#124]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android
* Device OS version: Android 13
* Device manufacturer / model: Google Pixel 4a
* XCode version: Version 14.1 (14B47b)
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/core: 4.5.0
  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
stopTimeout: 5,
debug: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
stopOnTerminate: false,
startOnBoot: true,
url: environment.locationEndpoint,
locationAuthorizationAlert: {
	titleWhenNotEnabled: text1,
	titleWhenOff: text2,
	instructions: text3,
	cancelButton: 'no',
	settingsButton: 'yes'
},
locationAuthorizationRequest:'always',
backgroundPermissionRationale: {
	title: text4,
	message: text5,
	positiveAction: text6,
	negativeAction:text7,
},
extras: {
	...
},
schedule: this.schedule,
scheduleUseAlarmManager: true,
```

## Expected Behavior
BackgroundGeolocation.onProviderChange() should trigger, with a status = 3 ( as in iOS is happening )

## Actual Behavior
BackgroundGeolocation.onProviderChange() is NOT triggered at all.

## Steps to Reproduce

1: On first use, user ( having location services ON ) chooses to NOT grant any kind of permission for location or physical activity.
2: Later on, they go to Android settings -> Apps -> My app -> permissions -> location and select "Allow all the time".

## Context

To act upon permission level increasing.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
no errors, no logs as the method is not triggered.
```

</details>

**Comment by christocracy** [comment]
Unfortunately, Android does not trigger an event when user modified permissions in Settings.

**Comment by xyboox** [comment]
@christocracy it does though when using the "backgroundPermissionRationale" flow. Couldn't the same apply to the other scenarios ( like from "Don't allow" or "Allow only while using the app" to "Allow all the time" )?

**Comment by christocracy** [comment]
People have asked this question *dozens* of times in the past.

No, Android does not fire events when user changes permission level in Settings.

**Comment by xyboox** [comment]
Thanks!

**Comment by christocracy** [comment]
You are free to call `getProviderState()` as desired, to query the current permission state.
