### ISSUE TITLE
Plugin works even on background, but it dont execute my code when in background on Android

### ISSUE THREAD

**Issue by barart** [transistorsoft/capacitor-background-geolocation#13]
## Your Environment
* Plugin version: 
capacitor-background-fetch: 0.0.6
capacitor-background-gelocation: 4.2.1
* Platform: Android
* Device OS version: 11
* Device manufacturer / model: SM-A725M
* XCode version: N/A
* Capacitor info (`npx cap doctor`)
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      reset: true,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      locationAuthorizationRequest: 'Always',
      distanceFilter: 10,
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
      
    }).then((state) => {
      console.log("BackgroundGeolocation is configured and ready to use ", state.enabled);
```
My onLocation and onMotionChange code:
```
 // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation((location) => {
      console.log('[onLocation]', location);
      
         console.log('Update Coords');
        const param = {
          lat: location.coords.latitude,
          lng: location.coords.longitude,
        }
        this.api.updateCoords(param).then((data) => {
           console.log(data);
        }).catch(error => {
          console.log(error);
        });
      
    }, ((error) => {  // <-- Location errors
      console.log('[onLocation] ERROR:', error);
    }));

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange((location) => {
      console.log('[onMotionChange]', location);
     
         console.log('Update Coords');
        const param = {
          lat: location.location.coords.latitude,
          lng: location.location.coords.longitude,
       }
        this.api.updateCoords(lparam).then((data) => {
           console.log(data);
        }).catch(error => {
          console.log(error);
        });
      
    });
```
## Expected Behavior

When app is in background  (closed/killed), plugin should be able to execute my code when onMotionChange and onLocation events; as i have debug mode enabled, i can hear when the plugin is registering movements, changes and locations, however my code is never executed, but if i have the app in foreground the plugin execute my code successfully on MotionChange and onLocation events, this only occurs on Android, on iOS works as expected.
## Actual Behavior

When app is in background (closed/killed) plugin works as i can hear the debug sounds, but it never execute my code onMotionChange and onLocation events.
## Steps to Reproduce

1. Install the app
2. Enable always and motion permissions 
3. Open the app and plugin works as expected
4. Kill the app
5. Plugin comes alive but it never execute my code on mentioned events

## Context

Im trying to execute a code when onMotionChange and onLocationChange
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
I dont think logs are relevant in this case as the plugin works but it dont execute my code on background, there is no different on foreground and background logs. I could not find [onLocation] or [onMotionChange] strings on logs (foreground or background)
```

</details>

**Comment by christocracy** [comment]
If you're trying to do an http request in the plugin's event-handlers, you're likely experiencing the Capacitor webview failing to execute code in the background.

I suggest you take advantage of the plugin's built-in native HTTP service.  See the API docs *HTTP Guide* for more information.

**Comment by barart** [comment]
Hello Chris... im not trying to make a http request, im trying to call an api as you can se on my code:

`BackgroundGeolocation.onMotionChange((location) => {
      console.log('[onMotionChange]', location);
     
         console.log('Update Coords');
        const param = {
          lat: location.location.coords.latitude,
          lng: location.location.coords.longitude,
       }
        this.api.updateCoords(param).then((data) => {
           console.log(data);
        }).catch(error => {
          console.log(error);
        });
      
    });`

as i wrote above, this works on ios but not on android

**Comment by christocracy** [comment]
>im not trying to make a http request, im trying to call an api as you can se on my code:

Yes, it looks like you're trying to manage sending location data to your API, likely via HTTP request, via Javascript code.

Are you observing the plugin logs?  See Wiki *Debugging*.

**Comment by barart** [comment]
Yes, as i mentioned when opening the thread, i already observed the plugin logs, there is nothing relevant or errors compared to the log with the app in foreground and the log in background, seems very similar both of them

**Comment by christocracy** [comment]
I suggest you print log messages in your event callbacks using `BackgroundGeolocation.logger`.  Those will print messages to the plugin's logs, which can be captured with `getLog` / `emailLog`.  That will tell you if the event-handlers are actually running.

**Comment by barart** [comment]
Im still debugging this, the `BackgroundGeolocation.logger` has been helpful, however, everything seems to work (without any code changes) as same and logger show that it "execute" my code (but it doesn't do what it should); what is strange for me, is that my code seems to start working completely when i added the `BackgroundGeolocation.logger` into it :/

Im still investiganting...

iOS works exactly as expected, pure beauty

**Comment by mitar096** [comment]
Hello,

I have the exact same problem. @barart  did you find a solution for this?

Thank you in advance

**Comment by ramandeepR** [comment]
Hello,

I have the exact same problem. @barart did you find a solution for this? @christocracy 

Thank you in advance

**Comment by mitar096** [comment]
Hello @ramandeepR,

I found a solution for this problem. Android will run the code only if it was written in Java. You must write this code in Java if you wont to do something in background. More about this you can find here: https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode#step-2a--plugin-version-2132

Best regards,
Mitar

**Comment by ramandeepR** [comment]
Hello @mitar096 

Thank you for reply. Can you help me with this integration? I am stuck on this issue now. May be I need to stop this only due to background location not working accurately.

Best Ragards,
Ramandeep

**Comment by tanuj-g** [comment]
Hello @christocracy 
I am encountering a similar problem where I need to transmit certain events (onMotionChange, onProviderChange) to my backend server. While the app is active in the background or foreground, the listeners successfully send these events. However, when the app is forcibly closed, I require immediate reception of these events on my server.

I am using plugin inbuild HTTP service to send the locations in the background and killed state. But that service only sends locations events for the IOS. they are not sending providerChange event in the background for ios

**Comment by christocracy** [comment]
> Platform: Android

>“they are not sending providerChange event in the background for ios”

This issue thread was posted related to Android.

**Comment by tanuj-g** [comment]
> 

@christocracy 
Is it necessary to handle the events in the killed state by writing native code for both Android and iOS platforms by myself?

Is there any potential for the plugin to send all providerChange events to my specified config URL via HTTP, similar to how it sends location updates when the app is in a killed state?

Could you please incorporate this configuration into the plugin so that it can send the events using a single config? Since the native code is already implemented in the plugin, this addition would be beneficial.

**Comment by christocracy** [comment]
> Is it necessary to handle the events in the killed state by writing native code for both Android and iOS platforms by myself?

Only Android.  iOS has no concept of “headless”.

> Is there any potential for the plugin to send all providerChange events to my specified config URL via HTTP

Android already does.  For iOS, you must do so manually.  iOS won’t fire the onProviderChange event if your app is **terminated**.

**Comment by tanuj-g** [comment]
@christocracy 
Could you please provide further clarification on what you mean by "manually handling the event" in the context of iOS?

My objective is to ensure that every onProviderChange event from the iOS app is sent to my server, regardless of the app's status (foreground, background, or killed state). This way, I can keep track of whether the user has granted or revoked location permissions.

For instance, if the user initially grants permission and tracking begins, but later manually revokes the location permission from the app through device settings, I would like to update my server accordingly to indicate that the user has selected incorrect permissions.

**Comment by christocracy** [comment]
> My objective is to ensure that every onProviderChange event from the iOS app is sent to my server, regardless of the app's status (foreground, background, or killed state)

On iOS, you can’t.
