### ISSUE TITLE
Location tracking stopped after some time(10-15 mins) in android

### ISSUE THREAD

**Issue by mohit-11-dev** [transistorsoft/capacitor-background-geolocation#135]
## Environment
* Plugin version:  "@transistorsoft/capacitor-background-fetch": "^1.0.2",
                              "@transistorsoft/capacitor-background-geolocation": "^4.9.4",
* Platform:  Android
* Device OS version: 11
* Device manufacturer / model: Vivo
* XCode version: N/A
* Capacitor info (`npx cap doctor`):  
 @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
* Plugin config provided to `#ready`:
```
        {
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 1,
              url:`${webAdmin.apiAdminUrl}firebase_api/location.php`,
              extras:{email: userId, uid:uid, token: token},
              debug: true,
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,  
              startOnBoot: true
        }
```

## Expected Behavior
It should be able to track locations all the time if gps and internet is on 

## Actual Behavior
It is not tracking after few minutes of idle time. I moved after few minutes and walk for around 500 meters but it didn't track and notification for tracking also didn't show up
## Steps to Reproduce
1. Install app 
2. Grant permission to allow all the time
3. Turn on gps 
4. make mobile idle for some time and then start walking, it doesn't track new location and notification for tracking also won't show 

## Context
 Trying to track location and user activity like walking running, cycling, vehicle etc
## Debug logs
<details>
	<summary>Logs</summary>

```01-10 19:17:28.941 19992  7106 I GCoreUlr: GMS FLP location updates requested: # czjk@c9614504
01-10 19:17:28.943 19992  7106 I GCoreUlr: GMS AR updates requested: UlrSampleSpec{mSamplePeriodMs=120000, mSampleMinMillis=15000, mActivitySampleMillis=240000, mMaxWaitTimeMillis=600000, mSourcePackage=10161:com.google.android.gms}
01-10 19:17:28.957 19992 11903 E GoogleLocationManager: 10161/com.google.android.gms[current_semantic_location]/6b9a91e4 -> Request[@2m/10m BALANCED_POWER_ACCURACY, minUpdateInterval=15s, THROTTLE_NEVER, waitForAccurateLocation] is not allowlisted to use THROTTLE_NEVER [CONTEXT service_id=6 ]
01-10 19:17:28.994 19992  7106 I GCoreUlr: WorldUpdater received intent Intent { act=com.google.android.location.reporting.ACTION_UPDATE_WORLD cmp=com.google.android.gms/com.google.android.location.reporting.service.DispatchingService (has extras) } with receiverAction android.location.PROVIDERS_CHANGED
01-10 19:17:29.181 19992  7237 E GoogleLocationManager: 10161/com.google.android.gms[current_semantic_location]/6b9a91e4 -> Request[@2m/10m BALANCED_POWER_ACCURACY, minUpdateInterval=15s, THROTTLE_NEVER, waitForAccurateLocation, WorkSource{10161 com.google.android.gms}] is not allowlisted to use THROTTLE_NEVER [CONTEXT service_id=6 ]
01-10 19:17:29.246 19992  7106 I GCoreUlr: WorldUpdater:android.location.PROVIDERS_CHANGED: Ensuring that reporting is active for [account#9#]
01-10 19:17:29.265 19992  7106 I GCoreUlr: WorldUpdater received intent Intent { act=com.google.android.location.reporting.ACTION_UPDATE_WORLD cmp=com.google.android.gms/com.google.android.location.reporting.service.DispatchingService (has extras) } with receiverAction com.google.android.location.internal.server.ACTION_RESTARTED

```

</details>

**Comment by christocracy** [comment]
- Have you read the wiki *Philosophy of Operation*?
- See wiki *Debugging* and learn how to retrieve plugin logs with .emailLog method.
- Are you aware of Config.stopTimeout?
