### ISSUE TITLE
Process ended when change system location permission

### ISSUE THREAD

**Issue by thoarca** [transistorsoft/capacitor-background-geolocation#137]
## Your Environment
* Plugin version: ^4.7.1
* Platform: Android
* Device OS version: 11
* Device manufacturer / model: Honor
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  onProviderChange(provider: ProviderChangeEvent) {
    console.log('[event] providerchange', provider);
    if (provider.enabled === true) {
      Storage.set({
        key: 'hasDisclosedBackgroundPermission',
        value: "true",
      });
    } else {
      Storage.set({
        key: 'hasDisclosedBackgroundPermission',
        value: "false",
      });
ì    }        
    this.addEvent('onProviderChange', new Date(), provider);
  }
```

## Expected Behavior
Disabling the permissions from the OS, the "hasDisclosedBackgroundPermission" variable should become false in the storage

## Actual Behavior
Disabling the permissions from the OS (with app opened in background), when re-open app from task manager, the app is killed
with this message "permission revoked".  Why is the app killed?
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Yes, that’s exactly right.  That’s the nature of the Android OS when you change permissions.

read [this](https://stackoverflow.com/questions/40240665/how-to-prevent-re-creating-an-activity-while-changing-the-permissions-at-runtime)
