### ISSUE TITLE
iOS not providing correct activity type in background, sending type as unknown even after granting the permission

### ISSUE THREAD

**Issue by mohit-11-dev** [transistorsoft/capacitor-background-geolocation#139]
## Environment
* Plugin version:  "@transistorsoft/capacitor-background-fetch": "^1.0.2",
                              "@transistorsoft/capacitor-background-geolocation": "^4.9.4",
* Platform:  iOS
* Device OS version: All
* Device manufacturer / model: Apple
* XCode version: All
* Capacitor info (`npx cap doctor`):  
 @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
* Plugin config provided to `#ready`:
```
        {
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 1,
              url:`${webAdmin.apiAdminUrl}firebase_api/location.php`,
              extras:{email: userId, uid:uid, token: token},
              debug: true,
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,  
              startOnBoot: true
        }
```

## Expected Behavior
It should be able to send correct activity type in iOS

## Actual Behavior
It is sending activity type as unknown while in background after app kill

## Steps to Reproduce
1. Install app 
2. Grant permission to allow all the time and allow track activity permission
3  kill the app

## Context
 Trying to track location and user activity like walking running, cycling, vehicle etc 
## Debug logs
<details>
	<summary>Logs</summary>
 NA
```
</details>

**Comment by christocracy** [comment]
The native motion api is a "black box" with an ON/OFF switch.  The plugin has not control over the quality of the data that comes out of it.

Note:  The motion API does not work in iOS Simulator; only *real* devices.
