### ISSUE TITLE
I keep getting the warning "Background Location is not enabled", even though I have "While using app" selected.

### ISSUE THREAD

**Issue by scottieslg** [transistorsoft/capacitor-background-geolocation#14]
## Your Environment
* Plugin version: 4.2.1
* Platform: iOS
* Device OS version: 12.3
* XCode version: 12.5
* Capacitor info (`npx cap doctor`)
* Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2

## Expected Behavior
If Location Services permissions "While Using the App" is selected, the message "Background Location is not enabled" should not show.

## Actual Behavior
Even though I have selected "While Using the App" under Settings/Location->Allow Location Access, I am getting a pop-up every time that says, "Background location is not enabled. To use background location, you must enable Always in the Location Services settings" 

## Steps to Reproduce
1. Add both @transistorsoft/capacitor-background-fetch and @transistorsoft/capacitor-background-geolocation to package.json
2. run npx cap sync ios
3. run npx cap open ios
4. Run app in simulator

## Context
Running the app gives an error each time I open the app, even though I have "While using the app" selected for Location Services permissions.

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationRequest`.

**Comment by scottieslg** [comment]
Setting `locationAuthorizationRequest: "WhenInUse"` in the `BackgroundGeolocation.ready` function fixed this.

**Comment by ZupitDevs** [comment]
@christocracy Hi, we're experiencing the same problem with iOS 15.5 (plugin version 4.8.0). Even though the config sets `locationAuthorizationRequest: 'Always'` neither the simulator or the actual iOS device shows the "Change to Always Allow"  alert. But the plugin keeps on showing the alert with "Background location is not enabled. To use background location, you must enable Always in the Location Services settings" 

Here's the config used for the plugin:

```
        const config: Config = {
            reset: true,

            // Geolocation Config
            distanceFilter: 10,
            locationAuthorizationRequest: 'Always',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,

            notification: {
                title: 'EasyTrucking',
                text: 'Tracciamento trasporto attivo (todo: localize)',
            },

            locationAuthorizationAlert: {
                instructions: 'Testo isturzioni libero (todo: localize)',
                cancelButton: 'Annulla',
                settingsButton: 'Impostazioni',
                titleWhenOff: 'Titolo quando off',
                titleWhenNotEnabled: 'Titolo quando disab.',
            },

            // Activity Recognition
            stopTimeout: 5,

            // Application config
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            autoSync: true,
            batchSync: false,
            startOnBoot: true, // <-- Auto start tracking when device is powered-up.
            stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
            foregroundService: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            url: `${environment.apiUrl}/api/mobile/transport/gps`,
        }
```

**Comment by ZupitDevs** [comment]
For anyone experiencing this issue, take a look at https://github.com/transistorsoft/capacitor-background-geolocation/issues/70 and be sure to include in your `Info.plist` the key `NSLocationAlwaysAndWhenInUseUsageDescription` and relative description

**Comment by thongquach** [comment]
Is there anyway we can completely disable this warning, @christocracy ?
My app already has a custom popup, and I don't want this one to be shown.

**Comment by christocracy** [comment]
Have you tried read the advice and api docs suggested in this *closed* issue?
