### ISSUE TITLE
Location data is inaccurate in certain cases, it show device travelled 2km in just 3 seconds

### ISSUE THREAD

**Issue by mohit-11-dev** [transistorsoft/capacitor-background-geolocation#143]
## Environment
* Plugin version:  "@transistorsoft/capacitor-background-fetch": "^1.0.2",
                              "@transistorsoft/capacitor-background-geolocation": "^4.9.4",
* Platform:  iOS
* Device OS version: All
* Device manufacturer / model: Apple
* XCode version: All
* Capacitor info (`npx cap doctor`):  
 @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
* Plugin config provided to `#ready`:
```
        {
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10,
              url:`${webAdmin.apiAdminUrl}firebase_api/location.php`,
              extras:{email: userId, uid:uid, token: token},
              debug: true,
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,  
              startOnBoot: true
        }
```

## Expected Behavior
It should be able to send location changes for every 10 meter or equivalent to it's speed converted distance

## Actual Behavior
At 692 to 696 there are not accurate data as practically , user took rest at 693 around 2 hours and suddenly it move 2000 meter (2 km) in next 3 second .

![image](https://user-images.githubusercontent.com/51900532/216312340-7909a9b4-7f8f-4003-9c1e-007a24fdf5c6.png)

## Steps to Reproduce
1. Install app 
2. Grant permission to allow all the time and allow track activity permission
3  kill the app

## Context
 Trying to track location and user activity like walking running, cycling, vehicle etc 
## Debug logs
<details>
	<summary>Logs</summary>
 NA
```
</details>

**Comment by christocracy** [comment]
Also see Location.coords.accuracy.  It’s up to you to filter data at your server.

**Comment by mohit-11-dev** [comment]
> Also see Location.coords.accuracy. It’s up to you to filter data at your server.

Location accuracy for the wrong data is 1541.1, what would be the optimum number to apply filter at server?

Also is there any description of what this number means?

**Comment by christocracy** [comment]
A location is not an exact point in space,

it is a circle of radius `accuracy`.  The device is somewhere in that circle.

- the typical accuracy of gps is ~5 meters.  A relatively small circle of probability.
- The typical accuracy indoors is 40-60 meters.  A bigger circle.
- The typical accuracy from cell tower triangulation is ~1000 meters.  A much larger circle.
