### ISSUE TITLE
Older coordinate entries are added at a future timestamp

### ISSUE THREAD

**Issue by mohit-11-dev** [transistorsoft/capacitor-background-geolocation#146]
## Environment
* Plugin version:  "@transistorsoft/capacitor-background-fetch": "^1.0.2",
                              "@transistorsoft/capacitor-background-geolocation": "^4.9.4",
* Platform:  iOS
* Device OS version: All
* Device manufacturer / model: Apple
* XCode version: All
* Capacitor info (`npx cap doctor`):  
 @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1
* Plugin config provided to `#ready`:
```
        {
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10,
              url:`${webAdmin.apiAdminUrl}firebase_api/location.php`,
              extras:{email: userId, uid:uid, token: token},
              debug: true,
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,  
              startOnBoot: true
        }
```

## Expected Behavior
It should be able to send location changes in correct order at correct timestamp

## Actual Behavior
Entry no 6 has older coordinates and entry got pushed at a later timestamp. In this case Location.coord.accuracy meter is also not too high 

![image](https://user-images.githubusercontent.com/51900532/217245709-fbcb56fe-12f2-42a8-aae4-07c70eb82e2e.png)

## Steps to Reproduce
1. Install app 
2. Grant permission to allow all the time and allow track activity permission
3  kill the app

## Context
 Trying to track location and user activity like walking running, cycling, vehicle etc 
## Debug logs
<details>
	<summary>Logs</summary>
 NA
```
</details>

**Comment by christocracy** [comment]
Each location has a `uuid` field so that you can review the plugin logs to see under what circumstances that location was recorded.

**Comment by mohit-11-dev** [comment]
Unable to find anything relevant in logs, I can only see event triggers and api call logs. It still doesn't explain why the coords interchanged.

**Comment by christocracy** [comment]
Sometimes, the native api can provide an unusual location.  You need to provide a uuid of an unusual location along with the corresponding logs from the plugin.
