### ISSUE TITLE
Alternative logic for requestPermission if previously authorized, but then denied later

### ISSUE THREAD

**Issue by alexbainbridge** [transistorsoft/capacitor-background-geolocation#148]
## Your Environment
* Plugin version: 4.10.0
* Platform: iOS
* Device OS version: 16.1.2
* Device manufacturer / model: Apple
* XCode version: 14.2

## Expected Behavior
BackgroundGeolocation.requestPermission() should open the OS permissions dialog more often than it currently does

Instead of (from the documentation)
"If the user has already provided authorization for location-services, the method will resolve successfully immediately."
it could become (proposed logic)
"If the user has already provided authorization for location-services, and that permission remains granted, the method will resolve successfully immediately."

## Actual Behavior
The actual behavior is as described by the documentation. i.e. working as documented.
"If the user has already provided authorization for location-services, the method will resolve successfully immediately."

## Steps to Reproduce
1. Start app
2. User provides authorization for location-services 
3. At some later point, perhaps in a different app session, user goes into OS app permissions, and denies authorization for location-services for this specific app
4. In our app, we can see that they no longer give us permission, we call BackgroundGeolocation.requestPermission() with a hint to the user to turn location back on please, but this resolves immediately and no OS permission dialog shows

## Context
I am trying to catch that the user has later removed location permission, having at one point given authorization. I can see they have done this, but what I can't do is force the permission dialog to open. Instead I have to explain how to find the app starting from general OS settings.

**Comment by christocracy** [comment]
It is up to the OS to allow the permission dialog to be shown.

You typically only get one chance for the OS to show its permissions dialog.  

When you call `.requestPermission()`, the plug-in has sent that request to the OS -- the OS can choose to simple ignore that request if the permissions dialog has already been shown.

Also see event `onProviderChange` to learn about the current state of location authorization.

If you don't configure the plug-in with `disableLocationAuthorizationAlert: true`, the plug-in can show its own dialog with a link to your app's *Settings*.  

![image](https://user-images.githubusercontent.com/14999/220180611-fe314799-f016-4eb0-9f7f-7d2ca7a32750.png)

**Comment by alexbainbridge** [comment]
Thank you. Now I come to look at it, I might have turned off your alert because we are pre-informing with our own information.  I guess what I will do (I need to do more evaluation) is once we have gone through the settings process once, set to update disableLocationAuthorizationAlert back to false, so your plugin can handle after the first moment, with your more astute logic

Thanks!
