### ISSUE TITLE
getGeofence function not implemented

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/capacitor-background-geolocation#15]
TypeError: _transistorsoft_capacitor_background_geolocation__WEBPACK_IMPORTED_MODULE_2__.default.getGeofence is not a function

**Comment by christocracy** [comment]
Thanks.  Will fix ASAP.

**Comment by christocracy** [comment]
Fix is merged to master and released to `4.2.2`

**Comment by JohnyBoy1234** [comment]
The getGeofence method crashes the app, so I think there's a problem with the native implementation on Android.

**Comment by christocracy** [comment]
Stacktrace, please.

**Comment by JohnyBoy1234** [comment]
See below. Should convert the identifier to String... for it not to crash. That being said, I'm not sure the search actually works correctly as the result promise fails. 

8-29 21:08:46.057 32071   487 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
08-29 21:08:46.057 32071   487 E TSLocationManager:   ‼️  Uncaught Exception: the bind value at index 1 is null
08-29 21:08:46.057 32071   487 E TSLocationManager: {...........}
08-29 21:08:46.057 32071   487 E TSLocationManager: java.lang.IllegalArgumentException: the bind value at index 1 is null
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:183)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:219)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1967)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1814)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1685)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1891)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at com.transistorsoft.locationmanager.data.sqlite.GeofenceDAO.find(Unknown Source:33)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$p.run(Unknown Source:12)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 21:08:46.057 32071   487 E TSLocationManager: 	at java.lang.Thread.run(Thread.java:919)
08-29 21:08:46.074 32071 32071 D TSLocationManager: [c.t.l.a.TSLocationManagerActivity onDestroy]

**Comment by JohnyBoy1234** [comment]
Seems like the String identifier is the only issue. Thanks

**Comment by christocracy** [comment]
Show me how you're executing `getGeofence`

**Comment by JohnyBoy1234** [comment]
I'm just saying that when adding geofences, the "identifier" I was adding was a number (which the plugin converts to a string) but the getGeofence(number) crashes it.

**Comment by christocracy** [comment]
>I'm just saying that when adding geofences, the "identifier"

Show me the *exact* data you're using to `addGeofence` and `getGeofence`.
