### ISSUE TITLE
For iOS want to reduce default 200 Mtrs.  stationary geofence to 50 Mtrs. 

### ISSUE THREAD

**Issue by mjoshi2023** [transistorsoft/capacitor-background-geolocation#150]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "^1.0.2" , "@transistorsoft/capacitor-background-geolocation": "^4.9.4" 
* Platform: iOS 
* Device OS version: All
* Device manufacturer / model: Apple
* XCode version: All
* Capacitor info (`npx cap doctor`) :
@capacitor/cli: 4.6.1
@capacitor/core: 4.6.1
@capacitor/ios: 4.6.1
@capacitor/android: 4.6.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
       {
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10,
              stationaryRadius: 50,
              url:`${webAdmin.apiAdminUrl}firebase_api/location.php`,
              extras:{email: userId, uid:uid, token: token},
              debug: true,
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,  
              startOnBoot: true
        }
```

## Expected Behavior

It should reduce geofence from 200 meters to 50 meters. As user will corss that 50 meters geofence will get his location for further processing. 
## Actual Behavior

Build which was generated with above configuration is not sending any type location data to our back end system api, Other build in which only StationaryRadius is removed from configuration working fine.  
## Steps to Reproduce

1. Install app
2. Grand Permissions
3. Kill App
4.

## Context

Trying to reduce 200 meters stationary geofence to 50 meters so will get location updates after crossing 50 meters instead of 200

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
NA....
```

</details>

**Comment by christocracy** [comment]
>Trying to reduce 200 meters stationary geofence to 50 meters so will get location updates after crossing 50 meters instead of 200

This is **impossible**.  The native iOS / Android APIs do not respond to geofences less than 200 meters.
