### ISSUE TITLE
No geofenceInitialTriggerExit

### ISSUE THREAD

**Issue by SchallerStefan** [transistorsoft/capacitor-background-geolocation#159]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "^1.0.3", "https://github.com/orgs/transistorsoft/teams/capacitor-background-geolocation": "^4.11.1"
* Platform: iOS and Android

## Context
Our App needs to do something, when the geofence is either ENTER or EXIT. When creating a geofence and the user is in it, the geofence can send an ENTER event with "geofenceInitialTriggerEntry". But we would need that feature also, when the user is outside of the geofence, when it is created. (e.g. geofenceInitialTriggerExit)

Is there a clean way, to send an exit event on creation ONLY when geofenceInitialTriggerEntry does not fire?

**Comment by christocracy** [comment]
> Is there a clean way, to send an exit event on creation ONLY when geofenceInitialTriggerEntry does not fire?

No.  Measure the distance of the current location to your target geofence’s centre point.

`if ((distance - geofenceRadius) >= 0)`, the device is outside the geofence.

**Comment by SchallerStefan** [comment]
Ok, thank you!
