### ISSUE TITLE
backgroundPermissionRationale is not working on Android

### ISSUE THREAD

**Issue by scottieslg** [transistorsoft/capacitor-background-geolocation#16]
## Your Environment
* Plugin version: 4.2.2
* Platform: Android
* Device OS version: 11
* Capacitor info (`npx cap doctor`)
* Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2

## Expected Behavior
On Android devices, a pop up declaring why I'm using background geolocations should appear.

## Actual Behavior
The backgroundPermissionRationale dialog is not showing.  It goes directly to the permission request.

## Steps to Reproduce
1. Add both @transistorsoft/capacitor-background-fetch and @transistorsoft/capacitor-background-geolocation to package.json
2. run npx cap sync android
3. run npx cap open android
4. Run app in simulator

## Context
I have the following config set up:

```
const state = await BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1000,
    stopTimeout: 1,
    startOnBoot: false,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    locationAuthorizationRequest: "WhenInUse",
    backgroundPermissionRationale: {
        title: "Allow XXXX to access to this device's location in the background?",
        message: "XXXX uses background location services to track where the service techs are and shows them on the desktop schedule map view.  In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
    },
    locationAuthorizationAlert: {
        titleWhenNotEnabled: "Location services are not enabled",
        titleWhenOff: "Location services are off",
        instructions: "XXXX requires background location tracking to be turned on. You must enable 'Always' in location-services",
        cancelButton: "Cancel",
        settingsButton: "Settings"
    }
})

if (!state.enabled)
    BackgroundGeolocation.start();
```
When I run in the emulator, I do not get any kind of pop up window explaining why I'm using background mode.

I've also tried using `locationAuthorizationRequest: "Always",`, to no avail.

**Comment by christocracy** [comment]
You're likely using targetSdkVersion < 30.

Use 30
