### ISSUE TITLE
SDK does not resume sending locations after idle period with Capacitor4 

### ISSUE THREAD

**Issue by cehh** [transistorsoft/capacitor-background-geolocation#160]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "^1.0.0", "@transistorsoft/capacitor-background-geolocation": "^4.7.1",
* Platform: iOS and Android
* Device OS version: Reproducible in all recent versions
* Device manufacturer / model: Reproducible in multiple models
* XCode version: 
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

export class BackgroundLocationService {
  backSubscriptions: Subs[] = [];
  events: any = [];
  ready: boolean;
  enabled: boolean;
  onlineStatus: boolean;
  userAttr: any;
  subscription: Subscription;
  @Select(TaskState) Status$: Observable&lt;any&gt;;
  agentId: any;
  tenantID: any;

  constructor() { }

  async backgroundInit() {
    return new Promise((resolve) =&gt; {
      Auth.currentAuthenticatedUser()
        .then(async (user) =&gt; {
          this.userAttr = user.attributes;
          /// Step 1:  Subscribe to BackgroundGeolocation events.
          let token = (await Auth.currentSession()).getIdToken().getJwtToken();
          this.agentId = this.userAttr.sub;
          this.tenantID = this.userAttr['custom:TENANT_HASH'];
          if ([this.platform.is](http://this.platform.is/)("cordova")) {
            this.backSubscriptions.push(BackgroundGeolocation.onLocation((location) =&gt; {
              this.addEvent('onLocation', location);
            }))

            this.backSubscriptions.push(BackgroundGeolocation.onMotionChange((event) =&gt; {
              this.addEvent('onMotionChange', event);
            }))

            this.backSubscriptions.push(BackgroundGeolocation.onActivityChange((event) =&gt; {
              this.addEvent('onActivityChange', event);
            }))

            this.backSubscriptions.push(BackgroundGeolocation.onProviderChange((event) =&gt; {
              this.addEvent('onProviderChange', event);
            }))
            /// Step 2:  Ready the plugin.
            BackgroundGeolocation.ready({
              // Geolocation Config
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 50,
              persistMode: BackgroundGeolocation.PERSIST_MODE_ALL,
              // Activity Recognition
              stopTimeout: 10,
              // Application config
              debug: false, // &lt;-- enable this hear sounds for background-geolocation life-cycle.
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              url: background_locationUrl,
              extras: {
                agentID: this.agentId,
                tenantID: this.tenantID
              },
              headers: {
                'Authorization': token
              },
              preventSuspend: true,      // &lt;-- Enable this to prevent iOS from suspending your app in the background while in the stationary state
              foregroundService: true,   // &lt;-- make the plugin mostly immune to OS termination due to memory pressure from other apps. 
              stopOnTerminate: false,   // &lt;-- Allow the background-service to continue tracking when user closes the app.
              startOnBoot: true,        // &lt;-- Auto start tracking when device is powered-up.
              autoSync: true,
              autoSyncThreshold: 2,
              batchSync: true
            }).then((state) =&gt; {
              // BackgroundGeolocation is now ready to use.
              this.ready = true;
              this.enabled = state.enabled;
              resolve(this.ready)
              // this.onToggleEnabled(isOnline);
            });
          }
        })
    })
  }
```

## Expected Behavior
The SDK continues sending locations once movement resumes.
 
## Actual Behavior
It seems that the SDK stops sending location updates after the phone is still and it does not resume sending when the movement starts.
The above configuration was working fine with Capacitor3 but it is giving us troubles with Capacitor4

## Steps to Reproduce

1. Do not move for 15 minutes or more so that it goes into static move
2. Start moving
3. Location SDK won't send updates until we call backgroundLocation.start() again.

## Context
We are developing an application to track delivery agents and vehicle fleets.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by cehh** [comment]
Please help us to migrate the configuration to Capacitor4 to track location accurately.

**Comment by cehh** [comment]
![image](https://user-images.githubusercontent.com/506875/230625080-4f0e5a1a-c448-4d35-a0c2-398c63cd4ace.png)
As seen in the picture above, there is a hole in the location tracking

**Comment by cehh** [comment]
We change the configuration to use the default settings:
`BackgroundGeolocation.ready({
              // Geolocation Config
              desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10,
              // Activity Recognition
              stopTimeout: 5,
              // Application config
              debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
              startOnBoot: true,
              url: background_locationUrl,
              extras: {
                agentID: this.agentId,
                tenantID: this.tenantID
              },
              // transistorAuthorizationToken: transisterToken,
              backgroundPermissionRationale: {
                title: "Allow {applicationName} to access to this device's location in the background?",
                message: "{applicationName} uses the location to track the vehicle location on map when the app is closed or not it use, In order to track your activity in the background, please enable background location permission all the time",
              },
              headers: {
                'Authorization': token
              },
              preventSuspend: true,      // <-- Enable this to prevent iOS from suspending your app in the background while in the stationary state
              // foregroundService: true,   // <-- make the plugin mostly immune to OS termination due to memory pressure from other apps. 
              // stopOnTerminate: false,  
              // startOnBoot: true,  // <-- Allow the background-service to continue tracking when user closes the app.
              // autoSync: true,
              // autoSyncThreshold: 2,
              // batchSync: true,
              // isMoving: true
            })`

We still see gaps in the location tracking even with the above default settings. The picture below shows gaps that started around 04-11 14:11:02.575 in the logs.
![image](https://user-images.githubusercontent.com/506875/231268979-53ccf48a-de49-4f35-903d-32019e297e55.png)

Thanks,
Carlos

**Comment by cehh** [comment]
This is the corresponding log file
[background-geolocation-0411.log.gz](https://github.com/transistorsoft/capacitor-background-geolocation/files/11204262/background-geolocation-0411.log.gz)

**Comment by cehh** [comment]
We still see gaps in the location tracking as shown in the picture above, see the gaps between 14:11:02.575 and 14:11:28 as an example.

We are trying to achieve a configuration that consistently reports locations every 100 meters or so. We set the distanceFilter to 10 for debugging purposes as that is the default configuration, but even with 10 we see gaps sometimes.

**Comment by cehh** [comment]
@christocracy I think the gaps in reporting are caused by the OS power savings, which might be shutting down network and GPS. If I disable the power savings on Android settings, then the SDK continues to send location data.

**Comment by cehh** [comment]
![image](https://user-images.githubusercontent.com/506875/231331869-bd73fded-0644-43f4-b00a-9ad4ae48b17d.png)

**Comment by christocracy** [comment]
Yes, it’s certainly your device or environment.

see api docs event onPowerSaveChange to learn when power-save mode is engaged.
