### ISSUE TITLE
Problems with migrating to gradle 8

### ISSUE THREAD

**Issue by SchallerStefan** [transistorsoft/capacitor-background-geolocation#164]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "1.0.3"
* Platform: Android

## Expected Behavior
Migrating to Gradle 8 should work.

## Actual Behavior
Error Message upon an AGP Upgrade Assistant from 7.4.2 to 8.0.0:

Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

## Context
Capacitor has released a v5 release candidate 5.0.0-rc.0. The Migration Tutorial recommends upgrading to gradle 8: https://capacitorjs.com/docs/next/updating/5-0#update-gradle-plugin-to-800
But upgrading the android project does not work (see Actual Behavior).
This Issue "https://github.com/ionic-team/capacitor/issues/6504" says that ALL capacitor-plugins need to migrate the package-Attribute from the Android-Manifest to the module gradle build file (using "namespace").
I did see, that this plugin has set the "peerDependencies" of capacitor-core to "^4.0.0", so I did assume, that it would not work.
But nonetheless, are there already plans, for gradle 8?

**Comment by christocracy** [comment]
This is a minor maintenance task.  It will be done in the next release.

**Comment by christocracy** [comment]
However, upgrading to Gradle 8 will require **all** plugins that you use to be compatible.  I don't think that'll happen for months.

I would avoid Gradle 8 until later this year.

**Comment by SchallerStefan** [comment]
@christocracy in our special case, we are mainly using capacitors official plugins (for which there are already beta-versions with the namespace "fix") and yours.
But you are right. We will delay upgrading Gradle 8. Thank you for the quick response!

**Comment by christocracy** [comment]
Ok, I have done a test with Gradle 8, adding the `namespace` attribute manually to all installed plugins and I can get my /example app to compile.

**Comment by ryaa** [comment]
It seems that gradle 8 is required for the capacitor 5 plugins - see https://capacitorjs.com/docs/updating/plugins/5-0#update-gradle-plugin-to-800

**Comment by christocracy** [comment]
Released:
- `capacitor-background-fetch: 5.0.0`
- `capacitor-background-geolocation: 5.0.0`
