### ISSUE TITLE
Gap at the start of the journey

### ISSUE THREAD

**Issue by lydongray** [transistorsoft/capacitor-background-geolocation#168]
## Your Environment
* Plugin version: 4.11.4
* Platform: iOS
* Device OS version: iOS 16.4.1
* Device manufacturer / model: Apple iPhone 8 Plus
* XCode version: 14.3
* Capacitor info: 

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Installed Dependencies:

  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/cli: 4.8.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
await BackgroundGeolocation.ready({
  // Geolocation Config
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  stopTimeout: 5,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: true,
  startOnBoot: false,
  showsBackgroundLocationIndicator: true,
  logMaxDays: 1,
  locationAuthorizationRequest: 'Always',
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "Location Services not enabled",
    titleWhenOff: "Location Services OFF",
    instructions: "You should enable 'Always' in Location Services",
    cancelButton: "Cancel",
    settingsButton: "Settings"
  },
  backgroundPermissionRationale: {
    title: "Allow {applicationName} to access this device's location in the background?",
    message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
    positiveAction: "Change to {backgroundPermissionOptionLabel}",
    negativeAction: "Cancel"
  },
  notification: {
    title: "Location Tracking",
    text: "Background location services activated",
    sticky: true,
  },
});
```

## Expected Behavior
Background Geolocation plugin to capture locations that are close together and that follow the travelled route.

## Actual Behavior
Background Geolocation plugin has gaps at the start of the journey.

## Context
I seem to be able to consistently get gaps at the start of the journey. I start location tracking at about 16:54 and immediately lock the device. You can see the gap between 16:54 and 16:56 where the location jumps around 800m. The rest of the journey however captures lots of locations so it is really only the start of the journey that I'm having issues with. Coincidentally (or not), all my tests that have this large gap between locations also equate to about 2 minutes. Thank you for your assistance :)

## Debug logs
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
[log.txt.gz](https://github.com/transistorsoft/capacitor-background-geolocation/files/11449593/log.txt.gz)
```

</details>

**Comment by christocracy** [comment]
Yes, that’s normal.  iOS requires movement of at least 200 meters before tracking initiates.  See wiki “Philosophy of Operation”.

you can manually toggle the plug-in into the “moving” state via method .changePace(true).
