### ISSUE TITLE
How to use this plugin on Chinese phones without Google Play?

### ISSUE THREAD

**Issue by Riuhou** [transistorsoft/capacitor-background-geolocation#17]
Android is China’s most popular mobile operating system, but, paradoxically, smartphones sold in China cannot have Google services pre-installed.
![38399a2811d63642036272d6edd2acc](https://user-images.githubusercontent.com/12491872/131477296-731553ab-0e66-4a6f-ac5c-450ff71f3c6c.jpg)

**Comment by christocracy** [comment]
Yes, I'm completely aware of this.

Sorry, this plugin requires apis available only in Play Services.

It will not work for you in China.
