### ISSUE TITLE
Sometimes plugin picks up the points that are far away from where users have traveled.

### ISSUE THREAD

**Issue by projul** [transistorsoft/capacitor-background-geolocation#176]
**Your Environment**

* Plugin version: "@transistorsoft/capacitor-background-fetch": "^5.0.0"
* Platform: iOS or Android
Device OS version: any version

* Device manufacturer / model: iOS and Android any device
XCode version: Version 14.3 (14E222b)

Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.4

**Plugin Config**

```
reset: true,
      debug: false,
      stationaryRadius: 30,
      distanceFilter: 50,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      maxDaysToPersist: 14,
      stopTimeout: 10,
      stopOnTerminate: false,
      heartbeatInterval: 100,
      preventSuspend: true,
      startOnBoot: true,
      enableHeadless: true,
      url: environment.api_url + API_ENDPOINTS.addUserCoords,
      headers: commonObj,
      params: commonObj,
      extras: commonObj,
      locationAuthorizationRequest: (await Device.getInfo()).platform == 'android' ? 'Any' : 'Always',
      disableLocationAuthorizationAlert: true,
      autoSyncThreshold: 5,
      forceReloadOnHeartbeat: true,
      autoSync: true,
      batchSync: true,
```

## Expected Behavior
Plugin should fetch the points accurately.

## Actual Behavior
Sometimes plugin picks up the points that are far away from where users have traveled.

## Steps to Reproduce
Drive a car with iOS or Android device and check on the map. It shows some points where you were not gone while traveling.

## Context
We are a construction company and employees go to their sides with the devices so that employers can track them.

**Comment by projul** [comment]
Any progress on this issue?

**Comment by christocracy** [comment]
>Any progress on this issue?

No.  You've provided information.  No logs, no map screenshot.

Due to the laws of physics, It's completely normal to see periodic poor quality locations depending on the environment and/or device.

**Comment by projul** [comment]
We have regularly experienced two major issues. 
1) Sometimes when the app is in a killed state my location and every setting are turned on. The location tracker starts after half a kilometer.
2) Sometimes the plugin picks up points that are too far along the user's journey. Among the highlighted points mentioned below, the plugin picks up the points that are far away from me.
Please see the attached screenshots.
![0ea78ee8-0671-4a97-828c-7509698a8ed4](https://github.com/transistorsoft/capacitor-background-geolocation/assets/83248819/c6769e4d-22eb-4eaa-936e-12823afa9c19)
![3230ed5d-3577-4a66-826e-4c39225ffc9e](https://github.com/transistorsoft/capacitor-background-geolocation/assets/83248819/e892992f-1195-4a1f-9dfe-36b26adbe8e8)
![cbbb9195-0009-4b87-9598-da8245af8225](https://github.com/transistorsoft/capacitor-background-geolocation/assets/83248819/c9994c90-6af6-4c5b-a4a5-4b234dd5f7d2)

**Comment by christocracy** [comment]
It’s up to you to filter your own data.  See api docs Location.coords.accuracy

**Comment by clementmas** [comment]
> It’s up to you to filter your own data. See api docs Location.coords.accuracy

How do you filter the locations when `autoSync` is enabled? Is there any way to set the minimum accuracy or hook before the sync event?

**Comment by christocracy** [comment]
Filter *at your server*

**Comment by danillo10** [comment]
I have the same problem with the plugin; it's logging locations far from where I am at the date and time it was sent. Those two green points in the middle of the blue points shouldn't be there among the blues but rather near the greens towards the yellow, as is the other green near the yellow.
![Captura de Tela 2024-02-18 às 06 20 25](https://github.com/transistorsoft/capacitor-background-geolocation/assets/9871536/5ff1fe89-e929-46a7-bddc-e69d4be8d783)

**Comment by christocracy** [comment]
See location.coords.accuracy and filter your own data accordingly.

Crappy data **does** happen, depending upon the environment 
, the laws of physics and state of the device at that time.

**Comment by clementmas** [comment]
I'm seeing points recorded very far away from the user's position despite the `accuracy` saying it's not:

```
[12:23:00] -16.9247633, 145.7808033 (accuracy: 3.9 m)
[12:40:00] -17.0832533, 145.7899983 (accuracy: 11.4 m) <-- wrong, it's actually 17 km away
[12:47:00] -16.9247283, 145.78061 (accuracy: 3.9 m)
```

Is there anything we can change in the config to prevent that (beside setting `desiredAccuracy` to `high`)?

What is determining the accuracy? Is it the GPS chip or an algorithm that could be fixed?

**Comment by christocracy** [comment]
> Is there anything we can change in the config to prevent that

No

> Is it the GPS chip

Yes.

**Comment by clementmas** [comment]
I'm sorry to insist but is there really nothing that can be done about this `accuracy` inaccuracy?

These big jumps don't happen when recording with Strava or other tracking apps. How do they do it?

I'm getting bug reports from beta testers because right now it's not usable. They have to manually fix all the jumps.

**Comment by christocracy** [comment]
You’re posting on a closed issue.  I suggest you open a new issue and provide more information.
