### ISSUE TITLE
Experience with background functionality after Capacitor upgrade v4 to v5

### ISSUE THREAD

**Issue by philippks** [transistorsoft/capacitor-background-geolocation#179]
## Your Environment
* Plugin version: Upgrade 4.10 to 5.0
* Platform: both
* Device OS version: various
* Device manufacturer / model: various

## Expected Behavior
We're starting exactly one geofence in background to determine if someone is in this geofence or not. This works in most cases as expected. The geofence is setup after login into the app. From that point, the geofence is triggered in the background. 

Everything should continue to work after the upgrade vom version v4 to v5 (including a change from `playServicesLocationVersion = '20.0.0'` to `googlePlayServicesLocationVersion = '21.0.1'`).

## Actual Behavior
When testing the upgrade, we encountered a problem that the geofences stopped working in the background. After opening the app (which initializes the geofences again), it started to work again. We're currently trying to verify if we can reproduce this problem by "re-doing" the version upgrade. 

## Question

Do you have any experience if the version upgrade could break the geofences which are running in the background? Is there a risk that we break the geofences, when a user updates the app but does not open the app again to re-initialize the geofences?

**Comment by christocracy** [comment]
v4 -> v5 has no effect in plug-in performance.

**Comment by christocracy** [comment]
> Is there a risk that we break the geofences, when a user updates the app but does not open the app again to re-initialize the geofences?

The plug-in automatically reinitializes geofences you added with .addgeofences after upgrade.

Calling .addGeofences stores your geofence information in the plug-in’s SQLite db.

**Comment by christocracy** [comment]
>When testing the upgrade, we encountered a problem that the geofences stopped working in the background

See Wiki *Debugging*.   Provide plugin logs from `.emailLog` method when this occurs.

**Comment by philippks** [comment]
Thanks for your fast reply @christocracy 

I properly verified it again and it seems to work as you mentioned. The geofences still work after upgrading from v4 to v5.

Therefore the issue was related to something else which I couldn't reproduce yet. I'll close this issue.
