### ISSUE TITLE
Where to edit the authorization popup messages [CHANGEME] Background location tracking is required for our app so we can...

### ISSUE THREAD

**Issue by luisurruela** [transistorsoft/capacitor-background-geolocation#18]
## Your Environment
* Plugin version: 4.2.1
* Platform: iOS and Android
* OS version: MacOS 11.5.2
* Device manufacturer / model: Moto G9 Plus
* Capacitor version: 3.2.0

## Expected Behavior
Hi Chris, I need to change the authorization popup messages and I don't know the file I need to edit or if I need to create a new file and where should I put it. 

## Actual Behavior
Two popups are displayed with generic messages like "[CHANGEME] Background location tracking is required for our app so we can..."

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The issue template (which you ignored) asked you whether you're talking about **iOS or Android**.

I can't read your mind.

**Comment by christocracy** [comment]
- for Android, see api docs Config.backgroundPermissionRationale.
- for iOS, see the Setup Docs for .plist entries.
