### ISSUE TITLE
Users experiencing app crashes: java.lang.NullPointerException

### ISSUE THREAD

**Issue by colenso** [transistorsoft/capacitor-background-geolocation#185]
## Your Environment
* Plugin version: 5.0.0
* Platform: Android
* Device OS version: Android 13
* Device manufacturer / model: Samsung Devices particularly S22 5G
* Capacitor info (`npx cap doctor`)
   ```
    💊   Capacitor Doctor  💊 
    
    Latest Dependencies:
    
      @capacitor/cli: 5.2.3
      @capacitor/core: 5.2.3
      @capacitor/android: 5.2.3
      @capacitor/ios: 5.2.3
    
    Installed Dependencies:
    
      @capacitor/cli: 5.0.4
      @capacitor/core: 5.0.4
      @capacitor/android: 5.0.4
      @capacitor/ios: 5.0.4
    
    [success] iOS looking great! 👌
    [success] Android looking great! 👌
   ```
* Plugin config provided to `#ready`:
```<!-- Syntax highlighting:  DO NOT REMOVE -->
BackgroundGeolocation.ready({
      stopOnTerminate: this.stopOnTerminate,
      foregroundService: true,
      url,
      headers,
      xhrFields,
      httpRootProperty: '.',
      locationTemplate,
      distanceFilter: 30,
      elasticityMultiplier: 1.5,
      heartbeatInterval: 60,
      showsBackgroundLocationIndicator: true,
      disableLocationAuthorizationAlert: true,
      notification: {
        title: 'Background Tracking Enabled',
        text: 'Your location is being sent to Company Name.'
      },
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow Company Name to access to this device's location in the background?",
        message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission\n",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
      }
    })
```

## Expected Behavior
App shouldn't crash

## Actual Behavior
I can see `com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition`  `java.lang.NullPointerException` being reported in Google Play Crashes and ANR section.

## Steps to Reproduce
Not been able to reproduce it yet. But some of our users are experiencing this issue and have reported it to us.

**Comment by christocracy** [comment]
Where’s your stacktrace?

**Comment by colenso** [comment]
Here's the stacktrace:
```
Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.getcapacitor.Bridge.lambda$callPluginMethod$0 (Bridge.java:789)
  at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA
  at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run
  at android.os.Handler.handleCallback (Handler.java:978)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at android.os.Looper.loopOnce (Looper.java:238)
  at android.os.Looper.loop (Looper.java:357)
  at android.os.HandlerThread.run (HandlerThread.java:67)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.getcapacitor.PluginHandle.invoke (PluginHandle.java:138)
  at com.getcapacitor.Bridge.lambda$callPluginMethod$0 (Bridge.java:780)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.JSObject.has(java.lang.String)' on a null object reference
  at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition (BackgroundGeolocationPlugin.java:374)
```

**Comment by christocracy** [comment]
>`at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition`

Your stacktrace is referencing a call to `.getCurrentPosition`.  You should post your code where you're using `.getCurrentPosition(options)`.

**Comment by christocracy** [comment]
I cannot reproduce here.

```
 $ npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/ios: 5.2.3
  @capacitor/android: 5.2.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

Your stacktrace references the plugin's Capacitor layer at [line 374 here](https://github.com/transistorsoft/capacitor-background-geolocation/blob/52e7ac4b790073f476f952d41a9285f8ac7b26d1/android/src/main/java/com/transistorsoft/bggeo/capacitor/BackgroundGeolocationPlugin.java#L374), suggesting that the [`JSObject options` here](https://github.com/transistorsoft/capacitor-background-geolocation/blob/52e7ac4b790073f476f952d41a9285f8ac7b26d1/android/src/main/java/com/transistorsoft/bggeo/capacitor/BackgroundGeolocationPlugin.java#L359) is `null`, as if in your Javascript you somehow managed to do this:

```javascript
BackgroundGeolocation.getCurrentPosition() // <-- No options {} provided
```

The typescript compiler will not allow that to build since [that method requires at least 1 argument of type `CurrentPositionRequest](https://github.com/transistorsoft/capacitor-background-geolocation/blob/52e7ac4b790073f476f952d41a9285f8ac7b26d1/src/declarations/BackgroundGeolocation.d.ts#L1056):

```
Failed to compile.

/Users/chris/workspace/background-geolocation/capacitor/capacitor-background-Expected 1-3 arguments, but got 0.  TS2554

  > 154 |       const location = await BackgroundGeolocation.getCurrentPosition();
```

Show me your call to `.getCurrentPosition`.

**Comment by colenso** [comment]
Thanks @christocracy for narrowing it down. I found 1 such instances like this:
```
BackgroundGeolocation.onHeartbeat(() => {
  BackgroundGeolocation.getCurrentPosition();
})
```

I wasn't aware that getCurrentPosition requires arguments. I'm using JavaScript not TypeScript, but maybe this is a good reason and opportunity to make the switch. I'll correct the code.
Strangely this piece of code was added 9 months ago and I'm not sure why it's throwing an error only now in v5 of the plugin.

**Comment by christocracy** [comment]
I will add a sanity-check to the Javascript API.  I wasn't aware people used Capacitor without TS.

```javascript
getCurrentPosition(options:Object) {
  options = options || {};  // <-- sanity check.
  .
  .
  .
}
```

In the meantime, add an empty `{}` to your options -- or better, add some sensible options for that case.

```javascript
BackgroundGeolocation.getCurrentPosition({});
```

**Comment by colenso** [comment]
> I will add a sanity-check to the Javascript API. I wasn't aware people used Capacitor without TS.
> 
> ```js
> getCurrentPosition(options:Object) {
>   options = options || {};  // <-- sanity check.
>   .
>   .
>   .
> }
> ```
> 
> In the meantime, add an empty `{}` to your options -- or better, add some sensible options for that case.
> 
> ```js
> BackgroundGeolocation.getCurrentPosition({});
> ```

Yup. Thank you for your help.
