### ISSUE TITLE
Permissions Popups

### ISSUE THREAD

**Issue by luisurruela** [transistorsoft/capacitor-background-geolocation#19]
## Your Environment
* Plugin version: 4.2.1
* Platform: Android 11
* Device OS version: Motorola G9 Plus
* Device manufacturer / model:
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:

## Expected Behavior
Just one geolocation permission popup before start location service

## Actual Behavior
Currently the app displays 3 popups in android 11 and 2 in android 10, Allow App_Name to access this device's  location?, Allow App_Name to access your physical activity? and Allow App_Name to access to this device's location in the background?

## Context
I need minimum number of geolocation permission popups. Is there a way to reduce the number of these popups?

**Comment by christocracy** [comment]
> Is there a way to reduce the number of these popups?

No.
