### ISSUE TITLE
Under Android is there a way to disable the Google Location Accuracy popup? 

### ISSUE THREAD

**Issue by Yermo** [transistorsoft/capacitor-background-geolocation#193]
## Your Environment
* Plugin version: 5.0.0
* Platform: iOS or Android: Android
* Device OS version: Android 12
* Device manufacturer / model: Google Pixel 3
* XCode version:
* Capacitor info (`npx cap doctor`):
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  private defaultConfig : any = {

    desiredAccuracy: 0,
    distanceFilter: 5,

    stopTimeout: 10,
    stopDetectionDelay: 10,
    stopOnTerminate: false,
    persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,

    // docs say not recommended.

    disableStopDetection: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
    foregroundService: true,

    backgroundPermissionRationale: {
      title: "Allow {applicationName} to access this device's location while recording is turned on even when the app is in the background.",
      message: "Once you press the record button, this app will record your trip even if you put it into the background. Once you press pause, it no longer records any location information.",
      positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
      negativeAction: 'Cancel'
    },
    preventSuspend: true,    
    heartbeatInterval: 60,

    // TEMPORARY

    disableMotionActivityUpdates: true, 
    stationaryRadius: 5,
    geofenceProximityRadius: 7000

  };

```

## Expected Behavior

There should be some way to prevent the annoying "For a better experience, turn on device location, which uses  Google's Location service." prompt after selecting "No thanks" the first time. 
## Actual Behavior

The popup appears each time start() is called. 
## Steps to Reproduce

1. Turn off Google Location Accuracy in Settings -> Location -> advanced
2. Call start. 
3. click No thanks. 
4. call stop and start again. 
5. The popup appears again.

## Context

In my app, I have a record button. If the user is not actively recording, I want to stop the plugin so that under iOS the blue tracking warning bar goes away. However, I have a current location button in my app, which the user may press while not in an actively tracking state. Calling getCurrentPosition() without having started the plugin seems to not work, so in this case, I start the plugin, call getLastPosition, then stop the plugin. 

But each time I do this, the annoying Google location service popup appears under Android. 

While my suspicion is the answer is no, Is there a way to prevent it from appearing when Google Location Accuracy has been set to off? 
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config.disableLocationAuthorizationAlert

**Comment by Yermo** [comment]
Thank you.
