### ISSUE TITLE
Crashes some of our users apps: Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by colenso** [transistorsoft/capacitor-background-geolocation#194]
## Your Environment
* Plugin version: 5.0.0
* Platform: Android
* Device OS version: Android 12
* Device manufacturer / model: 
  * Samsung Galaxy A11 & A02s
  * Motorola G Stylus 5G (2022)
  * Coosea - WindRiver DEMK4119
  * HMD Global - Nokia G400 5G
* Capacitor info (`npx cap doctor`)
   ```
    💊   Capacitor Doctor  💊 
    
   Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

  Installed Dependencies:

  @capacitor/core: 5.2.3
  @capacitor/ios: 5.2.3
  @capacitor/cli: 5.2.3
  @capacitor/android: 5.2.3
    
    [success] iOS looking great! 👌
    [success] Android looking great! 👌
   ```
* Plugin config provided to `#ready`:
```<!-- Syntax highlighting:  DO NOT REMOVE -->
BackgroundGeolocation.ready({
      stopOnTerminate: this.stopOnTerminate,
      foregroundService: true,
      url,
      headers,
      xhrFields,
      httpRootProperty: '.',
      locationTemplate,
      distanceFilter: 30,
      elasticityMultiplier: 1.5,
      heartbeatInterval: 60,
      showsBackgroundLocationIndicator: true,
      disableLocationAuthorizationAlert: true,
      notification: {
        title: 'Background Tracking Enabled',
        text: 'Your location is being sent to Company Name.'
      },
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow Company Name to access to this device's location in the background?",
        message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission\n",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
      }
    })
```

## Expected Behavior
App shouldn't crash

## Actual Behavior
App crashes with this stacktrace:
```
Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ccd4ae6 u0 com.x_b_e.client/com.transistorsoft.locationmanager.service.BackgroundTaskService}
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1924)
       at android.app.ActivityThread.access$2700(ActivityThread.java:248)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7880)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

## Steps to Reproduce
Not been able to reproduce it yet. But some of our users are experiencing this issue and have reported it to us.

**Comment by christocracy** [comment]
Yes, it's a very [well known](https://issuetracker.google.com/issues/254846063) issue among the Android Development Community, where Android provides exactly 5 seconds to promote a `Service` to foreground by calling `.startForeground()`, which the plugin does.

However, if your own app code is consuming time on the Main thread (eg: a SQLite database query or long-running HTTP request), the Main Thread is blocked, preventing the plugin from calling `.startForeground()` in time.

Also, update to the latest version.

**Comment by colenso** [comment]
Thanks. I'll update to the latest plugin version and will re-open this issue if our users face the issue again.

**Comment by christocracy** [comment]
I have the example app for *Cordova*, *React Native* and *Flutter* released to Play Store:  when running in isolation in my own application code, there are no reports of this ANR/Crash.  While there is not yet a published version of the *Capacitor* version (for no other reason than laziness), every different framework uses literally the *exact* same SDK code.

**Comment by christocracy** [comment]
<img width="1213" alt="Screenshot 2023-09-04 at 8 28 33 AM" src="https://github.com/transistorsoft/capacitor-background-geolocation/assets/14999/8af4c842-621d-4078-80f6-d90c1dd99ea2">
