### ISSUE TITLE
Requirements and questions about the Play Store validations

### ISSUE THREAD

**Issue by loicparent** [transistorsoft/capacitor-background-geolocation#197]
## Your Environment
* Plugin version: 5.1.2
* Platform: Android
* Device OS version: Android 13 - One UI 5.1
* Device manufacturer / model: Galaxy A51 5G
* Android Studio version: Flamingo 2022.2.1 Patch 2
* Capacitor info
````
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
````
* Plugin config provided to `#ready`:
```javascript
const state = await BackgroundGeolocation.ready({
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  stopTimeout: 5,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: true,
  startOnBoot: false,
  locationAuthorizationAlert: {
    titleWhenOff: this.translate.instant('global.geolocation.instructions'),
    titleWhenNotEnabled: this.translate.instant('global.geolocation.background-disabled'),
    instructions: this.translate.instant('global.geolocation.background-instructions'),
    cancelButton: this.translate.instant('global.actions.close'),
    settingsButton: this.translate.instant('global.acctions.change_settings')
  },
  locationAuthorizationRequest: 'WhenInUse'
});
```

## Expected Behavior
Validation in the Play Store following the Developer Program Policies.

## Actual Behavior
The app is rejected because the use of the Background Location.

## Context
Hello,
I finish to setup the plugin in my app but the release is rejected by the validation of the Play Store (Validated by Apple).
I just wanna know what is the requirements to by compliant with this plugin.

The messages that Google provide to me are:
1. Issue found: Invalid privacy policy
2. Issue found: Prominent disclosure not found

For the first message, I added a new section talking about the uses of the background location.
For the second message, I don't understand what I have to do. 

Should I do something to inform the user of the background location or is there a way to manage this in the plugin?
Is it possible to inform the user and maybe use this plugin without the background mode if the user reject it?

At the moment, I don't require the "Always" mode but the "WhenInUse" mode for the background location and so, I don't get the alert that inform the user about the background location.

_Hope you can help me to be compliant :)
Loïc_

**Comment by christocracy** [comment]
See my blog.  I've published 3 apps with this plugin, including updates last week.

https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353

**Comment by loicparent** [comment]
Hi @christocracy ,

Thank you for the link!

I just setup the same as you except for the `backgroundPermissionRationale` because I don't target the "Always" mode. Is it required even if the `locationAuthorizationRequest` is set on `WhenInUse`?

So, if I understand, I just need to show a custom alert that indicates the use of the background location before the display of the location permission. Is that right?

Also, I wonder if I have to define in AndroidManifest of the application the permission for the ACCESS_BACKGROUND_LOCATION or if this is automatically added with the SDK during the release build?

_Kind regards,
Loïc_

**Comment by christocracy** [comment]
> Also, I wonder if I have to define in AndroidManifest of the application the permission for the ACCESS_BACKGROUND_LOCATION

Read the last paragraph of my blog again.

**Comment by loicparent** [comment]
Hi again,

Thanks for your quick reply !

For my first question, I see in your TypeScript code that this is not required if the `locationAuthorizationRequest` is set on `WhenInUse`. ✅

For my second question, I suppose this is what I have to do: Show an alert informing about the backgroundLocation. ✅

For my third question, in fact, I wondered if I had to add the ACCESS_BACKGROUND_LOCATION because following the instructions [here](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md), I didn't see the step when I should added this line.

**Comment by loicparent** [comment]
But what happens if I add this?
````
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:node="remove" />
````

The location still works but not in the background mode. Is it that?

**Comment by loicparent** [comment]
Hello again,

After testing the several things, I finally opted for the solution of deactivating the background mode. 
I didn't know this was possible before reading your blog post because I hadn't seen this in what I had read in the documentation.

My application don't really needs the background location feature but need a good location feature (that your plugin allows). So that's ok for me. I close the ticket.

So thank you for the information!

_Have a nice day,
Loïc_
