### ISSUE TITLE
Android app hibernation mitigation?

### ISSUE THREAD

**Issue by jitmo** [transistorsoft/capacitor-background-geolocation#199]
Great plugin, does exactly what we need!

**Questions**

Without a user opening an Android-only app for a few months (after onboarding/permission flows) is the typical usage of this plugin sufficient to prevent Android app hibernation (including removal of locations/push permissions)?

If not, would us writing some Java in our app to receive events when this plugin is in headless mode be sufficient to prevent Android app hibernation?

**Android docs**

The Android docs on app hibernation mention the following, although developing for the 1st time at this depth on Android features it's hard to tell if these apply when using this plugin:

"...app usage for hibernation doesn't explicitly require user interaction. As long as a component of the package is invoked, it is still considered app usage. Some examples of this include:

- Apps that have a service or content provider bound by another app on the device or the OS. For example, Input Method Editors (IMEs) or password managers.
- Broadcast receivers in the package receiving an explicit broadcast from an external package.

Note: This excludes usage that would not occur if the app is force stopped. For example, running a job does not count as usage even though the job service component is invoked."

https://developer.android.com/topic/performance/app-hibernation#app-usage-non-examples

**Potentially useful context**

Our Android-only app, for Android 6+, is designed to work almost exclusively in the background, sending updated user locations to our sever then alerting users (via push notification) of nearby animals that could harm them (initially elephants in the Western Ghats region of India).

Staff log animal reports at a lat/lng with radius and our server determines which users are in that circle. Relevant users receive push notifications, with the information on lock-screen usually being enough for them to take action.

We have written a custom Kotlin plugin to read a device's app hibernation status and, during onboarding, show the relevant Android settings to the user (in the Google Play app for Android 6-10 and App Info for 11+) so they can disable app hibernation, although it's a clunky onboarding process which is likely to increase dropoff.

**Comment by christocracy** [comment]
>is the typical usage of this plugin sufficient to prevent Android app hibernation (including removal of locations/push permissions)?

It should be.  As long as the device is periodically moving about in the world.

>Staff log animal reports at a lat/lng with radius 

You should be using the plug-in’s Geofencing features for this.  You could *Push* geofence data to the plug-in to create geofences locally there to force the OS to do some work monitoring geofences.  That should assist preventing your app getting flagged for lack of activity.

**Comment by jitmo** [comment]
Thanks, in case the feature (to guide a user through disabling app hibernation when onboarding or opening the app) is needed later we'll make it server-side configurable and off for now.

Geofences are a great idea, if the app can pick up the geofence data once the animal report is logged server-side. I am not aware of a way to silently push that to all users out on Android.

When an animal report is logged the server checks who is currently in that geofence and sends them a push notification.

For other users (with the app sending its location to the server, when moving more than 500m) the sever calculates if they have entered the geofence and sends them a push notification.

Maybe I'm understanding this wrong; we could script up something to trigger off one or more plugin events, fetching geofences from the server, then look at reducing the motion/location radius before sending the next location to the server.

At first glance that feels like they could miss some alerts, or keeping the same radius but polling for geofences feels like extra data/battery; something we have asked to keep to a bare minimum.

Am I missing something? Could you recommend which events would be best, in headless mode, to fetch geofences from the sever? Or is there a plug-in feature I have overlooked that couple handle this?

**Comment by christocracy** [comment]
> I am not aware of a way to silently push that to all users out on Android.

By sending a "silent push notification", a notification with only JSON in the body and no `message`.  Your client code receives the message, decodes the JSON to send to `BackgroundGeolocation.addGeofence(options)`.

**Comment by jitmo** [comment]
Clarification; not sure of a way to silently push that to all users on Android _where the app has been closed by the user_

For your geolocation plugin we are using enableHeadless=true, stopOnTerminate=false and startOnBoot=true.

For push we are using @capacitor-firebase/messaging which can receive data-only push notifications for background apps.

Showing my ignorance, the assumption was that 'background' covers apps that have been opened but not visible, although wouldn't cover apps closed by the user (unless the plugin settings mean the app is always in the background, which means we are good to go).

If that's the case then the app doesn't need to send location to the server and can rely on geofences registered with the plugin via data-only push notifications (unless you see any issues with this approach).

Will experiment during the week, thanks.
