### ISSUE TITLE
[Android]  Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/capacitor-background-geolocation#2]
Currently failing on Android build for me;

![Screenshot 2021-06-07 at 14 46 07](https://user-images.githubusercontent.com/1065835/121027743-20443300-c79f-11eb-9215-faa2300941ea.png)

```
> Task :app:mergeDebugResources FAILED

Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/alex/Projects/silo/node_modules/@transistorsoft/capacitor-background-fetch/android/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/alex/Projects/silo/android/capacitor-cordova-android-plugins/src/main/libs/
       - file:/Users/alex/Projects/silo/android/app/libs/
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I believe I've followed the setup instructions of both background-geolocation and background-fetch.

```
"@transistorsoft/capacitor-background-fetch": "0.0.3",
"@transistorsoft/capacitor-background-geolocation": "0.0.10",
```

Edit different error after cleaning build:

```
> Task :transistorsoft-capacitor-background-geolocation:generateDebugRFile FAILED

Execution failed for task ':transistorsoft-capacitor-background-geolocation:generateDebugRFile'.
> Could not resolve all files for configuration ':transistorsoft-capacitor-background-geolocation:debugCompileClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Required by:
         project :transistorsoft-capacitor-background-geolocation

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by christocracy** [comment]
Show me the following files:
- android/build.gradle
- android/app/build.gradle

**Comment by alexcroox** [comment]
This was user error, I only added 1 of the 2 maven config required in android/build.gradle. Apologies for wasting your time!

**Comment by sguilly** [comment]
I do the same error.

Maybe improve the documentation to describe the right conf : 

allprojects {
    repositories {
        ...
        maven { url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs") }
        maven { url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs") }
    }
}

**Comment by alexcroox** [comment]
I found the source code of the example app very useful to compare any differences, this could certainly be pushed harder in the docs/FAQs if it's not already 👍

**Comment by christocracy** [comment]
>Maybe improve the documentation to describe the right conf :

Is there something unclear here?

![](https://dl.dropbox.com/s/uij95levw9t5seu/Screen%20Shot%202021-06-10%20at%2010.30.17%20AM.png?dl=1)

- [Setup Guides](https://github.com/transistorsoft/capacitor-background-geolocation#large_blue_diamond-setup-guides)
- [Android Setup Instructions (Required)](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md)
- [📂 `android/build.gradle`](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidappbuildgradle)

**Comment by brian-weasner** [comment]
I had this same issue.
User error, as I put the maven urls in the `buildscript > repositories` config block instead of `allprojects >  repositories`

**Comment by christocracy** [comment]
I think the Setup instructions clearly state exactly to place the maven urls in `allProjects`.

**Comment by brian-weasner** [comment]
Agreed, just commented in the event that someone else didn't read the documentation fully, and assumed the location to paste the maven urls as I did.
