### ISSUE TITLE
app:checkDebugDuplicateClasses - Duplicate class a.a found in modules

### ISSUE THREAD

**Issue by sanvisser** [transistorsoft/capacitor-background-geolocation#200]
## Your Environment
* Plugin version: ^5.0.0
* Platform: Android
* Capacitor info (`npx cap doctor`)
  * Latest Dependencies:
    * @capacitor/cli: 5.3.0
    * @capacitor/core: 5.3.0
    * @capacitor/android: 5.3.0
    * @capacitor/ios: 5.3.0

  * Installed Dependencies:
    * @capacitor/cli: 5.3.0
    * @capacitor/core: 5.2.3
    * @capacitor/android: 5.2.3
    * @capacitor/ios: 5.2.3

* Plugin config provided to `#ready`:
Not relevant

## Expected Behavior
Any combination of not-entirely-related dependencies should work together.

## Actual Behavior
It seems that the combination of `@transistorsoft/capacitor-background-geolocation` (^5.0.0) and `cordova-plugin-smartlook` (^2.0.2) 
do not work together at least on android. Running `ionic cap run android` causes the following problem:
```
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':app:checkDebugDuplicateClasses'.
[capacitor]         > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
[capacitor]         > Duplicate class a.a found in modules jetified-smartlook-analytics-frame-capturer-2.2.0-runtime (com.smartlook.android:smartlook-analytics-frame-capturer:2.2.0) and jetified-tslocationmanager-3.4.5-runtime (com.transistorsoft:tslocationmanager:3.4.5)
```

It seems both libraries use some kind of obfuscation? There is a conflict in the class name 'a.a'. The most accepted fix is to remove either one of them. But in our case this does not make sense since they have entirely different use-cases.

## Steps to Reproduce
1. initialize a fresh ionic capacitor angular project
2. install   "@transistorsoft/capacitor-background-geolocation": "^5.0.0" and "cordova-plugin-smartlook": "^2.0.2"
3. Further configuration of these libraries is not necessary since it is occurs during a gradle task, not during runtime.
4. run `ionic cap run android`

## Context

I'm wondering if this can be fixed in the lib. I do not see a way to configure this on our end.

**Comment by christocracy** [comment]
I’m looking into it.

**Comment by christocracy** [comment]
Try installing version `5.1.4`, just released.

**Comment by sanvisser** [comment]
Hi,  I just checked it, and it works. yay!
Thanks for the quick fix & release 👍
