### ISSUE TITLE
Schedule fails on android

### ISSUE THREAD

**Issue by ivanf-gale** [transistorsoft/capacitor-background-geolocation#202]
## Problem
Not sure if it is misconfiguration or bug, but...
When I am doing `setConfig` with provided `schedule` value the plugin is failing with fatal error and the app crashes.
Here is the payload for this field:
```javascript
[ 
   '2023-08-04-22:30 2023-08-05-07:30',
   '2023-08-14-10:30 2023-08-14-15:30',
   '2023-08-30-06:30 2023-08-30-15:30',
   '2023-08-26-06:30 2023-08-26-15:30',
   '2023-08-24-06:30 2023-08-24-15:30',
   '2023-08-25-12:30 2023-08-25-18:00',
   '2023-08-29-09:30 2023-08-29-14:00',
   '2023-08-31-09:30 2023-08-31-14:00',
   '2023-08-07-14:30 2023-08-07-16:30',
   '2023-08-29-14:30 2023-08-29-23:30',
   '2023-08-03-09:30 2023-08-03-14:00',
   '2023-10-01-14:30 2023-10-01-16:30'
 ]
```

## Your Environment
* Plugin version: 4.11.4
* Platform: Android (didn't check on iOS though)
* Device OS version: Android 13
* Device manufacturer / model: Samsung Galaxy A53 5G
* XCode version:
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/android: 5.4.0
  @capacitor/ios: 5.4.0

Installed Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/android: 4.8.0

[success] iOS looking great! 👌
[error] gale is missing in /Users/catatodev/work/gale-app/android/app/src/main/java/com/perdiem.
        Please create a directory structure matching the Package ID com.perdiem.gale within the
        /Users/catatodev/work/gale-app/android/app/src/main/java directory.
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    reset: true,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 800,
    httpRootProperty: '.',
    heartbeatInterval: 300,
    preventSuspend: true,
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true,
    disableLocationAuthorizationAlert: false,
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: this.getBackgroundPermissionRationale(),
  }
```

## Expected Behavior
Schedule set without errors

## Steps to Reproduce

1. Call .ready() with provided config
2. Call .setConfig() with the following argument
```
  BackgroundGeolocation.setConfig({
     schedule: [ 
       '2023-08-04-22:30 2023-08-05-07:30',
       '2023-08-14-10:30 2023-08-14-15:30',
       '2023-08-30-06:30 2023-08-30-15:30',
       '2023-08-26-06:30 2023-08-26-15:30',
       '2023-08-24-06:30 2023-08-24-15:30',
       '2023-08-25-12:30 2023-08-25-18:00',
       '2023-08-29-09:30 2023-08-29-14:00',
       '2023-08-31-09:30 2023-08-31-14:00',
       '2023-08-07-14:30 2023-08-07-16:30',
       '2023-08-29-14:30 2023-08-29-23:30',
       '2023-08-03-09:30 2023-08-03-14:00',
       '2023-10-01-14:30 2023-10-01-16:30'
    ]
})
```

## Context
I was trying to set schedule for background geolocation tracking. Different time formats didn't help me

## Debug logs

<img width="878" alt="Screenshot 2023-09-15 at 15 05 23" src="https://github.com/transistorsoft/capacitor-background-geolocation/assets/123574687/3bc1c2f6-894d-4df4-b78c-e19e5152b7f8">
<details>
	<summary>Logs</summary>

      <img width="878" alt="Screenshot 2023-09-15 at 15 05 23" src="https://github.com/transistorsoft/capacitor-background-geolocation/assets/123574687/3bc1c2f6-894d-4df4-b78c-e19e5152b7f8">

</details>

**Comment by christocracy** [comment]
I cannot reproduce that with the latest version (`v5.1.4`).

Create for me a simple HelloWorld which reproduces it and push it to a public repo for me.
