### ISSUE TITLE
BackgroundGeolocationHeadlessTask won't build or no logging

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/capacitor-background-geolocation#22]
If you follow the guide: https://github.com/transistorsoft/capacitor-background-geolocation/wiki/Android-Headless-Mode
then BackgroundGeolocationHeadlessTask.java won't build

Saving people a lot of frustration or even worse - people trying to debug their HeadlessTask without any logging to indicate it's actually running:

Open the build.gradle file (Module: android.app)
Go to the section "dependencies { "
Add in that list:
implementation 'org.slf4j:slf4j-api:1.7.25'

You're welcome.

**Comment by christocracy** [comment]
The wiki will be edited to use standard and [`Log`](https://developer.android.com/reference/android/util/Log) methods.

**Comment by christocracy** [comment]
There, Wiki updated to use `android.util.Log` instead.  No need to manually add `org.slf4j`.
