### ISSUE TITLE
Is it possible to use the android simulator to simulate locations/routes?

### ISSUE THREAD

**Issue by ivanbacher** [transistorsoft/capacitor-background-geolocation#220]
Could not find anything in the [docs](https://github.com/transistorsoft/capacitor-background-geolocation/wiki/Debugging#simulating-location) about using the android simulator. Maybe someone has already tried this?

I gave it a shot, but it seems like the the plugin is not recognising this.

![Screenshot 2023-11-14 at 09 59 28](https://github.com/transistorsoft/capacitor-background-geolocation/assets/5493114/7f0ac16b-4991-450e-81fe-62a625b173cc)

I guess the simulator device needs to be tricked into thinking that it is moving?

**Comment by christocracy** [comment]
The plug-in triggers tracking with the motion api (accelerometer + gyroscope).  The motion api doesn't operate in emulator.

You need to manually trigger the tracking state via method changePace(true).

Also see wiki "Debugging" about this.

**Comment by ivanbacher** [comment]
Super, thanks for the quick response.
