### ISSUE TITLE
The plugin stop tracking location randomly until user manually open the app again

### ISSUE THREAD

**Issue by tanuj-g** [transistorsoft/capacitor-background-geolocation#221]
## Your Environment
* Plugin version: 5.0.0
* Platform: Android
* Device OS version: 12
* Device manufacturer / model: realme / RMX2156
* XCode version:
* Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
await BackgroundGeolocation.ready({
      /**
       * Application config
       */
      autoSync: true, // <-- Auto start tracking when device is powered-up.
      /**
       * Permissions Config
       */
      backgroundPermissionRationale: {
        message:
          'Chaine needs location permission when you are assigned load to provide updates. This app collects location data to enable sharing tracking updates with your customers even when the app is closed or not in use.',
        negativeAction: 'Cancel',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        title: "Allow Chaine to access to this device's location in the background?"
      },
      debug: false, // <-- Enable this hear sounds for background-geolocation life-cycle.
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      disableLocationAuthorizationAlert: true,
      distanceFilter: 200,
      elasticityMultiplier: 4,
      extras: {
        ...extras
      },
      headers: {
        ContentType: 'application/json'
      },
      isMoving: true,
      logLevel:
        config.app.STAGE == 'prod' ? BackgroundGeolocation.LOG_LEVEL_ERROR : BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      reset: true,
      showsBackgroundLocationIndicator: false,
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      stationaryRadius: 25,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      stopTimeout: 5,
      /**
       * HTTP Config
       */

      url: config.app.MOBILE_APP_LOCATIONS_URL,
      useSignificantChangesOnly: true //only uses locations determined to be "significant"
    })
```

## Expected Behavior
Plugin should keep tracking location despite the user manually open the app or not

## Actual Behavior
If the user doesn't manually open the app, it randomly stops tracking location until it's manually opened again

## Steps to Reproduce

1. start the app - init the plugin 
2. Gave all correct permission and moved the app to the background 
3. Driver From point A to B (tracking is good) and then stop at point B for 4 hours (so plugin moved to stationary state)
4. Again start Driving from point B to Point A - no tracking & didn't receive any location update
5. Manually open the app and tracking started after that and received the location of Point A 
6. Distance b/w points A to B is 7 miles. and driving time is 25 min

## Context
Trying to correctly track the device location without manually opening every few hours/days (and without rebooting the device)

I encountered a situation where the plugin abruptly ceased transmitting location updates in the background until I opened the app manually. Referring to the log, at line 5123 with the timestamp 11-17 16:27:59.704, there's a message indicating that the BackgroundTaskService stopped. Subsequently, there are no further log entries, nor any background updates. Despite the user travelling around 5 miles, no updates were received during this period.

Later, at 11-17 17:14:36.000, when I manually activated the app, an update was immediately recorded, as evident in the subsequent log entry at line 5125.

One thing I found out is that my app was killed by OS when app location tracking stopped because of the stationary geofence. But as per plugin logic, my app should restart background activity if the user starts moving. But in the above case user moved from Point B to A but still haven't received any location update

## Debug logs
[log.gz](https://github.com/transistorsoft/capacitor-background-geolocation/files/13470224/log.gz)

<details>
	Referring to the log, at line 5123 with the timestamp 11-17 16:27:59.704, there's a message indicating that the BackgroundTaskService stopped. Subsequently, there are no further log entries, nor any background updates. Despite the user travelling around 5 miles, no updates were received during this period.

Later, at 11-17 17:14:36.000, when I manually activated the app, an update was immediately recorded, as evident in the subsequent log entry at line 5125.

```<!-- Syntax highlighting:  DO NOT REMOVE -->
11-17 14:50:31.493 DEBUG [TerminateEvent$a a] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
11-17 16:27:57.927 DEBUG [LoggerFacade$a a] PID: 4
11-17 16:27:57.929 INFO [LoggerFacade$a a] 


11-17 16:27:59.691 DEBUG [b destroy] 
  ✅  DESTROY: 1514ae4d-7fe6-44d6-968f-4060805fe874
11-17 16:27:59.696 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 1
11-17 16:27:59.697 DEBUG [AbstractService finish] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
11-17 16:27:59.704 DEBUG [AbstractService onDestroy] 
  🔴  BackgroundTaskService stopped
11-17 17:14:36.000 DEBUG [LoggerFacade$a a] 
11-17 17:14:36.001 DEBUG [LoggerFacade$a a] PID: 4
11-17 17:14:36.001 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
```

</details>

**Comment by christocracy** [comment]
>Plugin version: 5.0.0

See the [CHANGELOG](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/CHANGELOG.md) and use the latest version.

This plugin is designed to track location regardless if app terminated or device rebooted.  It does not need to be rebooted to continue tracking. 

Any problems are likely specifically related to your device.  See https://dontkillmyapp.com.  It's well-known that certain device manufacturers violate the publicly documented Android API to favour longer battery life.

**Comment by tanuj-g** [comment]
@christocracy 
I encountered a problem with my Android phone where, if a user manually alters the location permission from the phone settings, the provider change event does not occur. This event is only triggered when the user opens the app. However, I need this event to occur in the background as well. There are instances when a user revokes the location permission through the settings but does not open the app, leaving no way for the server to know whether the user still has the correct permissions.

But the above behaviour working fine in the IOS devices

**Comment by christocracy** [comment]
> if a user manually alters the location permission from the phone settings, the provider change event does not occur

That's correct.  Android does not fire an event if the user changes location permission.  There's no way to learn about that until the app is relaunched.

**Comment by tanuj-g** [comment]
@christocracy Thanks for the quick response. 
This plugin sends the location updates in the background but those updates don't contain the provider information. 
is that possible to get the provider information with each location update in the background so that we can handle the above issue?

**Comment by christocracy** [comment]
> that possible to get the provider information with each location update

No.  You are free to call the method .getProviderState() any time you wish.

**Comment by tanuj-g** [comment]
@christocracy 
In this situation, calling .getProviderState() requires the user to open the app. However, I am using this plugin in freight tracking app, where drivers often don't open the app for extended periods, typically ranging from 12 to 18 hours. During this time, we rely on receiving their background location updates, which unfortunately don't include the provider data.

There is a particular challenge when a driver manually goes into their settings and revokes location permission without opening the app. In such cases, we stop receiving background location updates because the driver has removed the permission. Additionally, we don't receive the providerChangeEvent because the driver hasn't opened the app.

I'm considering two possible solutions at the moment:

- Obtain the provider update with each location update.
- Receive the provider change event in the background.

Do you think it's feasible to implement either of these two options? Additionally, do you have any other suggestions on how we can address this grey area with this plugin?

**Comment by christocracy** [comment]
Implement background-fetch, already included as a dependency.

This will allow you to periodically query .getProviderState(), even if app terminated via "headless mode" (see api docs enableHeadless).

There is no possible way to append providerState to each recorded location.

**Comment by tanuj-g** [comment]
@christocracy
As I checked the Android headless documentation on this [Link](https://github.com/transistorsoft/capacitor-background-geolocation/wiki/Android-Headless-Mode)

It is mentioned about you can first consult the cordova plugin CDVBackgroundGeolocation.java

I am using the capacitor plugin, is that setup worked for the capacitor plugin too?

**Comment by christocracy** [comment]
The link is merely wrong.  Find the capacitor plug-in native code in this repo in /Android folder.

Yes, capacitor headless works.  See the /example app here in this repo.

In order to do headless code with capacitor, you are writing pure Java code.  You have no access to your JavaScript code at all.

**Comment by tanuj-g** [comment]
@christocracy Thanks

**Comment by danillo10** [comment]
i had the same problem and i solve closing the plugin in ngOnDestroy in ionic/angular BackgroundGeolocation.stop();
