### ISSUE TITLE
how to send data to api in capacitor background geolocation ionic android when app is closed

### ISSUE THREAD

**Issue by danillo10** [transistorsoft/capacitor-background-geolocation#223]
## Your Environment
* Plugin version: 5.2.4
* Platform: Android
* Device OS version: Android
* Device manufacturer / model: Motorola g53
* XCode version:
* Capacitor info (`npx cap doctor`)
* 💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 5.5.1
  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1

[success] Android looking great! 
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
initBackgroundPlugin() {
    this.subscriptions.push(BackgroundGeolocation.onLocation((location) => {
      this.addEvent('onLocation', location);
    }))

    this.subscriptions.push(BackgroundGeolocation.onMotionChange((event) => {
      this.addEvent('onMotionChange', event);
    }))

    this.subscriptions.push(BackgroundGeolocation.onActivityChange((event) => {
      this.addEvent('onActivityChange', event);
    }))

    this.subscriptions.push(BackgroundGeolocation.onProviderChange((event) => {
      this.addEvent('onProviderChange', event);
    }))

    BackgroundGeolocation.ready({
      autoSync: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      foregroundService: true,
      startOnBoot: true,
      heartbeatInterval: 30,
      preventSuspend: true,
      backgroundPermissionRationale: {
        title: "Permita que o {applicationName} acesse a localização o tempo todo deste dispositivo mesmo quando fechado ou não em uso.",
        message: "Este aplicativo coleta dados de localização para permitir o registro de suas viagens ao trabalho e calcular a distância percorrida.",
        positiveAction: 'Mudar para "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancelar'
      }
    }).then((state) => {
      this.ready = true;
      this.enabled = state.enabled;
      this.addEvent('State', state);
      BackgroundGeolocation.start()
        .finally(() => {
          this.startBackgroundTask()
        })
        .catch((err) => console.log(`Erro ao iniciar background geolocation start: ${err}`))
    }).catch((err) => console.log('Erro ao iniciar o background geolocation'));
  }

stopBackgroundTask() {
    BackgroundGeolocation.stop();
  }

getBackgroundLocation() {
    return new Promise((resolve, reject) => {
      BackgroundGeolocation.getCurrentPosition({persist: true}).then((location: Location) => {
        this.timeStampFormatado = this.getDataFormatada();

        this.convite.latitude = location.coords.latitude;
        this.convite.longitude = location.coords.longitude;
        this.convite.motorista_id = this.convite.motorista_id;
        this.convite.veiculo_id = this.convite.veiculo_id;
        this.convite.user_id = this.convite.motorista_id;
        this.convite.data_hora = this.timeStampFormatado;

        this.localizacaoSubscription = this.create(this.relativeUrl, this.convite)
          .subscribe(
            (data: LocalizacaoResponseInterface) => {
              resolve(data);
            },
            (error) => {
              console.log('Erro ao salvar localizacao, tentando novamente', error);
            }
          );
      }).catch((error) => {
        console.warn('- Location error: ', error);
      });
    });
  }
```

## Expected Behavior

The app send the post to api when is active or in background mode, but when i close the app it`s not working.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you observing logs from the plug-in?  See wiki "Debugging".

**Comment by danillo10** [comment]
> Are you observing logs from the plug-in? See wiki "Debugging".

It is sending the http request now, but when app is close the location event dont send the new latitude, longitude and timestamp updated, it`s the same always when app is close, i`m trying it onlocation event: 
`this.subscriptions.push(BackgroundGeolocation.onLocation(async (location) => {
        console.log(`Registro - Location ${JSON.stringify(location)}`);
        this.zone.run(() => {
          // this.convite.latitude = location.coords.latitude;
          // this.convite.longitude = location.coords.longitude;
          // this.convite.data_hora = new Date(location.timestamp).toISOString().replace('T', ' ').slice(0, 19);
        });

        try {
          console.log(`registro - Localizacao onLocation registrada com sucesso ${JSON.stringify(location)}`);
          this.convite.latitude = location.coords.latitude;
          this.convite.longitude = location.coords.longitude;
          this.convite.data_hora = new Date(location.timestamp).toISOString().replace('T', ' ').slice(0, 19);

          await BackgroundGeolocation.setConfig({
            params: {
              latitude: location.coords.latitude,
              longitude: location.coords.longitude,
              data_hora: new Date(location.timestamp).toISOString().replace('T', ' ').slice(0, 19),
              motorista_id: this.convite.motorista_id,
              user_id: this.convite.motorista_id,
              veiculo_id: this.convite.veiculo_id,
              status: this.convite.status,
              pedido_id: this.convite.pedido_id,
              pedido_detalhe_id: this.convite.pedido_detalhe_id,
              evento: 'onLocation'
            }
          });
          console.log('Localizacao onLocation atualizada com sucesso');
        } catch (error) {
          console.log('Erro ao atualizar localizacao', error);
        }
        this.addEvent('onLocation', location);
      }));`

**Comment by christocracy** [comment]
I suggest you use the plug-in's built-in native http service. 

See api docs "HTTP Guide".

Why are you adding location params to the plugins config??  That's weird.

**Comment by danillo10** [comment]
> I suggest you use the plug-in's built-in native http service.
> 
> See api docs "HTTP Guide".
> 
> Why are you adding location params to the plugins config?? That's weird.

To send to my api, it`s incorrect ?

```
BackgroundGeolocation.ready({
        url: '***',
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json"
        },
        params: {
          latitude: this.convite.latitude,
          longitude: this.convite.longitude,
          motorista_id: this.convite.motorista_id,
          user_id: this.convite.motorista_id,
          veiculo_id: this.convite.veiculo_id,
          status: this.convite.status,
          pedido_id: this.convite.pedido_id,
          pedido_detalhe_id: this.convite.pedido_detalhe_id,
          data_hora: this.convite.data_hora,
          evento: ''
        },
        autoSync: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1, // TODO MUDAR PRA 10
        // locationUpdateInterval: 30000,
        // heartbeatInterval: 30, // TODO 5 MINUTOS
        // maxRecordsToPersist: 1,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        foregroundService: true,
        startOnBoot: true,
        preventSuspend: true,
        backgroundPermissionRationale: {
          title: "Permita que o {applicationName} acesse a localização o tempo todo deste dispositivo mesmo quando fechado ou não em uso.",
          message: "Este aplicativo coleta dados de localização para permitir o registro de suas viagens ao trabalho e calcular a distância percorrida.",
          positiveAction: 'Mudar para "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancelar'
        }
      }).then(async (state) => {
        console.log(`Aplicacao is ready: ${state}`)
        this.ready = true;
        this.enabled = state.enabled;
        this.addEvent('State', state);
        BackgroundGeolocation.start();
      }).catch((err) => console.log('Erro ao iniciar o background geolocation'));
    }
```

**Comment by danillo10** [comment]
OMG, i have the position on the http request, thank you. Solved my 3 days problems hahaha

[2023-12-29 18:15:28] local.INFO: array (
  'location' => 
  array (
    'is_moving' => true,
    'uuid' => 'b26d2254-794e-41c6-a490-316d5af4d111',
    'timestamp' => '2023-12-29T21:15:29.078Z',
    'age' => 91,
    'odometer' => 9442.6,
    'coords' => 
    array (
      'latitude' => -19.8346543,
      'longitude' => -44.0169739,
      'accuracy' => 9.9,
      'speed' => 0.16,
      'speed_accuracy' => 0.09,
      'heading' => 248.94,
      'heading_accuracy' => -1,
      'altitude' => 863.8,
      'ellipsoidal_altitude' => 863.8,
      'altitude_accuracy' => 1.4,
      'age' => 100,
    ),
    'activity' => 
    array (
      'type' => 'still',
      'confidence' => 100,
    ),
    'battery' => 
    array (
      'is_charging' => false,
      'level' => 0.9,
    ),
    'extras' => 
    array (
    ),
  ),
  'latitude' => -19.8345924,
  'longitude' => -44.0169764,
  'data_hora' => '2023-12-29 21:08:21',
  'motorista_id' => 1,
  'user_id' => 1,
  'veiculo_id' => 1,
  'status' => 'Indo carregar',
  'pedido_id' => 22,
  'pedido_detalhe_id' => 192,
  'evento' => 'onLocation',
)
