### ISSUE TITLE
Does Huawei (HMS) require license in debug?

### ISSUE THREAD

**Issue by barart** [transistorsoft/capacitor-background-geolocation#224]
Im working on a Android an Huawei app, im testing whit real devices (2 huawei 1 android) on debug app, the android device work fine but not with the huawei devices, do i need a license for huawei in debug?

**Comment by christocracy** [comment]
The HMS adapter is fully functional in debug builds.

Are you observing the logs?  See wiki "Debugging" to learn how to observe native logs in real time.

**Comment by barart** [comment]
@christocracy Thanks for your reply

Yes im observing the logs, and im trying to figure why; i just make it work on one of the two devices when i changed the targetSdkVersion from 33 to 30, we still doing tests on that device

On the other device here are the relevant (or errors) lines of the log, it seems that it refuses to "get" movements?

`
...
...
2023-12-29 18:19:53.165  1349-2058  InputDispatcher         system_server                        E
Window handle Window{ec759fb u0 com.domain.myapp/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity} has no registered input channel
...
...
...
2023-12-29 18:19:53.327 23253-23253 TSLocationManager       com.domain.myapp             W
[c.t.l.s.ActivityRecognitionService a] ⚠️  Failed to initiate motion-activity updates (ERROR CODE: 10301, ACTIVITY_IDENTIFICATION_NOT_AVAILABLE).  This device does not support the Motion API due to missing sensors (eg: gyroscope, accelerometer).
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="ACCELEROMETER", vendor="MTK", version=1, type=1, maxRange=78.4532, resolution=0.0012, power=0.001, minDelay=5000}
╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
╟─ ⚠️  MAGNETOMETER:  none.  Motion-detection system performance will be degraded
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SIGNIFICANT_MOTION", vendor="MTK", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.001, minDelay=-1}
╚═════════════════════════════════════════════
2023-12-29 18:19:53.414  1349-1391  WindowManager           system_server                        I 
Animation done in AppWindowToken{7257ba6 token=Token{5b8d101 ActivityRecord{fec580b u0 com.domain.myapp/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity t785}}} mIsExiting= isHidden:true hiddenRequested:true
2023-12-29 18:19:53.415  1349-1391  WindowManager           system_server                        I 
Exit animation finished in Window{ec759fb u0 com.domain.myapp/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity EXITING}: remove=true
2023-12-29 18:19:53.415  1349-1391  WindowManager           system_server                        E 
win=Window{ec759fb u0 com.domain.myapp/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
...
...
...
2023-12-29 18:19:54.444 23253-23253 TSLocationManager       com.domain.myapp             W 
[c.t.l.s.ActivityRecognitionService a] ⚠️  Failed to initiate activity-transition updates (ERROR CODE: 10301, ACTIVITY_IDENTIFICATION_NOT_AVAILABLE).  This device does not support the Motion API due to missing sensors (eg: gyroscope, accelerometer).
`
I think the plugin do not like the accelerometer and motion sensors? 

This is the device:

huawei med-lx9 (Android studio says)
Huawei Y6p (commercial name): https://www.gsmarena.com/huawei_y6p-10222.php

**Comment by christocracy** [comment]
The plug-in won't work on that device.

> ╟─ ⚠️ GYROSCOPE: none. Motion-detection system performance will be degraded ╟─ ⚠️ MAGNETOMETER: none. Motion-detection system performance will be degraded

**Comment by christocracy** [comment]
> ⚠️ Failed to initiate activity-transition updates (ERROR CODE: 10301, ACTIVITY_IDENTIFICATION_NOT_AVAILABLE)

That is the OS returning that error.

**Comment by barart** [comment]
I see, i though that the accelerometer and significant_motion was enough but not with precision, so, the plugin need the 4 sensors to work?

**Comment by christocracy** [comment]
On Android it can work with just an accelerometer.  Huawei's engineers haven't yet figured out how to do it.

**Comment by barart** [comment]
Understood, so now i will need to code a exception if device is HUAWEI and one of the 4 sensors is missing trigger an alert to the users that the app is not going to work on their device, thanks a lot

**Comment by christocracy** [comment]
The plug-in has a .getSensors() method.  Search the API docs.
