### ISSUE TITLE
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.transistorsoft:tslocationmanager-v21:3.5.3)

### ISSUE THREAD

**Issue by stickypages** [transistorsoft/capacitor-background-geolocation#226]
## Your Environment
* Plugin version: 
```
"@transistorsoft/capacitor-background-fetch": "^5.1.1",
"@transistorsoft/capacitor-background-geolocation": "^5.2.4",
```
* Platform: iOS or Android **ANDROID**
* Device OS version: **Pixel 7 Emulator**
* Device manufacturer / model: **Google Pixel 7**
* XCode version: N/A (using Android)
* Capacitor info (`npx cap doctor`)
```
Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1
```
## Expected Behavior
Expecting Gradle project to sync.

## Actual Behavior
Gradle project sync failed.

`Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.transistorsoft:tslocationmanager-v21:3.5.3, variant=com.transistorsoft:tslocationmanager-v21:3.5.3 configuration compile, variantName=null, artifactFile=PATHTOPROJECT\node_modules\@transistorsoft\capacitor-background-geolocation\android\libs\com\transistorsoft\tslocationmanager-v21\3.5.3\tslocationmanager-v21-3.5.3.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=PATHTOPROJECT\android})`

## Steps to Reproduce
**Purchased a license, yes.**

I have gone through the help document located at:
https://github.com/transistorsoft/capacitor-background-geolocation
AND
https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md

**android/variables.gradle**
```
ext {
	minSdkVersion = 22
	compileSdkVersion = 33
	targetSdkVersion = 33
	androidxActivityVersion = '1.7.0'
	androidxAppCompatVersion = '1.6.1'
	androidxCoordinatorLayoutVersion = '1.2.0'
	androidxCoreVersion = '1.10.0'
	androidxFragmentVersion = '1.5.6'
	firebaseMessagingVersion = '23.1.2'
	playServicesLocationVersion = '21.0.1'
	junitVersion = '4.13.2'
	androidxJunitVersion = '1.1.5'
	androidxEspressoCoreVersion = '3.5.1'
	cordovaAndroidVersion = '10.1.1'
	coreSplashScreenVersion = '1.0.0'
	androidxWebkitVersion = '1.6.1'
}
```

**android/build.gradle**
```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        // capacitor-background-geolocation
        maven { url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs") }
        maven { url 'https://developer.huawei.com/repo/' }
        // capacitor-background-fetch
        maven { url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs") }
    }
}
```

**app/build.gradle**
```
...
Project background_geolocation = project(':transistorsoft-capacitor-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"
...
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            // [background-geolocation] Proguard-rules
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }

```

**AndroidManifest.xml**
```
 <!-- capacitor-background-geolocation licence -->
        <meta-data
            android:name="com.transistorsoft.locationmanager.license"
            android:value="XXXXXX"/>
```

## Context
I'm trying to get the project gradle file to sync/build.
I look in the file system and all files seem to be available that it's referencing. I'm not sure the next best step to debug this issue. 

## Debug logs
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.transistorsoft:tslocationmanager-v21:3.5.3, variant=com.transistorsoft:tslocationmanager-v21:3.5.3 configuration compile, variantName=null, artifactFile=PATHTOPROJECT\node_modules\@transistorsoft\capacitor-background-geolocation\android\libs\com\transistorsoft\tslocationmanager-v21\3.5.3\tslocationmanager-v21-3.5.3.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=PATHTOPROJECT\android})
```

</details>

**Comment by christocracy** [comment]
Seeing jcenter(), deprecated in 2021, in your gradle is a **red flag** that your gradle configuration is out-of-date.

https://developer.android.com/build/jcenter-migration

**Comment by christocracy** [comment]
I suggest you Google the error.  For example.

https://stackoverflow.com/questions/68000516/gradle-null-extracted-folder-for-artifact-resolvedartifact

**Comment by stickypages** [comment]
> I suggest you Google the error. For example.
> 
> https://stackoverflow.com/questions/68000516/gradle-null-extracted-folder-for-artifact-resolvedartifact

Yes, I've looked at this post. However, should the code provided in the 'setup guide' be a better implementation?
`url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs")
`
Using the **projectDir** instead of the hardcoded path?

I will look into my gradle file more, but it still seems to be related to the path directory. If I'm not to use the **projectDir**. What would be the best file path to use according to your plugin?

Thanks in advance.

**Comment by stickypages** [comment]
I updated my build.gradle file. commented our jcenter() etc. But I'm still getting the same error. I'm really at a loss on how to proceed, guess I should not have spent $400 quite yet on your setup. Any help would be greatly appreciated.

```
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.transistorsoft:tslocationmanager-v21:3.5.3, variant=com.transistorsoft:tslocationmanager-v21:3.5.3 configuration compile, variantName=null, artifactFile=PATHTOPROJECT\node_modules\@transistorsoft\capacitor-background-geolocation\android\libs\com\transistorsoft\tslocationmanager-v21\3.5.3\tslocationmanager-v21-3.5.3.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=PATHTOPROJECT\android})
```

**Comment by christocracy** [comment]
I suggest you practice installing the plugin into a freshly generated *HelloWorld* app.

**Comment by christocracy** [comment]
> However, should the code provided in the 'setup guide' be a better implementation?

No, there's nothing wrong with the Setup Instructions.  That's not where your problem lies.

**Comment by Dwarfjazzer** [comment]
I was just having the same issue and not sure if you found the solution but what helped me was this

https://github.com/facebook/react-native/issues/35168#issuecomment-1304976231

> [@JasonFes](https://github.com/JasonFes) I had a similar error, it wasn't obvious that I was running out of memory but I bumped up the maximum size of memory allocation pool by adding:
> 
> `org.gradle.jvmargs=-Xmx4096M`
> 
> to gradle.properties
> 
> It worked after. I hope it helps, it's from here https://stackoverflow.com/a/72951758/4439092
