### ISSUE TITLE
Send Background GPS updates to server

### ISSUE THREAD

**Issue by stickypages** [transistorsoft/capacitor-background-geolocation#228]
**Your Environment**
Plugin version:
"@transistorsoft/capacitor-background-fetch": "^5.1.1",
"@transistorsoft/capacitor-background-geolocation": "^5.2.4",
Platform: iOS or Android ANDROID
Device OS version: Pixel 7 Emulator
Device manufacturer / model: Google Pixel 7
XCode version: N/A (using Android)
Capacitor info (npx cap doctor)

**Latest Dependencies:**

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

**Installed Dependencies:**

  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

**Expected Behavior**
Run our Firebase function to update our Firebase data when the app is in the background.

**Actual Behavior**
It stops sending updates when I put the app in the background. 

**android/variables.gradle**
```
ext {
	minSdkVersion = 22
	compileSdkVersion = 33
	targetSdkVersion = 33
	androidxActivityVersion = '1.7.0'
	androidxAppCompatVersion = '1.6.1'
	androidxCoordinatorLayoutVersion = '1.2.0'
	androidxCoreVersion = '1.10.0'
	androidxFragmentVersion = '1.5.6'
	firebaseMessagingVersion = '23.1.2'
	playServicesLocationVersion = '21.0.1'
	junitVersion = '4.13.2'
	androidxJunitVersion = '1.1.5'
	androidxEspressoCoreVersion = '3.5.1'
	cordovaAndroidVersion = '10.1.1'
	coreSplashScreenVersion = '1.0.0'
	androidxWebkitVersion = '1.6.1'
}
```

**android/build.gradle**
```
allprojects {
    repositories {
        google()
        mavenCentral()
        // capacitor-background-geolocation
        maven { url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs") }
        maven { url 'https://developer.huawei.com/repo/' }
        // capacitor-background-fetch
        maven { url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs") }
    }
}
```

I'm trying to get the plugin to send updates to Firebase when the app is running in the background. 
Is it required that I use the plugin "firebase adapter"? 
Or do I need to use a native HTTP post in the heartbeat method? (if so, do you happen to have any samples of this that work best?)

I've only been successful when the app is in the foreground.
Would you be able to shed some light on this for the best process and actions to take?

Thanks in advance!

**Comment by christocracy** [comment]
> Is it required that I use the plugin "firebase adapter"?

No, you're free to listen to the plug-in events (eg .onLocation) and do whatever you wish with the data (eg interacting with some sort of 3rd party Firebase plugin).
