### ISSUE TITLE
Different outcomes on same trip

### ISSUE THREAD

**Issue by mwilogis** [transistorsoft/capacitor-background-geolocation#23]
## Your Environment
* Plugin version: Using the demo app in Play store "Cordova BG Geolocation"
* Platform: Android
* Device OS version: (Mobile 1: Android Version 10) (Mobile 2: Android Version 7.0)
* Device manufacturer / model: (Mobile 1: Huawei) (Mobile 2: Sony)
* XCode version: N/A
* Capacitor info (`npx cap doctor`) N/A
* Plugin config provided to `#ready`: N/A

## Expected Behavior
I expect when walking with the two devices, that it sets a location every 10 meters, as the default configuration is setup. Also that the tracking starts from when I walk the first 10 meters.

## Actual Behavior
I have tested with two devices, on two separate walks, same day with some hours apart.

**First walk: (Both devices starting tracking a bit too late)**
Device1:
![Device1_Walk1](https://user-images.githubusercontent.com/91071186/134013171-a5cced56-2b46-452f-93ec-1a7f4b8b58b1.png)

Device2:
![Device2_Walk1](https://user-images.githubusercontent.com/91071186/134013376-f8d4066c-b135-4ff7-8685-e90d07b4843c.png)

**Second walk (Device1 rute is what I expected, Device2 only send a few positions)**
Device1:
![Device1_Walk2](https://user-images.githubusercontent.com/91071186/134013621-6114c9cf-2b19-432c-ba77-7e7b8f6781ee.png)

Device 2:
![Device2_Walk2](https://user-images.githubusercontent.com/91071186/134013649-88be6e43-41a8-4118-b8c6-0bef1e52aae1.png)

## Steps to Reproduce

1. Download the "Cordova BG Geolocation" from play store
2. Register name
3. Go to "advanced"
4. Slide the top right trigger to the side to start gps 
5. Go to settings and disable "Sounds & Notifications"
6. Press the play icon
7. Set the app in background by clicking android home button

## Context
I'm trying to use the app to know if it's stable enough for us to buy a license.

## Debug logs
N/A

**Comment by christocracy** [comment]
- You don't need to press the `[ > ]` button.  That button executes the method `.changePace(true)`.  The plugin automatically engages location-tracking when the device is detected to be moving.
- See https://dontkillmyapp.com and adjust device Settings according to device manufacturer.

**Comment by mwilogis** [comment]
Hi

We implemented the plugin into our app instead of using the demo. We are using a Nokia phone running android 11 with battery saving shut off, like suggested at dontkillmyapp.com. But we still see it takes a long time before it recognizes that it is actually moving, when in background and not touched for a long time, our test we left it for 12 hours.

It took 25 mins before it found that it was moving, I attached a picture of this:
![trip](https://user-images.githubusercontent.com/91071186/142725604-d71a73d7-a54c-4d1b-9eb5-4be8d8ff4a27.png)

I found the related config parameters we are using in your init:
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
stopTimeout: 1,
locationAuthorizationRequest: 'Always'

Could we do anything in the configuration of the plugin to help the phone detect when it's moving much before, so it does not take 25 mins before it starts tracking when in background?

Kind regards

**Comment by christocracy** [comment]
I field test on about 12 devices, one of which is a Nokia that I purchased precisely because it was mentioned on dontkillmyapp.

My experience with Nokia is the same:  takes a long time to trigger.

No, there's no solution.

**Comment by mwilogis** [comment]
Thanks for the quick answer!

Did you happen to do a test of changing the behavior from using geofences to using timebased, to keep the phone active (with the downside of using the battery much more)?

Like using [locationupdateinterval](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#locationupdateinterval):
distanceFilter: 0,            // Must be 0 or locationUpdateInterval is ignored!
locationUpdateInterval: 60000  // Get a location every 1 min

Maybe this could be an option?

Also do you happen to share your findings about the 12 different devices, so we know which are better/worse in detecting the change from stationary to moving? Would be great to be able to start up with some experience of different manufactures/models.

**Comment by christocracy** [comment]
> with the downside of using the battery much more)?

I'm following the public Android api docs.  I'm not developing for Nokia, Samsung, OnePlus, Huawei, Xiaomi, etc.  I'm not going to attempt any hacks that abuse the user's battery. 

abusive tactics by developers is precisely how we got in this mess with DontKillMyApp.

You can see that Android is making changes to prevent abusive behavior with significant changes to permissions and background behavior since Android 10.

**Comment by mwilogis** [comment]
Could be that users are using the phone differently, like one branch of customers have it 90% in the car charger and it would be valid for them and also you have it as an option in your api, so I thought it would be a viable option for some cases. But you don't engorge that I can tell :) 

What about your findings, did you share it in the docs or in some post/feedback I didn't find? Would like to be able to guide our users around the worst manufactures like Nokia, and also have some suggestions of phones which are very good at triggering the "is moving state", both from your experience with android and iOS please.
