### ISSUE TITLE
Continuously getting provider change events (every 3 seconds) 

### ISSUE THREAD

**Issue by tanuj-g** [transistorsoft/capacitor-background-geolocation#230]
## Your Environment
* Plugin version: 4.10.1
* Platform: iOS or Android : Android
* Device OS version: 11
* Device manufacturer / model: samsung/ SM-G988N
* XCode version:
* Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
await BackgroundGeolocation.ready({
      /**
       * Application config
       */
      autoSync: true, // <-- Auto start tracking when device is powered-up.
      /**
       * Permissions Config
       */
      backgroundPermissionRationale: {
        message:
          'Chaine needs location permission when you are assigned load to provide updates. This app collects location data to enable sharing tracking updates with your customers even when the app is closed or not in use.',
        negativeAction: 'Cancel',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        title: "Allow Chaine to access to this device's location in the background?"
      },
      debug: false, // <-- Enable this hear sounds for background-geolocation life-cycle.
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      disableLocationAuthorizationAlert: true,
      distanceFilter: 200,
      elasticityMultiplier: 4,
      extras: {
        ...extras
      },
      headers: {
        ContentType: 'application/json'
      },
      isMoving: true,
      logLevel:
        config.app.STAGE == 'prod' ? BackgroundGeolocation.LOG_LEVEL_ERROR : BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      reset: true,
      showsBackgroundLocationIndicator: false,
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      stationaryRadius: 25,
      stopOnTerminate: false, // <-- Allow the background service to continue tracking when user closes the app.
      stopTimeout: 5,
      /**
       * HTTP Config
       */

      url: config.app.MOBILE_APP_LOCATIONS_URL,
      useSignificantChangesOnly: true //only uses locations determined to be "significant"
    })
```

## Expected Behavior
The plugin shouldn't send me frequent updates if there is an issue on the OS level then it should be handled on the client side otherwise it is very difficult to handle these things on the backend.

## Actual Behavior
- Constantly getting the provider change event from the plugin and my API is hitting by it.

## Steps to Reproduce
- I am not able to reproduce this on my test Android phones

## Context
I don't have any clue what is happening here you can help me or give me some idea what is the possible root cause of it? 
Currently, this is impacting my backend server because I am getting an insane amount of updates from one user which causing multiple issues including server crashing.

## Debug logs
--- This is happening in production with very few users, I don't have the logs of the user.

I am sending the screenshots of how frequently i am getting the updates: 
all of the updates are from one user and all are providerChange events.

<img width="801" alt="Screenshot 2024-01-30 at 10 47 10 PM" src="https://github.com/transistorsoft/capacitor-background-geolocation/assets/68414149/55c035ca-5c04-4e0d-840b-44571425e240">

Location Update: 
```
{
  "location": {
    "event": "providerchange",
    "provider": {
      "network": true,
      "gps": true,
      "enabled": true,
      "status": 3,
      "accuracyAuthorization": 0,
      "airplane": false
    },
    "is_moving": false,
    "uuid": "*******************",
    "timestamp": "2024-01-30T16:59:32.557Z",
    "odometer": 3268764.8,
    "coords": {
      "latitude": 47.38306662,
      "longitude": -122.23477168,
      "accuracy": 10,
      "speed": 0,
      "speed_accuracy": 0.01,
      "heading": 1,
      "heading_accuracy": 0.1,
      "altitude": 113.7,
      "ellipsoidal_altitude": 113.7,
      "altitude_accuracy": 0.1
    },
    "activity": {"type": "still", "confidence": 100},
    "battery": {"is_charging": false, "level": -21474836},
    "extras": {
      "androidSDKVersion": 30,
      "appVersion": "*******",
      "batteryLevel": 1,
      "connectionType": "unknown",
      "deviceID": "************",
      "deviceManufacturer": "samsung",
      "deviceModel": "SM-G988N",
      "deviceName": "SM-G988N",
      "deviceOS": "android",
      "deviceOSVersion": "11",
      "devicePlatform": "android",
      "driverPhone": "************",
      "iOSVersion": null,
      "isDeviceCharging": false,
      "isDeviceVirtual": false,
      "isNetworkConnected": true,
      "languageCode": "en",
      "userID": "**************************"
    }
  }
}

```

**Comment by christocracy** [comment]
Let me know how to reproduce.

**Comment by tanuj-g** [comment]
> Let me know how to reproduce.

I am also not able to reproduce this, I don't get any clue how it is happening. 
At this moment my app has more than 5K active users and this issue is coming for only around a few of the users for most of the users the plugin worked fine. 


can you please let me give some suggestions on what might be a possible issue or how I can figure out the root cause of this?

@christocracy is it possible to find something from the location update object?

**Comment by tanuj-g** [comment]
@christocracy One thing I noticed for each of these constantly received updates `connectionType": "unknown" is coming always but for the perfect scenario it should be 'wifi' or 'cellular'

**Comment by tanuj-g** [comment]
@christocracy any idea on this, Today again i am facing this issue for different user but the device is same SM-G988N

**Comment by christocracy** [comment]
See https://dontkillmyapp.com

**Comment by tanuj-g** [comment]
> See https://dontkillmyapp.com

But in my case, the background location isn't killed by OS. I am constantly getting the provider change events for only one specific device - SM-G988N, Approx 6-to 7 users using this phone and from all of them I am constantly getting the location updates.

**Comment by tanuj-g** [comment]
@christocracy 

I've identified the root cause of the issue. It seems that one of the users is employing certain techniques to generate a high volume of provider change events, resulting in frequent updates to the latitude and longitude coordinates. These updates often reflect minimal movements, typically within a 100-meter range.

Unfortunately, I haven't been able to determine how this user is achieving this behaviour. Do you have any suggestions on how we can address this situation either within the application or by implementing limitations within the plugin to control the frequency of updates?

Within the plugin, we currently detect fake locations or the use of virtual devices by checking the value of the isMock key. However, in this particular case, the isMock key is not present.

Please note that in the plugin configuration, I've specified values for distanceFilter and elasticityMultiplier, but despite this, I haven't been able to prevent the user from bypassing these limitations.

Your insights or recommendations would be greatly appreciated.

**Comment by christocracy** [comment]
See api docs [Config.disableProviderChangeRecord](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#disableproviderchangerecord)

**Comment by tanuj-g** [comment]
> See API docs [Config.disableProviderChangeRecord](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#disableproviderchangerecord)

@christocracy
Is the purpose of this setting to cease capturing the providerChange event altogether, or does it only halt certain types of provider change events? My inquiry stems from a desire to ensure the providerChange event is triggered for any device whenever there's a change in provider.

**Comment by christocracy** [comment]
By default, the plugin automatically posts a location containing `providerchange` event and associated data to your server.

If you don't want a `providerchange` location recorded and sent to your server each time that event fires, then disable it.

**Comment by tanuj-g** [comment]
@christocracy 
after disabling this, 

do i get the provider change event update when genuinely a provider change occurred like changing cellular network to wifi 
or disabling the Gps or other provider change-related scenarios?

**Comment by christocracy** [comment]
The javascript event `onProviderChange` continues to operate.  The plugin **NO LONGER SEND AN HTTP REQUEST** when the `onProviderChange` event fires.

**Comment by christocracy** [comment]
You can either enable it and accept to deal with your problem on your end, or disable it.

**Comment by tanuj-g** [comment]
> You can either enable it and accept to deal with your problem on your end or disable it.

hmm, ok Thanks buddy @christocracy
