### ISSUE TITLE
Capacitor React App "appStateChange" is triggered every time we call BackgroundGeolocation.requestPermission()

### ISSUE THREAD

**Issue by akshay-rane** [transistorsoft/capacitor-background-geolocation#232]
## Your Environment
* Plugin version: 5.2.4
* Platform: iOS and Android
* Device OS version: Android 11 - ColorOS version 11.1 and iOS version 17.2.1
* Device manufacturer / model: OPPO A54  and iphone 15.
* Capacitor React App.
* "@capacitor/app": "5.0.7",
```javascript <!-- syntax-highlighting:  paste your code below -->
import { App } from "@capacitor/app";

App.addListener("appStateChange", (isActive) => {
console.log("Status changed", isActive);
}).catch((error) => {
console.error("failed", error);
});

const status  = await BackgroundGeolocation.getProviderState();
if (status !== BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE) {
await BackgroundGeolocation.requestPermission();
}
```

## Expected Behavior
App.addListener("appStateChange", (isActive) => {}); should not get triggered
Also BackgroundGeolocation.requestPermission()
should not trigger the actual requestPermission if permission is already granted. so we don't have to check manually for current permission.

## Actual Behavior
App.addListener("appStateChange", (isActive) => {}); gets triggered
BackgroundGeolocation.requestPermission()
gets triggered the actual requestPermission if permission is already granted. so we have to check current permission everytime.

## Steps to Reproduce

1. add a "appStateChange" listener and log message on event capture.
2. call BackgroundGeolocation.requestPermission().
3. check for log message of appStateChange event

## Context
Enable disable a Toggle button to allow accessing location permission for our Capacitor React app.

**Comment by christocracy** [comment]
That's correct.  See api docs Config.disableLocationAuthorizationAlert.

**Comment by ximex** [comment]
the thing is that this also happens if we already have the permission. so i think the `BackgroundGeolocation.requestPermission()` function should check first internally if `(await BackgroundGeolocation.getProviderState()) === BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS` and then do nothing.

**Comment by christocracy** [comment]
The plug-in executes an Android function to ensure the device settings are compatible with the plug-ins requirements.  This requires an invisible Android activity to be shown, which causes your app to briefly report entering the background.  This is expected.

If you don't want this compatibility check to be performed, see api docs Config.disableLocationAuthorizationAlert.

**Comment by ximex** [comment]
ok thanks for the clearification
