### ISSUE TITLE
Flipped if statement in documentation

### ISSUE THREAD

**Issue by ximex** [transistorsoft/capacitor-background-geolocation#233]
If i see that correct the success/error case logging in this two examples are flipped. Also in the HTML docs
https://github.com/transistorsoft/capacitor-background-geolocation/blob/b26d04e61b5d9c3e2df59941c2d8fe8c99185b44/src/declarations/interfaces/Authorization.d.ts#L21-L27
https://github.com/transistorsoft/capacitor-background-geolocation/blob/b26d04e61b5d9c3e2df59941c2d8fe8c99185b44/src/declarations/BackgroundGeolocation.d.ts#L655-L661

**Comment by christocracy** [comment]
Yes.  Do what makes sense.

**Comment by christocracy** [comment]
It should be visible
