### ISSUE TITLE
We are not able to Send location updates to server in Background

### ISSUE THREAD

**Issue by Appsteamvasant** [transistorsoft/capacitor-background-geolocation#238]
## Your Environment
* Plugin version: 
"@transistorsoft/capacitor-background-fetch": "^5.1.1",
"@transistorsoft/capacitor-background-geolocation": "^5.2.4",
* Platform: iOS or Android
* Device OS version: Android 13,14
* Device manufacturer / model: Samsung galaxy note20 ultra 5g
* XCode version: Version 15.1 
* Capacitor info (`npx cap doctor`)
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

We have capacitor-background-geolocation license .

* Plugin config provided to `#ready`:

async configureBackgroundGeolocation() {
    // Step 1:  Listen to BackgroundGeolocation events.
    this.subscribe(BackgroundGeolocation.onEnabledChange(this.onEnabledChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onLocation(this.onLocation.bind(this)));
    this.subscribe(BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onGeofence(this.onGeofence.bind(this)));
    this.subscribe(BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onHttp(this.onHttp.bind(this)));
    this.subscribe(BackgroundGeolocation.onHeartbeat(this.onheartbeat.bind(this)));
    this.subscribe(BackgroundGeolocation.onProviderChange(this.onProviderChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onPowerSaveChange(this.onPowerSaveChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onConnectivityChange(this.onConnectivityChange.bind(this)));
    this.subscribe(BackgroundGeolocation.onAuthorization(this.onAuthorization.bind(this)));

    // Step 2:  Configure the plugin
    BackgroundGeolocation.ready({
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
      distanceFilter: 5000,
      locationAuthorizationRequest: 'Always',
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 60,
      preventSuspend: true,
      // [Android] backgroundPermissionRationale for Always permission.
      backgroundPermissionRationale: {
        title: 'Allow {applicationName} to access to this device`s location in the background?',
        message: 'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel'
      },
      locationAuthorizationAlert: {
        titleWhenOff: 'Activate your location in ALWAYS mode',
        titleWhenNotEnabled: 'Activate your location in ALWAYS mode',
        instructions: 'In order to keep your location updated in the background, please enable "Always" in Location permissions. This is necessary for the application to work correctly and for you to share your current location with your load Info.',
        cancelButton: 'Cancel',
        settingsButton: 'Settings'
      },
      url: environment.api.APP_SERVER_CONTEXT_URL + environment.api.CARRIER_GPS_POSITION_POST_URL,
      headers: {
        Authorization: 'Bearer ' + Token
      },
      method: 'POST',
      params: {
        currentLatitude: 17.5034787,
        currentLongitude: 78.3562719,
        speed: null,
        timestamp: moment().valueOf()
      },
      autoSync: true,
      autoSyncThreshold: 1
    }).then((state) => {
      // Update UI state (toggle switch, changePace button)
      //this.addEvent('State', new Date(), state);
      if (!state.enabled) {
        this.zone.run(() => {
          this.isMoving = state.isMoving;
          this.enabled = state.enabled;
          BackgroundGeolocation.start();
        });
      }
    });
  }

/// @event http
  onHttp(response: HttpEvent) {
    console.log('[event] http: ', response);
    this.addEvent('onHttp', new Date(), response);
  }

  // @HeartBeat
  onheartbeat(event: HeartbeatEvent) {
    console.log("[onHeartbeat] ", event);
    this.addEvent('onheartbeat', new Date(), event);
  }

## Expected Behavior

We need location updates send to server every 5000 meters in distance Filter and send to server every 15 mins in stationary mode (not moving). We are using our own server to update the location.

We also called the HTTP post in the onLocation and  heartbeat method. But not working. Like
// @HeartBeat
  onheartbeat(event: HeartbeatEvent) {
    console.log("[onHeartbeat] ", event);
    // this.addEvent('onheartbeat', new Date(), event);
    BackgroundGeolocation.getCurrentPosition({
      samples: 1,
      persist: true
    }).then((location) => {
      console.log("[getCurrentPosition] ", location);
      this.locationUpdate(location, location.coords.latitude, location.coords.longitude);
    });
  }

## Actual Behavior

When send the location updates to server we got error like 

VM3:269 result BackgroundGeolocation.addListener (#115912697)
main.js:2048 [event] http:  

responseText
: 
"<!doctype html><html lang=\"en\"><head><title>HTTP Status 400 – Bad Request</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class=\"line\" /><h3>Apache Tomcat/9.0.82</h3></body></html>"
status
: 
400
success
: 
false

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm trying to get the plugin to send updates to server when the app is running in the background.

## Debug logs

[Logs.docx](https://github.com/transistorsoft/capacitor-background-geolocation/files/14545253/Logs.docx)

**Comment by christocracy** [comment]
> 400 – Bad Request

It's up to you to configure your server code to accept http requests from the plug-in.

This is your own server saying "I don't know what to do with this".
