### ISSUE TITLE
Android stops sending location to backend randomly even if app is in foreground

### ISSUE THREAD

**Issue by hvma411** [transistorsoft/capacitor-background-geolocation#239]
## Your Environment
* Plugin version: ^5.1.1
* Platform: Android
* Device OS version: Any Android phone
* Device manufacturer / model: Any Android phone
* XCode version: 
* Capacitor info (`npx cap doctor`):
```💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
reset: true,
logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
heartbeatInterval: 60,
preventSuspend: true,
debug: false,
fastestLocationUpdateInterval: 10000,
stopOnTerminate: false,
showsBackgroundLocationIndicator: true,
startOnBoot: true,
persistMode: BackgroundGeolocation.PERSIST_MODE_ALL,
extras: {
	...params,
	os,
},
headers: {
	'x-api-key': 'some api key',
},
params: {
	...params,
	os
},
locationAuthorizationRequest: 'Always',
disableLocationAuthorizationAlert: false,
url: ApiRoutes.COORDS.updateCoords,
backgroundPermissionRationale: {
	'some permission rationale object here'
},
autoSync: true,
batchSync: false,
```

## Expected Behavior

Plugin should get location and send it to our backend

## Actual Behavior

Plugin sends a few locations to our backend and stops even if user is not closing app and still using it.

## Context

We tried a lot of live debugging with logs and it looks like plugin works fine on app init for a few minutes but after that it just stops receiving and sending location. We have added simple logger in methods like onLocation and onHttp to check if these events are firing nad it looks like from beginning it works fine but after some time onHttp stops working (onLocation still works) and after some time even onLocation stops working so we can't se any logs from these events.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki "Debugging".  Learn to enable verbose logging and fetch logs using .emailLog method.

**Comment by christocracy** [comment]
> persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,

Do you know what this does?  It's useless to provide the plug-in an `url` with PERSIST_MODE_NONE

**Comment by christocracy** [comment]
Do you know what persisted does?

Edit your post to provide the correct Config you're using.

**Comment by hvma411** [comment]
Yes, I know. As I can see in documentation it looks like if database is limited and event is not persisted in then it will not be uploaded to our backend by provided url. Am I right?

**Comment by christocracy** [comment]
PERSIST_MODE_NONE means that no locations will be uploaded EVER, no matter what.

Now go outside and gather logs with verbose logging.  Post your log file here using .emailLog

**Comment by danillo10** [comment]
@christocracy i have the same problem, i need to use persistMode: BackgroundGeolocation.PERSIST_MODE_ALL ?

**Comment by christocracy** [comment]
PERSIST_MODE_ALL is the default
