### ISSUE TITLE
Disabling road snapping

### ISSUE THREAD

**Issue by brian-g** [transistorsoft/capacitor-background-geolocation#240]
## Your Environment
* Plugin version: 5.2.4
* Platform: iOS
* Device OS version: 16.7.6
* Device manufacturer / model: Apple iPhone X, MQAJ2LL/A
* XCode version: 15.3
* Capacitor info (`npx cap doctor`)

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/ios: 5.4.0
  @capacitor/android: 5.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
desiredAccuracy: this._bgGeo.DESIRED_ACCURACY_HIGH,
activityType: this._bgGeo.ACTIVITY_TYPE_OTHER_NAVIGATION,
distanceFilter: 0,
disableElasticity: true,
elasticityMultiplier: 1,
locationTimeout: 60,
stationaryRadius: 25,
// ActivityRecognition config
stopTimeout: 5,
stopDetectionDelay: 0,
locationAuthorizationRequest: 'WhenInUse',
// Application config
foregroundService: true,
stopOnTerminate: true,
// Logging / debug config
logMaxDays: 1,
debug: false,
heartbeatInterval: 20,
logLevel: this._bgGeo.LOG_LEVEL_ERROR,
disableStopDetection: true,
```

## Expected Behavior
The GPS is snapping to roads. We never want that behavior. 

## Actual Behavior
Particularly on turns, the coordinates are snapping to the nearest road when the activity type corresponds to in_vehicle. If the activity type is on_bicycle the road snapping is turned off. 

## Steps to Reproduce

1. Using the Transistorsoft example app drive a farmer's field about 20 yards inside a road. 
2. Driving about 20 mph, approach a corner and a corresponding road, and slow down to make the corner. 
3. Results: the GPS coordinates returned are snapped to the nearest road, typically at the corner's exit. 

## Context
Our application has the functionality to allow a farmer to drive their field boundaries for accurate measurement of the size of the field and the planted acres. The road snapping is frustrating to them because now they have to hand-edit the field boundaries. 

The logs are from our app, which uses a slightly older version of the plugin. I was able to reproduce this issue with the example app and logged it to http://tracker.transistorsoft.com/FarmQA. There are 2 relevant logs to the tracker: iPhone10,6-brian-g(capacitor) and iPhone14,3-brian-g(capacitor). The relevant period in the logs is from March 20, 2024 12:00 PM to 12:30 PM. You can see that the newer iPhone (iPhone 14,3) tracks the route I drove perfectly, and it didn't matter how fast or slow I was going. The problem as you can see is with the iPhone X (iPhone 10,6) where the laps I took faster will snap to the road (or just somewhere else). 

I also noted that setting the activityType in the example app (angular) does not seem to persist and I don't know if the setting I tried to set was being applied or not. Apple also seems to have updated its activity types. https://developer.apple.com/documentation/corelocation/clactivitytype. 

Is otherNavigation (CLActivityType) or ACTIVITY_TYPE_OTHER_NAVIGATION the correct activityType that we should use? Is there another setting that would help us out?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
[bad-tracking-DEMOAPP-iPhoneX.log](https://github.com/transistorsoft/capacitor-background-geolocation/files/14672094/bad-tracking-DEMOAPP-iPhoneX.log)

**Comment by christocracy** [comment]
The plug-in does not implement **any kind of “snap to road”** API.  I’m pretty sure “snap-to-road” functionality is provided by map components and you have to pay extra for that.

for example, [Google Maps Snap to Road API](https://developers.google.com/maps/documentation/roads/snap).

**Comment by brian-g** [comment]
Look at the data I provided via the sample app. Something is going on.

**Comment by christocracy** [comment]
The plug-in turns on the native location for iOS `CLLocationManager` and tells it to `startUpdatingLocation`.  The plug-in then delivers those received locations to the `onLocation` event exactly as-provided.

googling “CLLocationManager snap to road”, [this thread](https://stackoverflow.com/questions/73906116/is-there-a-way-to-reliably-prevent-corelocation-coordinates-from-being-snapped-t) might help you.
