### ISSUE TITLE
Slowness when retrieving current position on Android

### ISSUE THREAD

**Issue by loic-parent** [transistorsoft/capacitor-background-geolocation#241]
## Your Environment
* Plugin version: ^5.4.0
* Platform: Android
* Device OS version: 13
* Device manufacturer / model: Galaxy A53 5G (Samsung)
* Capacitor info : 
```
Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
```
* Plugin config provided to `#ready`:
```javascript
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
stopTimeout: 5,
debug: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
stopOnTerminate: true,
startOnBoot: false,
locationAuthorizationRequest: 'WhenInUse'
```

## Expected Behavior
When I call the method `await BackgroundGeolocation.getCurrentPosition()`, the data should arrives without long delay.

## Actual Behavior
With IOS, I get the data directly but with Android, I have a long time corresponding to the timeout (30 seconds).

## Steps to Reproduce
1. Configure the plugin.
2. Request permission if not done.
3. At the opening of the application, call the method await BackgroundGeolocation.getCurrentPosition().

## Context
I try to get the current location of the user at the opening of the application to propose activities around it.

## Debug logs
<details>
	<summary>Logs</summary>

```
[c.t.l.l.TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 1 (76125ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 50.839151,4.354900 hAcc=14.461 et=+20h19m32s798ms alt=204.39999389648438 vAcc=1.0 {Bundle[{battery_level=0.95, is_charging=true, odometer=0.0}]}], time: 1711448464411
```
</details>

**Comment by loic-parent** [comment]
Hi Chris,

I encounter this issue but only for Android. If I define the `timeout` key to 1, so this is ok for Android but I don't have to do this for IOS to have a good loading time. Is it normal behavior?

_Thanks for your help,_
_Loïc_

**Comment by christocracy** [comment]
Show me the options you’re providing to .getCurrentPosition

**Comment by loic-parent** [comment]
Sure, here it is:

```
const location = await BackgroundGeolocation.getCurrentPosition({
	timeout: 30,
	persist: true,
	maximumAge: 5000,
	desiredAccuracy: 10,
	samples: 3,
});
```

**Comment by christocracy** [comment]
Now show me the logs from calling that (enable `debug: true`, as well).  

```
$ adb logcat *:S TSLocationManager:V
```

**Comment by loic-parent** [comment]
I can see this: 
```
2024-03-26 14:09:18.722 10046-10046 Capacitor/Console       com.my.app                    I  File: http://111.111.1.11:8100/main.js - Line 1 - Msg: >>>>> comfmy app
2024-03-26 14:09:18.725 10046-10046 Capacitor/Plugin        com.my.app                    V  To native (Capacitor plugin): callbackId: 43702593, pluginId: BackgroundGeolocation, methodName: getCurrentPosition
2024-03-26 14:09:18.725 10046-10046 Capacitor               com.my.app                    V  callback: 43702593, pluginId: BackgroundGeolocation, methodName: getCurrentPosition, methodData: {"options":{"timeout":30,"persist":true,"maximumAge":5000,"desiredAccuracy":10,"samples":3}}
```

Is that what you wanted?

**Comment by christocracy** [comment]
Are you waiting for `.ready(config)` to resolve *before* calling `.getCurrentPosition`?

```javascript
// NO!
BackgroundGeolocation.getCurrentPosition(options);
BackgroundGeolocation.ready(config);
BackgroundGeolocation.getCurrentPosition(options)

// YES
await BackgroundGeolocation.ready(config);  // <-- await 
const location = await BackgroundGeolocation.getCurrentPosition(options);
```

you must wait for `.ready(config)` to resolve (ie: `await`) before doing anything that requests location.

**Comment by christocracy** [comment]
Also from your logs:

>03-26 14:22:16.493 12117 12226 I TSLocationManager:   ℹ️  Location availability: false

Are you sure you've not disabled Location in your device settings (or disabled Wifi)?

**Comment by christocracy** [comment]
The location ultimately being returned to you is the "last known location" provided by the OS, which is > 75s old.

>║ getCurrentPosition LocationResult: 1 (75384ms old)

**Comment by loic-parent** [comment]
> Are you waiting for `.ready(config)` to resolve _before_ calling `.getCurrentPosition`?

Yes, I use a prepare method to check if it is ready and if not, I launch the ready method. Something like this:

```javascript
async prepare() {
  const state = await BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    stopTimeout: 5,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    stopOnTerminate: true,
    startOnBoot: false,
    locationAuthorizationRequest: 'WhenInUse'
  });

  this.ready = true;
}

async getCurrentPosition() {
  if( !this.ready ) {
    await this.prepare();
  }

  const location = await BackgroundGeolocation.getCurrentPosition({
    timeout: 30,
    persist: true,
    maximumAge: 5000,
    desiredAccuracy: 10,
    samples: 3,
  });
}
```


> Are you sure you've not disabled Location in your device settings (or disabled Wifi)?

Yes, I just check and test again. The location mode is enabled and the wifi stay active too (but I am testing inside a house).



> The location ultimately being returned to you is the "last known location" provided by the OS, which is > 75s old.

Yes, this is strange :/

**Comment by christocracy** [comment]
> ℹ️ Location availability: false

Go outside to test, where your device can see the GPS satellites in space.

**Comment by loic-parent** [comment]
Ok well do some tests now outside. I let you know in a few minutes.

One more thing, I have defined this in the AndroidManifest to use only the foreground location:
```
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:node="remove" />
```

I don't know if this could have an impact on slowness.

**Comment by christocracy** [comment]
>`<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"`

That permission allows your app to turn on location-services while in the background.   Without that permission, your app is not allowed to turn on location-services while your app is in the background.

**Comment by christocracy** [comment]
Removing that permission has no effect on the location api **while your app is in the foreground**.

**Comment by loic-parent** [comment]
> That permission allows your app to turn on location-servic…
> Removing that permission has no effect on the location api while your app is in the foreground.
Ok perfect! This is exactly what I want : Use your plugin (for its accuracy etc.) but don't use background mode.

**Comment by loic-parent** [comment]
I just come back from my outside tests.
With the 4G+ enable and position mode too and the wifi disabled. I get the same behavior: 30 seconds of waiting.

**Comment by christocracy** [comment]
Restart your phone.

**Comment by loic-parent** [comment]
I just try to restart the phone and re-install the application to reset the position choice etc. but no change :/

**Comment by christocracy** [comment]
Try Google maps

**Comment by loic-parent** [comment]
Oh, yes … I think you found what's wrong!
It seems to have the same issue so I suppose this is related to the phone.
I just try with another phone and it works better. (Worse than on Iphone but faster than 30s).

I tried with another phone but inside with the wifi and I got a similar loading time. That's why I thought it was more generalized than that.
**Do you maybe know a way to improve the indoor/wifi location?**

One last question before I close this ticket:
**Is there a way to remove, on Android, the permission alert to allow the access to the physical data?**

![alert-android-physical-data](https://github.com/transistorsoft/capacitor-background-geolocation/assets/63057166/80243132-62db-49d0-b41f-54c7b16875b2)

**Thanks again for your help**

**Comment by christocracy** [comment]
>Do you maybe know a way to improve the indoor/wifi location?

No.  Google and Apple maintain a large, global database of access-points (wifi router) locations whose locations are determined by people moving around using map apps.  The relative location of these routers is calculated based upon the GPS and the detected power-level of the access point.

>Is there a way to remove, on Android, the permission alert to allow the access to the physical data?

See API doc `Config.disableMotionActivityUpdates`

**Comment by loic-parent** [comment]
Ok many thanks for these precisions!

_Regards,
Loïc_
