### ISSUE TITLE
gpsGetCurrentPosition requesting permissions to be Always

### ISSUE THREAD

**Issue by stickypages** [transistorsoft/capacitor-background-geolocation#248]
## Your Environment
* Plugin version:
"@transistorsoft/capacitor-background-fetch": "^5.1.1",
"@transistorsoft/capacitor-background-geolocation": "^5.2.4",
    
* Platform: iOS or Android
iOS

* Device OS version:
iOS 17.4.1

* Device manufacturer / model:
14 Pro Max

* XCode version:
15.3

* Capacitor info (`npx cap doctor`)
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
    url: 'https://post-to-server',
    params: {},
    httpRootProperty: '.',
    headers: {
        'content-type': 'application/json'
    },
    batchSync: false,
    maxBatchSize: 1,
    autoSync: true,
    autoSyncThreshold: 5,
    stopTimeout: 5,
    heartbeatInterval: 60 * 5,
    foregroundService: true,
    maxRecordsToPersist: 100,
    debug: false, 
    logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
    stopOnTerminate: false, 
    startOnBoot: true,       
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    enableHeadless: false,
    distanceFilter: 5, // Meters,
    // stationaryRadius: 5, // iOS only, min distance must move
    stopOnStationary: false,
    preventSuspend: true, // iOS enable continuous tracking in the background
    //locationAuthorizationRequest: 'Always',
    showsBackgroundLocationIndicator: true,
    backgroundPermissionRationale: {
        title: 'Allow our app...',
        message: 'This app collects location data..etc.',
        positiveAction: 'Change to Always Allow',
        negativeAction: 'Cancel'
    },
}
```

## Expected Behavior
Click a button and receive GPS coords 'gpsGetCurrentPosition'

## Actual Behavior
When I click on a button to 'gpsGetCurrentPosition' it notifies me that I need to allow the app to have access 'Always'. I currently have it set to 'While using the app'. 
While on Android it works as I hoped, but iOS keeps asking for the 'Always' permission.

## Context
I have a button that get's the current users location and sends it to a friend.

My Buttons onClick method
```
async gpsGetCurrentPosition() {
        return await BackgroundGeolocation.getCurrentPosition(currentPositionOptions).then(location => {
            return {
                lat: location?.coords?.latitude || null,
                lng: location?.coords?.longitude || null,
            }
        }).catch(error => {
            console.log('[gps] error ', error)
            return error
        })
    }
```

**Comment by christocracy** [comment]
See API docs Config.locationAuthorizationRequest
