### ISSUE TITLE
Unable to generate release build - Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available

### ISSUE THREAD

**Issue by mgravindran** [transistorsoft/capacitor-background-geolocation#249]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "^1.0.4",
    "@transistorsoft/capacitor-background-geolocation": "^4.12.0",
* Platform: iOS and Android
* Device OS version: 
* Device manufacturer / model:
* XCode version: 
* Capacitor info (`npx cap doctor`)    @capacitor/cli: 4.8.1
  @capacitor/core: 4.8.1
  @capacitor/android: 4.8.1
  @capacitor/ios: 4.8.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior
Unable to generate release builds for ios and android. It was working until very recently. Local debugging works.

## Actual Behavior
Error while trying to generate android app bundle and ios bundle
Android Error:
https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
Could not find any matches for com.transistorsoft:tslocationmanager-v21:+

iOS Error:
Library/Developer/Xcode/DerivedData/App-fjuztocypdyclsefefjjkvmijtqi/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/TransistorsoftCapacitorBackgroundGeolocation/TSLocationManager.framework/TSLocationManager[14](TSProviderChangeEvent.o)'; r_address (0x38C002C) is not in bounds of atom 0x3BC0->0x3CB0

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> ^4.12.0",

See the [Changelog](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/CHANGELOG.md) and install latest version.

> Could not find any matches for com.transistorsoft:tslocationmanager-v21:+

You did not correctly follow the require Setup instructions linked in the readme.

**Comment by mgravindran** [comment]
@christocracy Since we are on capactitor 4, the last compatible version is 4.12.0. Is there a more recent version for capacitor 4?

**Comment by christocracy** [comment]
I suggest you invest the time upgrading to the latest version of Capacitor.  It’s not hard.

> Is there a more recent version for capacitor 4?

No

**Comment by mgravindran** [comment]
@christocracy Is there any work around? We have few dependencies that are not yet ready for capacitor 5/6.

**Comment by christocracy** [comment]
What dependencies are not yet ready for 5/6?

> Is there any work around?

No

**Comment by mgravindran** [comment]
@christocracy Some of our custom plugins are not yet built for cap 5/6.
Will start with the migration and see if that solves this issue. 
Just curious, has the maven repos for older versions removed? Is that the issue here?

**Comment by christocracy** [comment]
The maven repos in the master branch reference there latest version.  You need to observe the Setup Instructions from the tagged version you have installed.

**Comment by mgravindran** [comment]
ok i see 4.12.0 needs googlePlayServicesLocationVersion 20.0.0. It is weird that we have been using googlePlayServicesLocationVersion = '21.0.1' for 4 months now with 4.12.0 and have submitted several versions to the store. 
Thanks @christocracy for your timely guidance
