### ISSUE TITLE
Unable to customize the permission popup title and message

### ISSUE THREAD

**Issue by mijeshvazhappilly** [transistorsoft/capacitor-background-geolocation#250]
* Plugin version: 
    "@transistorsoft/capacitor-background-fetch": "^6.0.0",
    "@transistorsoft/capacitor-background-geolocation": "^6.0.1",
* Platform: Android
* Device OS version: 14.x
* Device manufacturer / model: Samsung
* Plugin config provided to `#ready`:
```
BackgroundGeolocation.ready(
      {
        autoSync: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        disableMotionActivityUpdates: true,
        distanceFilter: 0,
        foregroundService: true,
        allowIdenticalLocations: true,
        fastestLocationUpdateInterval: this.intervalTime,
        geofenceProximityRadius: 50,
        locationAuthorizationRequest: 'Always',
        notification: {
          title: this.settings.androidDrawerTitle,
          text: this.settings.androidDrawerText
        },
        backgroundPermissionRationale: {
          title: 'Allow {applicationName} to access your location when the app is closed?',
          message: this.messageService.getCustomMessage('locationInterstitial'),
          positiveAction: 'Change to {backgroundPermissionOptionLabel}',
          negativeAction: 'Cancel'
        },
        locationUpdateInterval: this.intervalTime,
        useSignificantChangesOnly: isIOS,
        stopOnTerminate: false,
        startOnBoot: true
      }).then((state) => {
        console.log("=======> state: "+JSON.stringify(state));
        BackgroundGeolocation.start();
      });
```

## Expected Behavior
The state object returned from ‘BackgroundGeolocation.ready’ is suppose to have the values configured in the 'backgroundPermissionRationale' and the permission popup shows the customized message instead of the default one - '[CHANGEME] This app collects location data for FEATURE X and FEATURE Y'.

## Actual Behavior
We have ensured that we are calling the ‘getCurrentLocation’ method only after the  ‘BackgroundGeolocation.ready’ method is completed and state value is returned but we are still seeing the permission popup with default messages.

state object:
state: {"activityRecognitionInterval":10000,
"allowIdenticalLocations":false,
"authorization":{},"autoSync":true,
"autoSyncThreshold":0,
"backgroundPermissionRationale":{
"title":"Allow {applicationName} to access this device's location even when closed or not in use?",
"message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
"positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":0,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.playermax.sit.regression.BackgroundGeolocationHeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":0,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxMonitoredGeofences":97,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":-1,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false,"didDeviceReboot":false}

## Context
We are trying to customize the permission popup message in the Android app while using the TransistorSoft Background Geolocation plugin.

**Comment by christocracy** [comment]
The only way this can happen is by executing a method which causes the plug-in to request location permission (eg .getCurrentPosition) before .ready(config).

disable all code which references `BackgroundGeolocation` **except for** `.ready` to determine where your problem is coming from.

**Comment by christocracy** [comment]
Also see wiki “Debugging” and learn to observe the plug-in logs in real time via `$ adb logcat`

**Comment by mijeshvazhappilly** [comment]
> The only way this can happen is by executing a method which causes the plug-in to request location permission (eg .getCurrentPosition) before .ready(config).
> 
> disable all code which references `BackgroundGeolocation` **except for** `.ready` to determine where your problem is coming from.

We are invoking only this 'ready' method and after completion we see that the state object is not updated .It has only default values for the 'backgroundPermissionRationale'. I have provided the log of the 'state' object for your reference. it needs to be updated with the values passed in the ''backgroundPermissionRationale' once the 'ready' method is completed, right? Why it is still showing the default message strings?

**Comment by christocracy** [comment]
The only way that can happen is by providing `reset: false` in your Config.

**Comment by mijeshvazhappilly** [comment]
> The only way that can happen is by providing `reset: false` in your Config.

We are not giving the 'reset' as false. Please see the config below for your reference.

{
        autoSync: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        disableMotionActivityUpdates: true,
        distanceFilter: 0,
        foregroundService: true,
        allowIdenticalLocations: true,
        fastestLocationUpdateInterval: this.intervalTime,
        geofenceProximityRadius: 50,
        locationAuthorizationRequest: 'Always',
        notification: {
          title: this.settings.androidDrawerTitle,
          text: this.settings.androidDrawerText
        },
        backgroundPermissionRationale: {
          title: 'Allow {applicationName} to access your location when the app is closed?',
          message: this.messageService.getCustomMessage('locationInterstitial'),
          positiveAction: 'Change to {backgroundPermissionOptionLabel}',
          negativeAction: 'Cancel'
        },
        locationUpdateInterval: this.intervalTime,
        useSignificantChangesOnly: isIOS,
        stopOnTerminate: false,
        startOnBoot: true
      }

**Comment by christocracy** [comment]
> @transistorsoft/capacitor-background-geolocation": "^6.0.1",

Are not lying about the version you’re using?

>”  Upgrading the Capacitor version has lots of implications and we are not in a position to do so, considering the other package dependencies. Could you please suggest a version of TransistorSoft, which has support for the Android SDK34 and runs with Capacitor 4.x?”

**Comment by mijeshvazhappilly** [comment]
> > @transistorsoft/capacitor-background-geolocation": "^6.0.1",
> 
> Are not lying about the version you’re using?
> 
> > ”  Upgrading the Capacitor version has lots of implications and we are not in a position to do so, considering the other package dependencies. Could you please suggest a version of TransistorSoft, which has support for the Android SDK34 and runs with Capacitor 4.x?”

Why should we lie here? We are trying this in a sample project as we did not receive any further response from you for the above query.

**Comment by christocracy** [comment]
Are you attempting to generate a *release* build without a license key?

**Comment by mijeshvazhappilly** [comment]
> Are you attempting to generate a _release_ build without a license key?

no. We already have 65 capacitor TS licenses created from the portal.

**Comment by christocracy** [comment]
Create for me a simple *hello_world* app which reproduces this an share it with me in a public GitHub repo.
