### ISSUE TITLE
How to turn off LocationAuthorizationAlert completely

### ISSUE THREAD

**Issue by stib** [transistorsoft/capacitor-background-geolocation#255]
Hi Chris,

I am displaying different location authorization contextual messages to the user depending on when the user enables capabilities that need location and what location permission the user is in i.e. Never, Always, WhenInUse. In that context I don't want the default locationAuthorizationAlert showing up as well because then there can be multiple alerts and that gets confusing. 

I want to turn off the default locationAuthorizationAlert completely - not have it show at all no matter what the user does. I couldn't find anything on that in my search so I am not sure if I am missing a way to do that - appreciate your help with that.

## Your Environment
* Plugin version: 5.2.4
* Platform: Both iOS and Android
* Device OS version: N/A
* Device manufacturer / model: N/A
* XCode version: N/A
* Capacitor info (`npx cap doctor`)
```
Latest Dependencies:
  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:
  @capacitor/cli: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/ios: 5.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
locationAuthorizationRequest: 'WhenInUse',
// locationAuthorizationAlert. (Commented out)
```

## Expected Behavior
Don't show the default locationAuthorizationAlert

## Actual Behavior
locationAuthorizationAlert shows up under certain scenarios

Thanks,
Sanjay.

**Comment by christocracy** [comment]
Show me a screenshot of what you *think* the locationAuthorizationAlert is.  It probably isn’t what you *think* it is.

**Comment by stib** [comment]
Thanks Chris. Not quite sure of the sequence of permission changes that brings it up but I will try to capture one and post. The reason I am pretty sure it is the locationAuthorizationAlert is because it is almost the exact same alert as shown in documentation [here](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/locationauthorizationalert.html) - the title is "Location services are off" and the text I as I recall has "WhenInUse" instead of "Always" as in the documentation - since my locationAuthorizationRequest is set to "WhenInUse".

With the configuration I have, would the expected behavior be for that alert to not show up at all?

**Comment by stib** [comment]
Hi Chris,

Here is the captured screenshot I referred to earlier. The locationAuthorizationAlert shows on top of the alert I generate. The sequence is the following - 

1. Open settings and give the App the WhenInUse location permission
2. Start the App and initiate location tracking (don't change the permission to Always)
3. Close the App
4. Open settings and change location permission to Never
5. Start the App again

That's when you see the locationAuthorizationAlert show up as in the screenshot below.

Would be great to be able to force it to turn off locationAuthorizationAlert completely.

<img src="https://github.com/transistorsoft/capacitor-background-geolocation/assets/310258/8269e672-673d-4eae-ab7b-da85483ceed6" width=30% height=30%>

Thanks,
Sanjay.

**Comment by christocracy** [comment]
Search API docs `Config.disableLocationAuthorizationAlert`.

**Comment by stib** [comment]
Thank you Chris. Somehow missed that in my original search. That's exactly what I was looking for.

Thanks,
Sanjay.

**Comment by stib** [comment]
Closing the issue - thanks.
