### ISSUE TITLE
When is 'event' equal to 'heartbeat' in the POST schema

### ISSUE THREAD

**Issue by svenbw** [transistorsoft/capacitor-background-geolocation#257]
In the documentation in the HTTP post schema (see https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/location.html#http-post-schema) event can be set to `motionchange`, `geofence` or `heartbeat`.

However the `onHeartbeat` function handler will not post data itself when invoked by the plugin (https://transistorsoft.github.io/capacitor-background-geolocation/classes/backgroundgeolocation.html#onheartbeat). If an update must be sent to the server the `getCurrentPosition` function must be called. Since this is invoked from javascript the event will be missing.

Can anyone give details what the condition(s) are that will set `event` to `heartbeat` in the posted server data?

**Comment by danillo10** [comment]
Same problem

**Comment by christocracy** [comment]
You are free to attach `extras` to your getCurrentPosition call, attaching any meta data you wish.

**Comment by svenbw** [comment]
We're using the extras already.

My original question was mainly to understand under which conditions the event is set to heartbeat because it's in the documentation listed as a possible option.

**Comment by christocracy** [comment]
The docs must be wrong.

**Comment by danillo10** [comment]
They work only with app open, if app is closed heartbeat doesnt work

**Comment by christocracy** [comment]
> if app is closed heartbeat doesnt work

On iOS (nobody has specified iOS vs Android), that’s correct:  no heartbeat after terminate.  Read api docs Config.stopOnTerminate.
