### ISSUE TITLE
Upload Log crashes the app on ios 

### ISSUE THREAD

**Issue by mgravindran** [transistorsoft/capacitor-background-geolocation#259]
## Your Environment
* Plugin version: 6.0.1
* Platform: iOS
* Device OS version: ios 17.12
* Device manufacturer / model: iPhone 11
* XCode version: 15.3 
* Capacitor info (`npx cap doctor`)   @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
[success] iOS looking great! 👌
[success] Android looking great! 👌
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'WhenInUse',
            locationAuthorizationAlert: {
                titleWhenNotEnabled: "Location services are not enabled",
                titleWhenOff: "Location services are off",
                instructions: "App requires location services to be turned on. You must enable 'WhenInUse' in location-services",
                cancelButton: "Cancel",
                settingsButton: "Settings"
            }
```

## Expected Behavior

```javascripot
BackgroundGeolocation.logger.uploadLog('OUR_API_URL').then((success =>{
            this.appService.showMessage('Logs shared successfully', 'success');
        })).catch((error) => {
            console.log("[uploadLog] FAILURE:", error);
        });
```
This should upload the log file to the given endpoint

## Actual Behavior

This causes a crash on ios
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

On Android, there is no crash but instead opens the share window to share the log file via email/other mediums
## Steps to Reproduce

1.
2.
3.
4.

## Context

Upload diagnostic logs for debugiing

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
⚡️  To Native ->  BackgroundGeolocation emailLog 97820628
ℹ️-[TSDBLogger db_save] Log committed
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x19b80c870 0x193b2fc00 0x19b738574 0x19b738188 0x19b73813c 0x1009a5028 0x1034b6b34 0x1034c8258 0x1034b6b34 0x1034c6fec 0x1034c6ba0 0x19b75720c 0x19b753f18 0x19b753668 0x1deb1e5ec 0x19db702b4 0x19db6f8f0 0x1001a56d0 0x1be1a6dcc)
```

</details>

**Comment by christocracy** [comment]
Fixed.  Javascript layer was incorrectly executing `emailLog` instead of `uploadLog`.

Fix published to `6.0.3`.
