### ISSUE TITLE
Prominent Discloser before Runtime permission.

### ISSUE THREAD

**Issue by CodevLabsMalta** [transistorsoft/capacitor-background-geolocation#262]
Hi,

We have an implementation of the module but its not the main functionality of the app. Most of the users will choose not to use the GPS features. 

We are now having an issue with Android approval. We are showing a custom prominent disclosure popup as soon the user opts to switch on the GPS. If the user doesn't accept, the module will not be started.

Android is telling us the following;

**Prominent disclosure not found

Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.** 

Could it be that some permissions are still be tiggered when the app is loaded? We are importing the module but we do not call any methods before the user decides to switch on the GPS.

Any insight on this would be appreciated.

**Comment by christocracy** [comment]
Read my blog about this:  https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353
