### ISSUE TITLE
App Rejected: SDK com.huawei.hms:update

### ISSUE THREAD

**Issue by stickypages** [transistorsoft/capacitor-background-geolocation#264]
I am trying to do an update to our application using your plugin and I've continued to get this error stating
```
SDK: huawei hms update SDK com.huawei.hms:update
```
And this is their request:
_To bring your app into compliance, follow these steps:

You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK.
huawei hms update SDK com.huawei.hms:update: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK._

**This is my Build.gradle**
```
// capacitor-background-geolocation
maven { url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs") }
maven { url 'https://developer.huawei.com/repo/' }
// capacitor-background-fetch
maven { url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs") }
```

If you have some direction in helping me solve this, that would be greatly appreciated.

## Your Environment
* Plugin version: 6.x.x
```
"@transistorsoft/capacitor-background-fetch": "^6.0.0",
"@transistorsoft/capacitor-background-geolocation": "^6.0.3",
```
* Platform: Android
* Device OS version: N/A
* Device manufacturer / model: Google
* XCode version: N/A
* Capacitor info (`npx cap doctor`)
```
@capacitor/cli: 6.1.0
@capacitor/core: 6.1.0
@capacitor/android: 6.1.0
@capacitor/ios: 6.1.0
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(geoLocationConfig).then(async () => {
	console.log('[gps] #1 BackgroundGeoLocation is Ready')

	BackgroundGeolocation.start().then(() => {
		console.log('[gps] #3 Location tracking Has Started')
		this.gpsGetPositionAndUpdateUser().catch((e) => {
			console.log('[gps] #3.1 ERROR:', e, JSON.stringify(e))
		})
		isGpsStarted = true
	})

	this.gpsInitProviderListeners()
	await this.gpsInitBackgroundFetch()
	
	BackgroundGeolocation.onHeartbeat( () => {
		console.log('[gps] #4.2 init onHeartbeat event')
		this.gpsGetPositionAndUpdateUser().then((r) => {
			console.log('[gps] #4.3 SUCCESS:', r, JSON.stringify(r))
		}).catch((e) => {
			console.log('[gps] #4.3 ERROR:', e, JSON.stringify(e))
		})
	});
})
```

## Expected Behavior
Being able to use the latest version to update my app.

## Actual Behavior
App getting rejected for violation of device and network abuse policy

## Steps to Reproduce
Installed version 6, and was unable to get a successful app submission

## Context
Trying to update my app in the app store

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK.
huawei hms update SDK com.huawei.hms:update: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
```

</details>

**Comment by christocracy** [comment]
post your `android/variables.gradle`

**Comment by stickypages** [comment]
Sure! ```android/variables.gradle```

```
ext {
  minSdkVersion = 22
  compileSdkVersion = 34
  targetSdkVersion = 34
  androidxActivityVersion = '1.8.0'
  androidxAppCompatVersion = '1.6.1'
  androidxCoordinatorLayoutVersion = '1.2.0'
  androidxCoreVersion = '1.12.0'
  androidxFragmentVersion = '1.6.2'
  firebaseMessagingVersion = '23.3.1'
  playServicesLocationVersion = '21.0.1'
  junitVersion = '4.13.2'
  androidxJunitVersion = '1.1.5'
  androidxEspressoCoreVersion = '3.5.1'
  cordovaAndroidVersion = '10.1.1'
  coreSplashScreenVersion = '1.0.1'
  androidxWebkitVersion = '1.9.0'
  androidxExifInterfaceVersion = '1.3.6'
  hmsLocationVersion = '6.0.0.302'
  okHttpVersion = '4.9.1'
  localBroadcastManagerVersion = '1.0.0'
}

```

**Comment by christocracy** [comment]
You’re overriding the `hmsLocationVersion` and providing a version **older than** the [plug-in’s default](https://github.com/transistorsoft/capacitor-background-geolocation/blob/c0cc455846dd47b9d49b96b106b1d771c6f7a2ff/android/build.gradle#L36)

just delete that line from your variables.gradle and let the plug-in provide its more recent default version.

**Comment by stickypages** [comment]
Ok thanks i'll give that a go! And report back either way.

**Comment by stickypages** [comment]
@christocracy That seemed to do the trick, thank you!
