### ISSUE TITLE
turn off the plugin in background mode

### ISSUE THREAD

**Issue by danillo10** [transistorsoft/capacitor-background-geolocation#266]
Is it possible to turn off the plugin in background mode without opening the app? For example, I want it to stop tracking when a trip ends.

**Comment by christocracy** [comment]
You are free to call .stop() whenever you wish.

**Comment by danillo10** [comment]
Even if the app is closed? In my case, it is configured to call with the app closed and tracking on, but it does not execute the stop.

**Comment by christocracy** [comment]
> but it does not execute the stop.

Then your own function, where you are calling `.stop()`, is not being executed.  When `.stop()` is called, the plugin stops.

**Comment by danillo10** [comment]
I created with headless, a Java class that stop the plugin when the trip is end. Thank you
