### ISSUE TITLE
Warning with the package background-fetch

### ISSUE THREAD

**Issue by loic-parent** [transistorsoft/capacitor-background-geolocation#269]
## Your Environment
* Plugin version: 6.0.0
* Platform: Android
* Device OS version: 14
* Device manufacturer / model: All
* Capacitor info 
```
💊   Capacitor Doctor  💊
Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  stopTimeout: 5,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: true,
  startOnBoot: false,
  locationAuthorizationRequest: 'WhenInUse'
}
```

## Expected Behavior
No warning in the latest version of Android Studio

## Actual Behavior
Hi Chris, I see this warning in Android Studio:
"Avoid using '+' in version numbers…"
![android-warning](https://github.com/user-attachments/assets/0e2b3d28-2f5b-4785-ae90-fe53f3e302c1)
Should I do something to fix/avoid this?
_Thanks,
Loïc_

## Steps to Reproduce
1. Install the package in Ionic/Capacitor project
2. Run ìonic cap run android --open`
3. Open the Project Structure and see that the dependency is marked as warning
![image](https://github.com/user-attachments/assets/3f1c186b-77f5-4794-a78b-d0913333f3fe)

## Context
Just build the app.

## Debug logs
No specific log to show. This is a warning with the package directly not with the use of it.

**Comment by christocracy** [comment]
Ignore.  The library is loaded locally from the package itself, not via package manager (eg mavenCentral).  There is only one version of the library packaged into the plug-in’s node-module.

**Comment by loic-parent** [comment]
Wow what a quick reply. Thanks :)

Ok, I will ignore it.

_Have a nice day,
Loïc_
