### ISSUE TITLE
documentation: timestamp

### ISSUE THREAD

**Issue by phil-w** [transistorsoft/capacitor-background-geolocation#270]
The docs say: 
~~~
	timestamp,    // <-- Javascript Date instance
~~~

It's actually an ISO format date, which isn't what you get from (say) new Date().
The value is eg: `2024-08-03T15:06:27.743Z`

So that's a string, not an Object.

**Comment by christocracy** [comment]
It’s a mistake in the docs.  It’s a Date instance on Cordova, which shares the same docs.
