### ISSUE TITLE
Tracking not strating when I enable it

### ISSUE THREAD

**Issue by iampapaisarkar** [transistorsoft/capacitor-background-geolocation#272]
## Your Environment
* Plugin version: 6.0.2
* Platform: iOS
* Device OS version: 17.5.1
* Device manufacturer / model: iPhone 13
* XCode version: 15.4
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
          // transistorAuthorizationToken: token,
          // reset: false, // <-- !!WARNING!!  DO NOT USE THIS IN YOUR OWN CODE UNLESS YOU REALLY KNOW WHAT IT DOES
          url: `${process.env.API_URL}/mobile-app-tracker-device-location-store`,
          params: {
              device_token: this.getLocal('deviceToken')
           },
          debug: this.isDev() ?? false,
          locationAuthorizationRequest: 'Always',
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          backgroundPermissionRationale: {
            title:
              "Allow {applicationName} to access this device's location even when closed or not in use.",
            message:
              'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'
          },
          distanceFilter: 5,
          stopTimeout: 1,
          heartbeatInterval: 120,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          autoSync: true,
          maxDaysToPersist: 14
        }).then((state) => {
          this.setBGLready(true)
          this.setBGLenabled(state.enabled)
          this.BGLaddEvent('State', state)
          if (state.schedule.length > 0) {
            BackgroundGeolocation.startSchedule()
          }
          if (config) {
            this.BGLsetConfig(config)
          }
        })
```

## Expected Behavior
When I start tracking, it should begin immediately or within a few seconds. New location data should then be sent to our server.

## Actual Behavior
But actually, it starts tracking a few minutes after being enabled and sends data to the database.

## Steps to Reproduce

1.
2.
3.
4.

## Context
As you can see, the green area represents my home. I start traveling from my home, but the tracking begins a few meters after I start moving. Ideally, it should start from my home or maybe 20-30 meters into the journey, but instead, it only starts after 200-300 meters. As shown in the image, I began tracking on two devices, and the tracking starts from the red cross area.
<img width="1132" alt="Screenshot 2024-08-09 at 2 57 41 PM" src="https://github.com/user-attachments/assets/f1a36951-7514-4edb-a9f8-e924335873d6">

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> it should start from my home or maybe 20-30 meters into the journey, but instead, it only starts after 200-300 meters

iOS requires movement of *at least* **200 meters** before tracking engages, as documented.  See API docs [`Config.stationaryRadius`](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#stationaryradius)

>⚠️ Note: iOS will not detect the exact moment the device moves out of the stationary-radius. In normal conditions, it will typically take ~200 meters of movement before the plugin begins tracking.

>Configuring stationaryRadius: 0 has NO EFFECT. In fact the plugin enforces a minimum stationaryRadius of 25 and in-practice, the native API won't respond for at least 200 meters.


We're fortunate that iOS even allows this.

**Comment by christocracy** [comment]
You are, of course, free to *manually* toggle the plugin into the *moving* state via `.changePace(true)` while your app is in the foreground, like a "Jogging App" would do with a [`Start Workout`] button.
