### ISSUE TITLE
Background geolocation is used all the time

### ISSUE THREAD

**Issue by suyundukov** [transistorsoft/capacitor-background-geolocation#273]
## Your Environment
* Plugin version: 4.16.5
* Platform: iOS
* Device OS version: 17.5.1
* Device manufacturer / model:  Apple iPhone 14 Pro
* XCode version: 15.4
* Capacitor info (`npx cap doctor`):
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2
* Plugin config provided to `#ready`:
```javascript
{
  backgroundPermissionRationale: { title, message, positiveAction, negativeAction },
  disableLocationAuthorizationAlert: true,
  startOnBoot: true,
  stopOnTerminate: false,
}
```

## Expected Behaviour
App uses background location only when needed.

## Actual Behaviour
App uses background location all the time.

## Steps to Reproduce

1. https://github.com/suyundukov/capacitor-background-geolocation-issue-reproduction
2. Install app
3. Add some point
4. In 3-4 days I'm receiving this notification:
<img src="https://github.com/user-attachments/assets/2f5c6140-a6b9-47b2-b30a-e5257f0d0982" width=200>

## Context
I'm working with geofences and I want to show a notification whenever user is in geofence point. This is how I use it:

```js
BackgroundGeolocation.onGeofence((_, taskId) => {
  LocalNotifications.schedule(...);
  BackgroundGeolocation.finish(taskId);
});

await BackgroundGeolocation.ready({
  backgroundPermissionRationale: { title, message, positiveAction, negativeAction },
  disableLocationAuthorizationAlert: true,
  startOnBoot: true,
  stopOnTerminate: false,
});

BackgroundGeolocation.startGeofences();
```

It works most of the time, but my biggest problem is that app is using background location all the time. I thought it will use it only when user is near geofence point.

**Comment by christocracy** [comment]
>  I thought it will use it only when user is near geofence point.

Your assumption was incorrect.  Geofences are managed purely by the OS.  How do you think the OS knows when the device is near a geofence:  by periodically sampling the location.

the user will get that dialog once for the life of the app install.  There’s no way to avoid it.

**Comment by suyundukov** [comment]
I thought that geofences are managed by the OS after being set up by the app. The app defines the geofence's parameters and actions, while the OS handles the location monitoring and triggers the app when the geofence is crossed, even if the app isn't running. But by the way it looks, app is constantly monitoring location in background or am I wrong on this one?

**Comment by christocracy** [comment]
> But by the way it looks, app is constantly monitoring location in background or am I wrong on this one?

You are wrong.  Your app is constantly monitoring location only if a solid location arrow is shown in the OS status bar.

see your device Settings *Privacy and Security* for more info:

![IMG_2057](https://github.com/user-attachments/assets/46d9612e-387e-4dfd-8b22-01f365371756)

**Comment by suyundukov** [comment]
If I’ve only set up a single geofence point, why is it showing that the app has accessed my location at multiple places?

**Comment by christocracy** [comment]
How do you think the OS knows where you’re at so it can evaluate a geofence to ask “am I in this geofence?”

**Comment by suyundukov** [comment]
Isn't it the OS, rather than the app itself, that utilises location services in that case?

**Comment by christocracy** [comment]
What does your privacy settings show for your app?

**Comment by suyundukov** [comment]
> What does your privacy settings show for your app?

Allow Location Access: "Always".

> Isn't it the OS, rather than the app itself, that utilises location services in that case?

According to Apple’s documentation, ["the system monitors regions and wakes up your app as needed when conditions change between satisfied and unsatisfied states"](https://developer.apple.com/documentation/corelocation/monitoring-the-user-s-proximity-to-geographic-regions). Given this, why does it indicate that my app is using geolocation even when user is in a different country from the original geofence location?

**Comment by suyundukov** [comment]
After further investigation, I realized that the issue was actually on my side, and not related to the project. I apologize for the oversight and any confusion this may have caused. I'll be closing this issue now. Thank you for your understanding.
