### ISSUE TITLE
I want to use a plugin in my Ionic Angular application when the user closes the app from the background.

### ISSUE THREAD

**Issue by Gjagadish123** [transistorsoft/capacitor-background-geolocation#277]
Could you share full details of the application key? I am a little confused because this program will require several users.

**Comment by christocracy** [comment]
Purchased keys allow infinite users,  the key is bound to your applicationId.

**Comment by christocracy** [comment]
> In pricing plans, I can't see any limitless users. 

It goes without saying.  It’s impossible for this plug-in to do device-based pricing since the plug-in doesn’t validate keys remotely.  This plug-in has no idea how many users you have.

>Also, if I purchase this plugin, can I use all of its features?

- The new Polygon geofencing feature requires a separate purchase.

**Comment by christocracy** [comment]
What’s difficult?  Have you tried?

**Comment by christocracy** [comment]
> Is there a trial period API key so that I can ensure everything is operating as per my requirements?

No.  Trial keys are impossible (since the plug-in doesn’t validate keys remotely.  

That’s why the plug-in is fully functional in debug builds so you can try before you buy (as noted at the top of the GitHub readme)
