### ISSUE TITLE
Foreground location is not working app crashes on android 14

### ISSUE THREAD

**Issue by adeel399** [transistorsoft/capacitor-background-geolocation#280]
## Your Environment
* Plugin version:4.0.1
* Platform: Android
* Device OS version: Android 14
* Device manufacturer / model: Samsung A23
* XCode version:
* Capacitor info:
 Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.1.2
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] Android looking great! 👌
* Plugin config provided to `#ready`:
i dont get what its mean but below is the fuction when on click crash app
```
  async start(): Promise<void> {
    await BackgroundGeolocation.destroyLocations();
    await this.setAndroidBackButtonBehavior();
    await BackgroundGeolocation.start();

    if (!this.totalTimer) {
      this.totalTimer = new Timer();
      this.startTimer(this.totalTimer);
    } else {
      this.startTimer(this.totalTimer);
    }

    if (!this.segmentTimer) {
      this.segmentTimer = new Timer();
      this.startTimer(this.segmentTimer);
    } else {
      this.startTimer(this.segmentTimer);
    }

    this.watchLocation();
  }
```
```javascript <!-- syntax-highlighting:  paste your code below -->
// AndroidManifest.xml

<manifest package="be.bbconsulting.unrestricted" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">
        
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="your_license_key" />
        
        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:label="@string/title_activity_main"
            android:launchMode="singleTask"
            android:name="be.bbconsulting.unrestricted.MainActivity"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <provider
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            android:name="androidx.core.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
        
        <service
            android:name=".LocationForegroundService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="location" />
    </application>
    
    <!-- Required permissions -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"
    tools:ignore="ScopedStorage" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove" />
</manifest>


```

```javascript <!-- syntax-highlighting:  paste your code below -->
// MainActivity.java
package be.bbconsulting.unrestricted;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class);


     Intent serviceIntent = new Intent(this, LocationForegroundService.class);
     startForegroundService(serviceIntent); 
  }
}

```
```javascript <!-- syntax-highlighting:  paste your code below -->
//LocationForegroundServices.java

package be.bbconsulting.unrestricted;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.Service;
import android.content.Intent;
import android.os.Build;
import android.os.IBinder;
import androidx.core.app.NotificationCompat;
import android.content.pm.ServiceInfo;
import android.os.Build;
import android.os.Build.VERSION_CODES;
public class LocationForegroundService extends Service {

    private static final String CHANNEL_ID = "LocationServiceChannel";
    private static final int NOTIFICATION_ID = 1;

    @Override
    public void onCreate() {
        super.onCreate();
        createNotificationChannel();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Notification notification = createNotification();

        // Check if the Android version is less than Android 14 (Tiramisu)
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            // For Android versions below 14, use startForeground without service type
            startForeground(NOTIFICATION_ID, notification);
        } else {
            // For Android 14 (API level 34) and above, specify the service type (e.g., LOCATION)
            startForeground(NOTIFICATION_ID, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_LOCATION);
        }

        // Return START_STICKY to keep the service alive
        return START_STICKY;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        // Handle service destruction logic
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel serviceChannel = new NotificationChannel(
                CHANNEL_ID,
                "Location Service Channel",
                NotificationManager.IMPORTANCE_DEFAULT
            );
            NotificationManager manager = getSystemService(NotificationManager.class);
            if (manager != null) {
                manager.createNotificationChannel(serviceChannel);
            }
        }
    }

    private Notification createNotification() {
        // Create a notification for the foreground service
        return new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("Location Service")
                .setContentText("Tracking your location")
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .build();
    }
}

```
## Expected Behavior

When i try to start recording it should work in the foreground and update my location 
## Actual Behavior

App crash as i start to run run background location function everything is working fine on android 13 before target api 34 after updating to 34 now app is crash as i clicked 

i tried to add all permissions and well as new update for forground service type location but nothing works app still crashing
## Steps to Reproduce

just update target api to 34 in variable file and you will see that crash 

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->

Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{a1bfbdf 10435:be.bbconsulting.unrestricted/u0a295} targetSDK=34

```

</details>

**Comment by adeel399** [comment]
i have added new issue and follow the template please help me as i already wasted 2 days on that issue please

**Comment by christocracy** [comment]
> Plugin version:4.0.1

You’re using a very old version.  See the CHANGELOG and update to latest version.

**Comment by christocracy** [comment]
> already wasted 2 days on that issue please

Because you’re using an old version from before targetSdkVersion 34 (I presume Google Play Store sent you a warning to update to targetSdkVerion 34).  You’re not going to get away with sitting on an old version of this plug-in.  You **must** update to the latest version.

**Comment by adeel399** [comment]
in my package.json
i have
    "cordova-background-geolocation-lt": "^4.0.1",
    "cordova-plugin-background-fetch": "^7.0.1",
    
  after updating to latest
  npm install @transistorsoft/capacitor-background-geolocation --save
npm install @transistorsoft/capacitor-background-fetch --save

i have added these but older is also there in package.json file should i remove cordova doing that does effect my code 

   @transistorsoft/capacitor-background-fetch": "^6.0.1",
    "@transistorsoft/capacitor-background-geolocation": "^6.1.0",
    
    "cordova-background-geolocation-lt": "^4.0.1",
    "cordova-plugin-background-fetch": "^7.0.1",

**Comment by adeel399** [comment]
also while updating to latest 
do i still need to add 
 <service
            android:name=".LocationForegroundService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="location" />
            
        in androidmenifest on that is handled automatically

**Comment by christocracy** [comment]
Remove every plug-in containing the words “background-geolocation” in its name.

Re-install the plugin according to the Installation Steps linked in the readme here.

pretend you’re installing the plugin for the first time ever.

**Comment by christocracy** [comment]
And uninstall every plugin containing the words “background-fetch” as well.

**Comment by adeel399** [comment]
after removing plugin and adding new as u mention this is what i get while building
'''
 Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/D:/unrestricted-app/android/capacitor-cordova-android-plugins/src/main/libs/
       - file:/D:/unrestricted-app/android/app/libs/
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/D:/unrestricted-app/android/capacitor-cordova-android-plugins/src/main/libs/
       - file:/D:/unrestricted-app/android/app/libs/
       '''

**Comment by christocracy** [comment]
Like I said, pretend you're installing the plugin for the first time ever.  Starting with the [Setup Instructions](https://github.com/transistorsoft/capacitor-background-geolocation?tab=readme-ov-file#large_blue_diamond-setup-guides)

Just follow the instructions.

**Comment by adeel399** [comment]
thanks alot it worked
