### ISSUE TITLE
App crashes with an Exception (Stacktrace available)

### ISSUE THREAD

**Issue by colenso** [transistorsoft/capacitor-background-geolocation#281]
## Your Environment
* Plugin version: 6.0.3
* Platform: Android
* Device OS version: Android 8.0
* Device manufacturer / model: LG Nexus 5X
* XCode version: NA
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0
  @capacitor/core: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
      stopOnTerminate: this.shouldApplyScheduleBasedLocationTracking ? false : this.stopOnTerminate,
      foregroundService: true,
      url,
      headers,
      xhrFields,
      httpRootProperty: '.',
      locationTemplate,
      distanceFilter: 30,
      elasticityMultiplier: 1.5,
      heartbeatInterval: 60,
      showsBackgroundLocationIndicator: true,
      stopTimeout: MAX_STOP_DURATION_IN_MINS,
      disableLocationAuthorizationAlert: true,
      logLevel: this.isVerboseLoggingEnabled ? BackgroundGeolocation.LOG_LEVEL_VERBOSE : BackgroundGeolocation.LOG_LEVEL_OFF,
      notification: {
        title: 'Background Tracking Enabled',
        text: 'Your location is being sent to Us.'
      },
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow Us to access to this device's location in the background?",
        message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission\n",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
      }
    }
```

## Expected Behavior

App shouldn't crash.

## Actual Behavior

App crashes within 15 seconds of starting up.

## Steps to Reproduce

1. Start our app that makes use of this plugin.
2. App crashes within 15 seconds of start-up.
3.
4.

## Context

I have code like: 
```
let isIgnoring = await BackgroundGeolocation.deviceSettings.isIgnoringBatteryOptimizations();
```
called when the app goes between foreground and background and also upon app initialization. Based on the Stacktrace, it seems related to this, maybe?

Stacktrace as reported by firebase:
```
          Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.x_b_e.client-LDiKGbT9p013Ga8irj1p_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.x_b_e.client-LDiKGbT9p013Ga8irj1p_w==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libtslocationmanager.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.transistorsoft.locationmanager.settings.Settings.<clinit>(:2)
       at com.transistorsoft.locationmanager.settings.Settings.load()
       at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(:65)
       at com.transistorsoft.locationmanager.adapter.TSConfig.a(:9)
       at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(:14)
       at com.transistorsoft.locationmanager.BootReceiver.b(:4)
       at com.transistorsoft.locationmanager.BootReceiver.$r8$lambda$EIqrzxxk16lv3slx2rrjsr-_P30()
       at com.transistorsoft.locationmanager.BootReceiver$$ExternalSyntheticLambda0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Post the following files:
- android/build.gradle
- android/app/build.gradle

**Comment by colenso** [comment]
- android/build.gradle: 
[build.gradle.zip](https://github.com/user-attachments/files/17239174/build.gradle.zip)

- android/app/build.gradle:
[build.gradle.zip](https://github.com/user-attachments/files/17239178/build.gradle.zip)

**Comment by christocracy** [comment]
Also, have you purchased a license?

**Comment by colenso** [comment]
> 1.  `android/build.gradle`
> 
> - Delete all references to the [deprecated `jcenter()`](https://developer.android.com/build/jcenter-migration) maven repo.
> 
> ```gradle
> 
> buildscript {
> 
> 
> 
>     repositories {
> 
>         google()
> 
>         jcenter() // <---------------------------- DELETE THIS
> 
>         mavenCentral()
> 
>     }
> 
>     dependencies {
> 
>         classpath 'com.android.tools.build:gradle:8.2.2'
> 
>         classpath 'com.google.gms:google-services:4.4.0'
> 
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
> 
> 
> 
>         // NOTE: Do not place your application dependencies here; they belong
> 
>         // in the individual module build.gradle files
> 
>     }
> 
> }
> 
> 
> 
> apply from: "variables.gradle"
> 
> 
> 
> allprojects {
> 
>     repositories {
> 
>         google()
> 
>         jcenter() // <---------------------------- DELETE THIS
> 
>         // capacitor-background-geolocation
> 
>         maven {
> 
>           url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs")
> 
>         mavenCentral()
> 
>         }
> 
>         // capacitor-background-fetch
> 
>         maven {
> 
>           url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs")
> 
>         }
> 
>     }
> 
> }
> 
> 
> 
> task clean(type: Delete) {
> 
>     delete rootProject.buildDir
> 
> }
> 
> ```
> 
> 
> 
> 2.  `android/app/build.gradle`
> 
> - You failed to implement *ALL* the [Required Setup Instructions](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md#android-setup-instructions-required).  **Everything** labeled in `+green` must be implemented
> 
> 
> 
> 
> 
> 

Okay.  I will follow it and check.

**Comment by colenso** [comment]
> Also, have you purchased a license?

Yes we have.

**Comment by christocracy** [comment]
>Device OS version: Android 8.0
>Device manufacturer / model: LG Nexus 5X

Is this an emulator?

**Comment by colenso** [comment]
> > Device OS version: Android 8.0
> > Device manufacturer / model: LG Nexus 5X
> 
> Is this an emulator?

No. It's on a real device.

**Comment by colenso** [comment]
I've implemented all the required setup instructions and I'm closing this issue for now. Will re-open if I see the same error on a build that has this implemented.
