### ISSUE TITLE
[Question] Do I Need Separate Start, Stop, and Default States for Tracking Configs?

### ISSUE THREAD

**Issue by chrisbiscuit** [transistorsoft/capacitor-background-geolocation#282]
Hi,

I’m developing a walking app using `react-background-geolocation` and currently have three separate configurations that I apply depending on the user's activity state:

1. **GEO_CONFIG**: Applied when `.ready` is called, and it initialises the geolocation settings when the user opens the app.
2. **GEO_CONFIG_START**: Applied dynamically when the user starts walking (increased tracking frequency and persistence settings).
3. **GEO_CONFIG_STOP**: Applied when the user stops the walk (tracking is disabled to save battery and prevent unnecessary processing).

**What I'm Trying to Achieve:**
- When the user is actively walking, I want to ensure the app tracks location accurately and reliably, even in the background.
- When the walk ends, I want to stop tracking to conserve resources and avoid unnecessary background activity.
- I’m also worried about the app being killed by the OS while the user is not walking, which is why I disable certain features in `GEO_CONFIG_STOP`.

### My Questions:
1. **Do I need three separate states** (default, start, stop) for my use case, or can I just handle everything with one config that I tweak dynamically?
2. Am I over-optimising by completely disabling tracking in the `STOP` state to prevent the app from being killed by the OS? Is that step even necessary, or would keeping tracking on (in a lower accuracy mode) suffice to maintain app reliability?
3. Would maintaining just one state with some dynamic modifications be a better approach, or is there an optimal balance between these distinct configs?

### What I Have Considered:
Using three distinct states:
```javascript
export const GEO_CONFIG = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  locationAuthorizationRequest: 'WhenInUse',
  showsBackgroundLocationIndicator: true,
  notification: {
    title: 'Tracking walk',
    text: 'Tracking your walk...',
  },
  foregroundService: true,
  activityType: BackgroundGeolocation.ACTIVITY_TYPE_FITNESS,
};

export const GEO_CONFIG_START = {
  stopOnTerminate: false,
  startOnBoot: true,
  heartbeatInterval: 60,
  preventSuspend: true,
};

export const GEO_CONFIG_STOP = {
  stopOnTerminate: true,
  heartbeatInterval: undefined,
  preventSuspend: false,
};
```

Is this overcomplicating things, or should I merge these into a single state and simply toggle key parameters dynamically depending on activity?

Thanks in advance for your advice!

**Comment by christocracy** [comment]
>Do I need three separate states (default, start, stop) for my use case

No.

>Am I over-optimising by completely disabling tracking in the STOP state 

Yes.  When the user clicks some sort of button signalling the end of their "walk", you call `.stop()`.  When the user clicks some sort of UI button signalling the *start* of their "walk", you call `.start()`, followed by `.changePace(true)`.

```javascript
// Start walk
await BackgroundGeolocation.start();
await BackgroundGeolocation.changePace(true); // <-- toggle immediately to "moving" state.
.
.
.
// Stop Walk
BackgroundGeolocation.stop()
```

>Would maintaining just one state with some dynamic modifications be a better approach

Yes.

Some notes about your config:

> foregroundService: true,

I don't know where people get the idea to use this option.  It's been deprecated from the plugin for over 5 years and it does absolutely nothing.  The plugin completely ignores this option.  Delete it.

> preventSuspend: false,

This iOS-only option only works with `Always` location authorization.  You're using `WhenInUse`.  Delete it and forget about it.  Also, it only applies when the device is in the stationary state, which your walking app is not interested in.

See API docs Config.stopTimeout and provide a sufficiently high value for your use case to prevent the plugin unnecessarily entering the stationary state for brief pauses in activity (eg: 20 min).

**Comment by chrisbiscuit** [comment]
Thanks for your detailed and prompt response. I appreciate the clarification regarding the states and config options. I’ll simplify things based on your advice and remove the unnecessary configurations like `foregroundService` and `preventSuspend`. 

I’ll try out the changes and will update you if any issues arise. Thanks again for the guidance.

**Comment by chrisbiscuit** [comment]
> I don't know where people get the idea to use this option. It's been deprecated from the plugin for over 5 years and it does absolutely nothing. The plugin completely ignores this option. Delete it.

It looks like the documentation still mentions `preventSuspend` as an option, which could be misleading for users. It might be helpful to update or remove that section to avoid any further confusion.

See: [Documentation Link](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#preventsuspend)
