### ISSUE TITLE
Odometer reading shows anomalies

### ISSUE THREAD

**Issue by mgravindran** [transistorsoft/capacitor-background-geolocation#284]
## Your Environment
* Plugin version: 6.0.3
* Platform: Both iOS and Android
* Device OS version: iOS 16, Android 12/13/14
* Device manufacturer / model: Apple, Redmi, Samsung
* XCode version: 15.3
* Capacitor info (`npx cap doctor`)   @capacitor/cli: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
const config: Config = {
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            backgroundPermissionRationale: {
                title: "Allow *** to access to this device's location in the background?",
                message: "*** uses background location services to capture your live location to log your field journey. In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
                positiveAction: "Change to {backgroundPermissionOptionLabel}",
                negativeAction: "Cancel"
            },
            locationAuthorizationAlert: {
                titleWhenNotEnabled: "Location services are not enabled",
                titleWhenOff: "Location services are off",
                instructions: "*** requires background location tracking to be turned on. You must enable 'Always' in location-services",
                cancelButton: "Cancel",
                settingsButton: "Settings"
            },
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            debug: !environment.production,// <-- enable debug sounds/notifications
            url: API_URL
            autoSync: true,
            autoSyncThreshold: 2,
            batchSync: true,
            maxBatchSize: 10,
            httpRootProperty: 'location',
            params: payloadParams,
            locationsOrderDirection: "ASC",
            maxDaysToPersist: 1,
            stopOnTerminate: this.platform === 'ios' ? true : false,
            notification: {
                text: "Location services are running in the background",
                priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_DEFAULT,
            }
        }
        return new Promise((resolve, reject) => {
            BackgroundGeolocation.setConfig(config).then((state) => {
                resolve(true);
            }).catch(error => {
                resolve(false);
            });
        });
```

## Expected Behavior
For every location change (in non-still mode), the odometer reading should increase as per the distance between the previous and new location coordinates

## Actual Behavior
On analysing the location tracking data from real users, we see an anomaly in the odometer reading. For every location change, the reading increases corresponding to the distance. But suddenly there is a spike in the odometer reading (~ 22Lakh meters). This happens for the next 5 to 10 readings and then again the reading reflects correctly. 
Attaching some data samples here.

Also attached a full spreadsheet marking the anomalies in red
https://docs.google.com/spreadsheets/d/1sx-ASEpxWhLfznD79nhxLoYnY1n75RAh1g-UBz-Nae0/edit?gid=0#gid=0
[Uploading Location Odometer Anomalies.xlsx…]()

<google-sheets-html-origin><style type="text/css"></style>
_id | session_id | location.event | location.is_moving | location.uuid | location.age | location.timestamp | location.odometer | diff |   | location.coords.latitude | location.coords.longitude | location.coords.accuracy | location.coords.speed | location.coords.speed_accuracy | location.coords.heading | location.coords.heading_accuracy | location.coords.altitude | location.coords.ellipsoidal_altitude | location.coords.altitude_accuracy | location.coords.age | location.activity.type | location.activity.confidence | location.battery.is_charging | location.battery.level | location.provider.network | location.provider.gps | location.provider.enabled | location.provider.status | location.provider.accuracyAuthorization | location.provider.airplane |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
66e12acf2a70e4c311393240 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 9b601c97-3bac-44d8-8191-a61954e41148 | 307 | 2024-09-11T05:28:56.369Z | 211950.9 | #VALUE! | #VALUE! | 17.5442711 | 78.4915323 | 31.36 | -1 | 1.5 | -1 | 45 | 535.5 | 535.5 | 1.66 | 311 | in_vehicle | 100 | FALSE | 0.91 |   |   |   |   |   |   |  
66e12acf2a70e4c311393241 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | f65d0f39-3b3c-4b1e-9151-cb398a627421 | 131 | 2024-09-11T05:29:50.223Z | 212018.7 | 67.8 | yes | 17.5443868 | 78.4909056 | 15.69 | 2.29 | 1.5 | 281.03 | 45 | 536.6 | 536.6 | 1 | 133 | in_vehicle | 100 | FALSE | 0.91 |   |   |   |   |   |   |  
66e12ad91f508bb458f48655 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 98add9c5-0030-4033-b095-677e3aa8a0bb | 3057 | 2024-09-11T05:29:52.298Z | 212038.8 | 20.1 | yes | 17.5444351 | 78.4907223 | 14.92 | 9.12 | 1.5 | 285.38 | 45 | 536.7 | 536.7 | 1 | 3061 | in_vehicle | 100 | FALSE | 0.91 |   |   |   |   |   |   |  
66e12ad91f508bb458f48656 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | d3bd2d69-2c03-44df-9af8-0c18b4a2d640 | 222 | 2024-09-11T05:30:00.390Z | 212075.6 | 36.8 | yes | 17.5445578 | 78.4904002 | 19.88 | 4.82 | 1.5 | 291.03 | 45 | 537.1 | 537.1 | 1 | 225 | in_vehicle | 100 | FALSE | 0.91 |   |   |   |   |   |   |  
66e12ae5d8ec4a36d046b20f | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 81ed227c-b193-4dfa-b204-1ecd7c99f521 | 128 | 2024-09-11T05:30:10.573Z | 212098.1 | 22.5 | yes | 17.5445349 | 78.4901903 | 6.98 | 3.31 | 2.7 | 286.26 | 38.4 | 537.3 | 537.3 | 1.28 | 131 | in_vehicle | 100 | FALSE | 0.91 |   |   |   |   |   |   |  
66e12ae5d8ec4a36d046b210 | 0AACA53605DBE74C0C9442A0E1416 | providerchange | TRUE | 25d1417b-9759-4f36-a7a6-07acc78e10bf | 11 | 2024-09-11T05:30:12.451Z | 212098.1 | 0 | no | 17.5445349 | 78.4901903 | 6.98 | 3.31 | 2.7 | 286.26 | 38.4 | 537.3 | 537.3 | 1.28 | 14 | in_vehicle | 100 | FALSE | 0.91 | FALSE | FALSE | FALSE | 3 | 0 | FALSE |  
66e15b462a70e4c3113992ec | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 4b476ddc-9450-4bf6-b0d7-0e923ac2c8ff | 1658 | 2024-09-11T08:56:34.002Z | 212098.1 | 0 | no | 17.5462403 | 78.4876512 | 45.6 | -1 | 1.5 | -1 | 45 | 531.4 | 531.4 | 4.05 | 1667 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e15b4b15c62484ce418d26 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | e529cad0-049c-4290-9a34-8c19a0b4610c | 2146 | 2024-09-11T08:56:40.354Z | 2467666 | 2255567.9 | yes | 17.5462743 | 78.4876922 | 22.07 | -1 | 1.5 | -1 | 45 | 531.4 | 531.4 | 100 | 2165 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e15b57c6ca2881e01dc0fb | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | ec1bfdf0-4337-45f2-9be7-bb56e7094d05 | 335 | 2024-09-11T08:56:51.762Z | 4723226 | 2255560 | yes | 17.5462886 | 78.4877065 | 29.5 | 0.23 | 1.5 | 29.66 | 45 | 531.4 | 531.4 | 100 | 340 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e15b5d2a70e4c311399367 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | b9cb5bc4-6792-4135-9925-c1bdf0eeec3a | 125 | 2024-09-11T08:56:58.858Z | 6978790 | 2255564 | yes | 17.546246 | 78.4876539 | 21.42 | 0.99 | 1.5 | 229.78 | 45 | 531.4 | 531.4 | 53.28 | 129 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e15b602a70e4c311399379 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | c35a88fb-10ca-4ee7-bd8c-650be52f3d24 | 303 | 2024-09-11T08:57:02.010Z | 9234359 | 2255569 | yes | 17.5462429 | 78.4876827 | 22.94 | 0.82 | 1.5 | 101.11 | 45 | 531.4 | 531.4 | 92.72 | 312 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e15b67d8ec4a36d04712fa | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | f1314f43-1e02-4f94-a926-258ffe629938 | 1861 | 2024-09-11T08:57:07.146Z | 11489926 | 2255567 | yes | 17.5462495 | 78.4876819 | 24.26 | 0.13 | 1.5 | 37.39 | 45 | 531.4 | 531.4 | 76.31 | 1867 | still | 100 | FALSE | 0.79 |   |   |   |   |   |   |  
66e1713b1f508bb458f50a51 | 0AACA53605DBE74C0C9442A0E1416 | motionchange | TRUE | 39ff2e26-a37a-470f-806b-ba4986ded327 | 1052 | 2024-09-11T10:30:17.245Z | 12617709 | 1127783 | yes | 17.5423887 | 78.4884964 | 17.23 | 0.07 | 0.11 | -1 | -1 | 533.8 | 533.8 | 2.23 | 1063 | on_bicycle | 100 | FALSE | 0.63 |   |   |   |   |   |   |  
66e171421f508bb458f50a58 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 261b6cd3-bc7b-4291-8ebb-362ea8536e77 | 142 | 2024-09-11T10:30:19.939Z | 12617709 | 0 | no | 17.5423823 | 78.4884941 | 27.86 | 0.07 | 1.5 | -1 | -1 | 533.8 | 533.8 | 5.33 | 147 | on_bicycle | 100 | FALSE | 0.63 |   |   |   |   |   |   |  
66e171421f508bb458f50a59 | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 74b4255e-0bc3-477e-8a59-062e8a59ad2f | 134 | 2024-09-11T10:30:25.518Z | 12617709 | 0 | no | 17.5423886 | 78.4885967 | 44.28 | 1.78 | 1.5 | 86.44 | 45 | 533.8 | 533.8 | 7.93 | 141 | on_bicycle | 100 | FALSE | 0.63 |   |   |   |   |   |   |  
66e17153d8ec4a36d04736bc | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | 24af3728-a4d0-4be1-aabc-ee5f95033b2b | 166 | 2024-09-11T10:30:30.407Z | 12617750 | 41 | yes | 17.5420213 | 78.4884589 | 42.97 | 7.43 | 1.5 | 197.79 | 45 | 534.3 | 534.3 | 100 | 169 | on_bicycle | 100 | FALSE | 0.63 |   |   |   |   |   |   |  
66e17153d8ec4a36d04736bd | 0AACA53605DBE74C0C9442A0E1416 |   | TRUE | e20f55f4-ed58-447a-81ea-a95ac867b770 | 164 | 2024-09-11T10:30:42.390Z | 12617750 | 0 | no | 17.5419978 | 78.488223 | 48.9 | 4.35 | 1.5 | 228.8 | 45 | 534.3 | 534.3 | 7.12 | 169 | on_bicycle | 100 | FALSE | 0.63 |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

## Steps to Reproduce

1. Start BackgroundGeolocation.start() with location permission as Always.
2. Simulate movement/do a real travel
3. Monitor the location data posted by the plugin to the API URL. Or export the local DB data stored by the plugin
4. Verify the odometer reading for every location change event

## Context

Live tracking of location for users

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I think I'm ready to give up on odometer and remove it from the plugin.  It's too difficult to manage.

**Comment by christocracy** [comment]
I suggest you manage distance-travelled on your own.

**Comment by mgravindran** [comment]
Thanks @christocracy for the prompt response. We will implement the calculation of distance on our end.
