### ISSUE TITLE
The React example isn't correct in this repo

### ISSUE THREAD

**Issue by msacc-mas** [transistorsoft/capacitor-background-geolocation#286]
In the Readme/main github repo for this plugin, this doesn't make sense. You want to start the plugin if its not already enabled. Your main documentation has it correct.

```` /// 3. start / stop BackgroundGeolocation
  React.useEffect(() => {
    if (!ready) { return }

    if (enabled) {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.stop();
      setEvents([]);
    }
  }, [enabled]);
````

From main docs: https://transistorsoft.github.io/capacitor-background-geolocation/classes/backgroundgeolocation.html#getstate
````
if (!state.enabled) {
    ////
    // 3. Start tracking!
    //
    BackgroundGeolocation.start(function() {
      console.log("- Start success");
    });
  }
  ````

**Comment by christocracy** [comment]
It’s a mistake.  Follow the logical way.

**Comment by christocracy** [comment]
Actually, no:  it’s correct.  This is a `<Switch/>` listener.  If you toggle the switch to enabled `true`, then logically you will tell the plug-in to `.start()`.

**Comment by christocracy** [comment]
You’re confusing the `State.enabled` returned by `.ready` with the value of a`<Switch />` change listener.

**Comment by christocracy** [comment]
The `<Switch />` referenced is this one:

![IMG_2361](https://github.com/user-attachments/assets/302b0eeb-20fa-4b15-a7b8-56024a8e88ac)

**Comment by msacc-mas** [comment]
> You’re confusing the `State.enabled` returned by `.ready` with the value of a`<Switch />` change listener.

Indeed, sir, i was!
