### ISSUE TITLE
Google Play Store Rejection Issues with ACTIVITY_RECOGNITION Permission

### ISSUE THREAD

**Issue by chrisbiscuit** [transistorsoft/capacitor-background-geolocation#289]
Hi there,

We’ve been encountering multiple rejections on our Android app submission to the Google Play Store after updating to SDK 14, specifically for the `ACTIVITY_RECOGNITION` permission. Following the guidance on your [blog post](https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a), we selected the "Other" category, providing the following explanation:
> "The app uses the ActivityTransition API to automatically toggle location services ON when the device is detected to be in-motion. When the motion API reports the device is 'still,' the app turns OFF location services to conserve battery. This is a documented use-case for the Activity Transition API, as per the official [Android Developer documentation](https://developer.android.com/develop/sensors-and-location/location/transitions)."

However, our submission still got rejected with this response:
> "During our review, we have identified functionalities that relate to the following categories:
> Others (Please Specify) What other health features does your app offer?
> Please review and update your selections to ensure accuracy. This includes removing any irrelevant or excessive categories and adding any necessary ones."

We've tried revising our response multiple times but haven’t had success. Could you advise if there’s anything else we might try to ensure our app meets with Google’s requirements? Additionally, do you offer any consultation services? We would be open to compensating you for your time if so.

Thanks in advance for any help you can provide!

**Comment by christocracy** [comment]
What is the nature of your app, its purpose?  What are your users using it for?

**Comment by chrisbiscuit** [comment]
Our app is designed for dog owners to support and monitor their pets’ activity levels and wellbeing. One of the main features is activity tracking, allowing users to record their dog’s walks, which they can view on a map. The app encourages daily exercise by helping users set and achieve pet care goals.

Here’s a link to the app on Google Play for further details: [App Link](https://play.google.com/store/apps/details?id=com.biscuit.biscuit&hl=en_GB).

**Comment by christocracy** [comment]
Maybe you should add that text to the description for the permission?

**Comment by chrisbiscuit** [comment]
### Update on resolving the Google Play rejection issue:
Thanks for your help. I’m posting this to leave a record of how we resolved the issue for anyone else facing the same frustrating situation with Google Play.

Just to recap, we’re building a dog wellbeing app that tracks users’ dog walking activities, which are displayed on a map. **Since the launch of our app**, we’ve always had the **"Activity & Fitness"** category ticked in our Health Declaration, as we thought it was necessary since the owner is also exercising while walking the dog We ticked the **"Activity & Fitness"** box and explained in the **"Other"** field that we don’t offer additional health features. We tried various ways of explaining what we do, but the **"Other"** field only allowed 250 characters, which made it difficult to provide enough detail.

Despite this, our app was repeatedly rejected with the reason:

```
We found an issue in the following area(s):
Full description (en-GB):
```
...and inquiries about other health features we were offering.

After multiple appeals, with one unanswered for 3 weeks, we eventually got a useful response from Google Play. They advised us to **remove the "Activity & Fitness" category** from the declaration entirely. We updated the **"Other"** field to read:

```
My app doesn’t provide any health features
```
...and that did the trick—our app was approved after making that change.

### Key takeaway:
When appealing, it’s better to select the option that says **"I don’t know what to do"** rather than contesting the rejection as incorrect. 

I’m attaching screenshots of the email from Google Play, along with our Health Declaration, in case it helps anyone else in the future.

**Google Play Rejection Email**
<img width="869" alt="image" src="https://github.com/user-attachments/assets/ac204037-83cf-4be7-951b-c7312406b47c">

**Google Play Support Email**
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/5535f5d5-495b-496c-a464-feea51b53e0a">

**Our Working Health Declaration**
<img width="971" alt="image" src="https://github.com/user-attachments/assets/f6d0d8c3-ed2d-48be-8f43-38cc7b8817c3">

<img width="946" alt="image" src="https://github.com/user-attachments/assets/92933b92-f759-4f59-8fb0-6453b9f85fba">

**Comment by christocracy** [comment]
Thank you *very* much for sharing this.  Well done!

**Comment by ademirtemur** [comment]
this works, add these lines.

`<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />`
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />`
