### ISSUE TITLE
Testing on IOS

### ISSUE THREAD

**Issue by itpetgram** [transistorsoft/capacitor-background-geolocation#29]
Before buying a license I wanted to test the integration on IOS, I belive to have configured everything besides the License Key. Your Readme states as follows:
```
The Android module requires purchasing a license. However, it will work for DEBUG builds. It will not work with RELEASE builds without purchasing a license.
```
It says nothing on the IOS license, so my question is: Does it work in debug mode on IOS?

**Comment by redyredy123** [comment]
And so basically it requires no license on IOS and is free for use on IOS?

**Comment by christocracy** [comment]
Yes
