### ISSUE TITLE
REQUEST_INSTALL_PACKAGES permissions error in google play store submission

### ISSUE THREAD

**Issue by msacchetti** [transistorsoft/capacitor-background-geolocation#291]
```
## Your Environment
* Plugin version: Latest
* Platform: iOS or Android :Android, android apk 34
All Deps are up to date as of now, following the setup instructions in this repo
```

Submitting the app, we get rejected from google for 

> "Your app uses android.permission.REQUEST_INSTALL_PACKAGES which has not been declared"

It is coming from huawei. 

Following your install setup guide, it says to add
```
hmsLocationVersion
maven { url 'https://developer.huawei.com/repo/' }
```

But then at the bottom it says this plugin is optional.  (we dont plan to support or care about this in our release)
https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md#huawei-mobile-services-hms-support

Do we just remove those two huawei lines from the setup guide? If we need those, how do we fix it?

<br class="Apple-interchange-newline">

<img width="965" alt="image" src="https://github.com/user-attachments/assets/f565095f-4db6-4e45-987e-0511f5c1b55b">

<img width="984" alt="image" src="https://github.com/user-attachments/assets/392656bd-701a-41ac-bf7a-1e166ff9e653">

**Comment by vmauna-mas** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral()
       maven {
         // capacitor-background-fetch
         url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs")
      }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
        classpath 'com.google.gms:google-services:4.4.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
       // capacitor-background-geolocation
      maven { url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs") }
      maven { url 'https://developer.huawei.com/repo/' }
      // capacitor-background-fetch
      maven { url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs") }
    
    
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Post variables.gradle

**Comment by vmauna-mas** [comment]
ext {
    minSdkVersion = 31
    compileSdkVersion = 34
    targetSdkVersion = 34
    hmsLocationVersion = '6.0.0.302'
    okHttpVersion = '4.9.1'
    localBroadcastManagerVersion = '1.0.0'
    playServicesLocationVersion = '21.0.1'
    androidxActivityVersion = '1.8.0'
    androidxAppCompatVersion = '1.6.1'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.12.0'
    androidxFragmentVersion = '1.6.2'
    coreSplashScreenVersion = '1.0.1'
    androidxWebkitVersion = '1.9.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.5'
    androidxEspressoCoreVersion = '3.5.1'
    cordovaAndroidVersion = '10.1.1'
}

**Comment by christocracy** [comment]
delete this and the plugin will use its [default value](https://github.com/transistorsoft/capacitor-background-geolocation/blob/7e0514fe22d94ea115845a81b1514e4ef0a35b6c/android/build.gradle#L36) `6.9.0.300`

```diff
-  hmsLocationVersion = '6.0.0.302'
```

or set it to `6.9.0.300`

**Comment by msacchetti** [comment]
> delete this and the plugin will use its [default value](https://github.com/transistorsoft/capacitor-background-geolocation/blob/7e0514fe22d94ea115845a81b1514e4ef0a35b6c/android/build.gradle#L36) `6.9.0.300`
> 
> ```diff
> -  hmsLocationVersion = '6.0.0.302'
> ```
> 
> or set it to `6.9.0.300`

I just found this issue from 2023 after we posted this - can you update the docs? might save some people a couple hours of fiddling in the future. Thank you for this awesome plugin!

**Comment by christocracy** [comment]
The [Setup Instructions](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidvariablesgradle) do not instruct you to add that variable.

**Comment by msacchetti** [comment]
> The [Setup Instructions](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidvariablesgradle) do not instruct you to add that variable.

A number of other ext variables are available but should generally not need to be modified.
<img width="998" alt="image" src="https://github.com/user-attachments/assets/ed1a3f6e-4792-404b-aee1-01064ce562a2">

"not modified" comes across as, "put these other ext variables in, but they dont need to be modified from what you show them as there" - but they do

**Comment by msacchetti** [comment]
Constructive feedback for other users:

> The ext(tra?) ext(ended?) variables below are not normally required in the basic plugin configuration. Ony add these ext variables if you have a use case for them, otherwise, skip this step. 


(and then update it to the correct one, 6.9.0.300)
