### ISSUE TITLE
iOS Background Location Tracking Stops When Using 'When in Use' Permission

### ISSUE THREAD

**Issue by tomek-em** [transistorsoft/capacitor-background-geolocation#292]
## Your Environment
* Plugin version: 
  capacitor background geolocation: 6.0.0
* Platform: iOS
* Device OS version: 16.5
* Device manufacturer / model: iPhne X, iPhone 15
* XCode version: 15.4
* Capacitor info (`npx cap doctor`): 
  @capacitor/cli: 6.1.2, @capacitor/core: 6.1.2, @capacitor/ios: 6.1.2 
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
await BackgroundGeolocation.ready({
      startOnBoot: false,
      locationAuthorizationRequest: 'WhenInUse'',
      notification: {
        smallIcon: 'drawable/ic_turo_noti_3',
        title: notificationTitle,
        text: notificationText,
        sticky: true
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      stopTimeout: 10,
      stopOnTerminate: false,
      stopOnStationary: false,
      debug: false,
      reset: true,
    });
```

## Expected Behavior
The app tracks and display the user's position path on the map continuously, even when running in the background, while only requesting the "When in Use" location permission

## Actual Behavior
When changing the location authorization request from "Always" to "When in Use" and updating the configuration accordingly, the app stops tracking the user's location immediately after closing the app on iOs. This results in only straight lines between the last recorded locations when the app is reopened, instead of a continuous path.

## Steps to Reproduce

1. Set locationAuthorizationRequest to When in Use in the app configuration.
2. Implement the geolocation plugin to track user positions and draw the path on the map.
3. Run the app and start tracking a route.
4. Minimize or close the app.
5. Reopen the app to observe the location tracking behavior.

## Context
I have an app that displays the user's position path on the map over time and calculates the distance traveled. I have set locationAuthorizationRequest to "Always," and the plugin works great.

However, the customer prefers not to prompt users for the "Always" location permission due to privacy concerns. They provided the Strava app as an example, which successfully tracks location in the background with only "When in Use" permission by running a foreground service with a persistent notification. However, replicating this behavior in my app does not yield the same results, especially on iOS, where tracking ceases once the app is closed.

Is there a way to prompt for location permission as "When in Use" and still maintain reliable background tracking of the user's position?

**Comment by christocracy** [comment]
Start by upgrading to the latest version:

https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/CHANGELOG.md

**Comment by christocracy** [comment]
With WhenInUse, the user must manually engage location-tracking while your app is in the foreground, like a “Jogging App” does with some sort of [Start Workout] button.

in that UI button, you will call .changePace(true).  See the wiki “Philosophy of Operation” for more information.

with WhenInUse, an app absolutely cannot automatically engage location tracking in the background when device motion is detected.  That’s made possible ONLY with Always authorization.

so, if your Customer wants to click a “Start Tracking” button, like Strava, go ahead.

**Comment by tomek-em** [comment]
This works. Thank you.

**Comment by tomek-em** [comment]
This works. Thank you.

**Comment by christocracy** [comment]
The plugin must be `enabled: true` before calling `.changePace(true)`.  Calling `.start()` sets `State.enabled == true`.

```javascript
onClickStartTracking() {
  await BackgroundGeolocation.start();
  await BackgroundGeolocation.changePace(true);
}

onClickStopTracking() {
  BackgroundGeolocation.stop() // You don't need to call .changePace(false)
}
```
