### ISSUE TITLE
Generic question

### ISSUE THREAD

**Issue by monkeydkon** [transistorsoft/capacitor-background-geolocation#3]
What is the difference between `capacitor-background-geolocation` and `cordova-backgrond-geolocation`?

I've been using the latter but with capacitor. If I change to `capacitor-background-geolocation` should I be expecting any difference at all?

**Comment by christocracy** [comment]
All versions of background-geolocation use the **exact same** native iOS and Android libraries (`TSLocationManager.xcframework` and `tslocationmanager.aar`, respectively).

Performance of the plugin is not only identical between Cordova and Capacitor, it's identical  with React Native and Flutter, as well.

However, when used with Capacitor, the `cordova-background-geolocation` plugin uses Capacitor's "Cordova Compatibility" interface.  This causes weird build errors as Capacitor releases new versions.  It was these support issues that finally motivated me to create a pure Capacitor adapter.

Also, the benefit of using the pure Capacitor version is that it gives one more control over the plugin's native iOS / Android config / dependency versions that are completely hidden from you when using the cordova version.  This makes it far more difficult to deal with build issues.

The setup and management of the plugin with Capacitor shares much in common with the Flutter and React Native versions (eg: [Android Setup](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md).  This is a much more preferable way to set up plugin than Cordova's automated "magic", which makes it very difficult to manage dependency versions, resolve gradle dependency conflicts.

If you're using Capacitor, it is far more preferable to use `capacitor-background-geolocation`.  It is certain Capacitor will continue to introduce changes that break your builds, wasting hours of time with the cordova version.
