### ISSUE TITLE
Headless Mode Android

### ISSUE THREAD

**Issue by simonneutert** [transistorsoft/capacitor-background-geolocation#31]
## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* Device OS version: 8.0.0
* Device manufacturer / model: Huawei Mate 10 Lite
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
   Capacitor Doctor   

Latest Dependencies:       

  @capacitor/cli: 3.2.5    
  @capacitor/core: 3.2.5   
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5    

Installed Dependencies:    

  @capacitor/core: 3.2.5   
  @capacitor/cli: 3.2.5    
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5    

[success] Android looking great! 👌
[error] Xcode is not installed
```

## Expected Behavior

The Code from the Wiki for enabling headless mode with capacitor should compile.

## Actual Behavior

From the given example code

```java
// Get reference to plugin singleton
BackgroundGeolocation bgGeo = BackgroundGeolocation.getInstance(event.getContext());

// Build config object:
JSONObject config = new JSONObject();
try {
  config.put("persist", false);
  config.put("samples", 1);
} catch (JSONException e) {
  // This really won't run
}

// Build a Callback
TSLocationCallback callback = new TSLocationCallback() {
    public void onLocation(TSLocation location) {
        Log.d("TSLocationManager", "- getCurrentPosition SUCCESS: " + location.toJson());
    }
    public void onError(Integer error) {
        Log.d("TSLocationManager", "- getCurrentPosition FAILURE" + error);
    }
};
// Run it
bgGeo.getCurrentPosition(config, callback);
```

## Steps to Reproduce

1. clean hello world ionic/cap3 project
2. install this plugin with background fetch
3. read and copy headless code

## Context

get the currentPosition and write it to the sqlite db or maybe even send it

I have checked the linked cordova class in the reference, but I have no clue on what I am missing, sorry

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
android\app\src\main\java\io\ionic\starter\BackgroundGeolocationHeadlessTask.java:95: error: method getCurrentPosition in class BackgroundGeolocation cannot be applied to given types;
            bgGeo.getCurrentPosition(config, callback);
                 ^
  required: TSCurrentPositionRequest
  found: JSONObject,TSLocationCallback
  reason: actual and formal argument lists differ in length
```

</details>

**Comment by christocracy** [comment]
You need to operate upon your HeadlessTask.java in AndroidStudio, within the Android app itself in order to get code-assist.  Don't attempt to operate upon your HeadlessTask *without* code-assist.

**Comment by simonneutert** [comment]
Thank you so much @christocracy
