### ISSUE TITLE
new BackgroundFetch.Callback() missing onTimeout() method

### ISSUE THREAD

**Issue by deviantmilk** [transistorsoft/capacitor-background-geolocation#35]
## Your Environment
* Plugin version: 
@transistorsoft/capacitor-background-fetch@0.0.6
@transistorsoft/capacitor-background-geolocation@4.4.0

* Platform: Android

* Device OS version:

* Device manufacturer / model: Samsung A21s

* Capacitor info (`npx cap doctor`)
*  Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.2.5
  @capacitor/cli: 3.2.5
  @capacitor/android: 3.2.5

[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

```

## Expected Behavior
When building the app in Android Studio the app should build without failing. I have followed all the setup steps in your setup guide.

## Actual Behavior
When building the app in Android Studio the build fails with the error here below.

## Steps to Reproduce
1. Run build / app in Android Studio

## Context
Building the app with adding the background geolocation for capacitor plugin from transistorsoft?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac D:\xxx\android\capacitor-cordova-android-plugins\src\main\java\com\transistorsoft\cordova\backgroundfetch\CDVBackgroundFetch.java:57: error: <anonymous com.transistorsoft.cordova.backgroundfetch.CDVBackgroundFetch$1> is not abstract and does not override abstract method onTimeout(String) in Callback
[capacitor]         adapter.configure(config.build(), new BackgroundFetch.Callback() {
[capacitor]         ^
[capacitor]         Note: Some input files use or override a deprecated API.
[capacitor]         Note: Recompile with -Xlint:deprecation for details.
[capacitor]         Note: D:\xxx\android\capacitor-cordova-android-plugins\src\main\java\cordova\plugins\Diagnostic.java uses unchecked or unsafe operations.
[capacitor]         Note: Recompile with -Xlint:unchecked for details.
[capacitor]         1 error
[capacitor]         FAILED
```

</details>

**Comment by christocracy** [comment]
Why do you still have the `cordova-plugin-background-fetch` installed?  Get rid of it.

>CDVBackgroundFetch.java:57
