### ISSUE TITLE
Question: Is UIApplicationOpenSettingsURLString exposed anywhere?

### ISSUE THREAD

**Issue by alexcroox** [transistorsoft/capacitor-background-geolocation#4]
Is the settings button here exposed as a method anywhere on the API?

![ios-locationAuthorizationAlert](https://user-images.githubusercontent.com/1065835/123645065-e5717000-d81d-11eb-9fc8-29b770bb1ea5.jpg)

Context: I have a series of setup/welcome screens that guide the user to setup the correct permissions. I'd like to redirect them to the settings section to correct their denied permissions if applicable.

![Screenshot 2021-06-28 at 14 32 27](https://user-images.githubusercontent.com/1065835/123644948-c96dce80-d81d-11eb-8fea-a38d9a10b35c.png)

**Comment by alexcroox** [comment]
For anyone else looking for an immediate solution, this is how I currently do it:

https://www.npmjs.com/package/capacitor-native-settings

```
  async openAppSettings() {
      const { NativeSettings } = await import('capacitor-native-settings')

      if (this.$app.isIos) {
        NativeSettings.openIOS({ option: 'app' })
      } else if (this.$app.isAndroid) {
        NativeSettings.openAndroid({ option: 'application' })
      }
    },
```

**Comment by christocracy** [comment]
>Is the settings button here exposed as a method anywhere on the API?

No.  You must use a 3rd-party plugin as you've done above.
