### ISSUE TITLE
Migrate to Capacitor BGgeo. Crashes on boot on iOS Device and Simulator

### ISSUE THREAD

**Issue by sixmilesourdough** [transistorsoft/capacitor-background-geolocation#41]
## Your Environment
* Plugin version: 
        @transistorsoft/capacitor-background-fetch@0.0.6
       @transistorsoft/capacitor-background-geolocation@4.4.3
* Platform: iOS
* Device OS version: iOS 14.4.2
* Device manufacturer / model: iPhone 7
* XCode version: 12.4
* Capacitor info (`npx cap doctor`)
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/android: 2.4.2
  @capacitor/core: 3.0.0-rc.4
  @capacitor/ios: 3.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript 
BackgroundGeolocation.ready({
    url: ENV.TRACKER_HOST,
    reset: true,
    debug: false,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    locationAuthorizationRequest: 'Always',
    // logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    backgroundPermissionRationale: {
      title: "___",
      message: "___",
      positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
      negativeAction: 'Cancel'
    },
    distanceFilter: 15,
    disableElasticity: true,
    disableStopDetection: true,
    pausesLocationUpdatesAutomatically: false,
    stopOnTerminate: true,
    startOnBoot: false,
    enableHeadless: true,
    // encrypt: true,
    autoSync: true,
    autoSyncThreshold: 15,
    batchSync: true,
    maxBatchSize: 50,
    maxDaysToPersist: 14,
    stationaryRadius: 5, // iOS
    showsBackgroundLocationIndicator: true, // iOS blue bar
    headers: {
      "authorization": "Bearer " + ENV.ACCESS_TOKEN,
    },
   
    params: {               // <-- Optional HTTP params
          }
  }).then(async (state) => {
    // console.log('- BackgroundGeolocation is ready: ', state);
    this.zone.run(() => {
      this.state.enabled = state.enabled;
      this.state.isMoving = state.isMoving;
      this.state.geofenceProximityRadius = state.geofenceProximityRadius;
      this.state.trackingMode = state.trackingMode;
      this.onClickGetCurrentPosition();
    });
    if ((state.schedule.length > 0)) {
      BackgroundGeolocation.startSchedule();
    }
  }).catch((error) => {
    // console.warn('- BackgroundGeolocation configuration error: ', error);
  });
```

## Expected Behavior

App runs on device or simulator

## Actual Behavior

App crashes instantly on boot in both device and simulator. The only output in the xcode debugger is this:

2022-01-13 21:39:05.707385-0800 App[5617:1484538] [TSBackgroundFetch load]: (
)
2022-01-13 21:39:05.708214-0800 App[5617:1484538] [TSBGAppRefreshSubscriber load]: {
}

## Steps to Reproduce

1. ionic cap sync ios
2. build app in Xcode
3.
4.

## Debug logs

2022-01-13 21:39:05.707385-0800 App[5617:1484538] [TSBackgroundFetch load]: (
)
2022-01-13 21:39:05.708214-0800 App[5617:1484538] [TSBGAppRefreshSubscriber load]: {
}

<details>
    <summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>App crashes instantly on boot

If there's a crash, there must be a stack-trace.

**Comment by sixmilesourdough** [comment]
<img width="1034" alt="Screen Shot 2022-01-14 at 9 03 11 AM" src="https://user-images.githubusercontent.com/92763835/149555535-78b67270-3be5-4c97-95e2-aa97e41fcd59.png">

**Comment by christocracy** [comment]
I see no reference to the plugin causing a crash.

**Comment by sixmilesourdough** [comment]
Ionic Serve runs without issue in the browser (obviously BG Geo isn't active in the browser). The issue is just on device and simulator. Let me know if there's somewhere else to look for the stack trace.
Thanks.

**Comment by christocracy** [comment]
If you're new to the plugin with Capacitor, I suggest you first create a simple Hello World capacitor app and practice getting the plugin setup and launching in isolation.

**Comment by sixmilesourdough** [comment]
Thanks.

**Comment by Vasek18** [comment]
@sixmilesourdough you can see the console output within the app at chrome://inspect/#devices (android)
