### ISSUE TITLE
Question about migration from cordova-background-geolocation-lt

### ISSUE THREAD

**Issue by Vasek18** [transistorsoft/capacitor-background-geolocation#44]
Hi,

We were using https://github.com/transistorsoft/cordova-background-geolocation-lt and now we are prepared our code base with capacitor' plugin for release
We wonder can there be any data losses after migration e.g. with schedule? What will happen to users whose geolocation is currently being tracked?

Thanks in advance

**Comment by christocracy** [comment]
>We wonder can there be any data losses after migration e.g. with schedule? 

No, there will be no issue.

>What will happen to users whose geolocation is currently being tracked?

They will continue to be tracked.
