### ISSUE TITLE
ERROR in ./node_modules/@transistorsoft/capacitor-background-geolocation/dist/index.js 38:19-33 "export 'registerPlugin' was not found in '@capacitor/core'

### ISSUE THREAD

**Issue by gabriel-arrvda** [transistorsoft/capacitor-background-geolocation#5]
I'm trying to implement this plugin on my ionic application and im facing this issue when i try to build my app in dev instance

Ionic 5
Android without license key
@capacitor/core: 2.4.2

![image](https://user-images.githubusercontent.com/73544831/124799998-856c7f00-df2b-11eb-863e-cd72024b229b.png)

**Comment by christocracy** [comment]
Are you using Capacitor 3?

**Comment by gabriel-arrvda** [comment]
no i'm using capacitor 2.4.2

**Comment by christocracy** [comment]
This is a Capacitor 3 plugin.

**Comment by gabriel-arrvda** [comment]
thanks now it's working

**Comment by gabriel-arrvda** [comment]
thanks now it's working

**Comment by gabriel-arrvda** [comment]
thanks now it's working
