### ISSUE TITLE
App go to suspend Android

### ISSUE THREAD

**Issue by lordrepha1980** [transistorsoft/capacitor-background-geolocation#50]
## Your Environment
* Plugin version: 4.4.5 Capacitor
* Platform: Android
* Device OS version: 11
* Device manufacturer / model: Samsung A7

```
await BackgroundGeolocation.ready({
                    disableMotionActivityUpdates: true,
                    heartbeatInterval: 60,
                    enableHeadless: true,
                    stopOnTerminate: false,
                    preventSuspend: true,
                    desiredOdometerAccuracy: 10,
                    disableStopDetection: true,
                    pausesLocationUpdatesAutomatically: false,
                    debug: false,
                    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                    locationAuthorizationRequest: "WhenInUse",
                    backgroundPermissionRationale: {
                    title: "{applicationName} erlauben, die Standortdaten zu lesen?",
                        message: "",
                        positiveAction: "Ändern auf: {backgroundPermissionOptionLabel}",
                        negativeAction: "Abbrechen"
                    },
                    //disableLocationAuthorizationAlert: false
                    locationAuthorizationAlert: {
                        titleWhenNotEnabled: "Geolocation 'Immer' ist nicht aktiviert",
                        titleWhenOff: "Geolocation ist ausgeschaltet",
                        instructions: "Bitte gehen Sie in die Einstellungen und schalten Sie 'Standort -> immer' an",
                        cancelButton: "Abbrechen",
                        settingsButton: "Einstellungen"
                    }
                }).then( async (state) => {
               
                    // YES -- .ready() has now resolved.
                    const justNowLocation = await BackgroundGeolocation.getCurrentPosition({});
                    sendCoords(justNowLocation)

                    await BackgroundGeolocation.start();  

                    

                    BackgroundGeolocation.setConfig({
                        locationAuthorizationRequest: 'Always'
                    });


                });


                
                BackgroundGeolocation.onHeartbeat(({location}) => {
                    sendCoords(location)
                });
            
                const geolocationWatchId =  BackgroundGeolocation.onLocation(location => {
               
                    sendCoords(location)

                }, error => {
                    log("[location] ERROR: ", error);
                });
```

## Expected Behavior
The App must not  to suspend.

## Actual Behavior
The App go  to suspend.

## Context
I have all Settings from the dontkillmyapp.com, set on my app.

**Comment by christocracy** [comment]
The plugin's heartbeat mechanism ([`AlarmManager.setRepeating`](https://developer.android.com/reference/android/app/AlarmManager#setRepeating(int,%20long,%20long,%20android.app.PendingIntent))) *is* subject to the operating system's "idle time".

Heartbeat events *will* be throttled.

**Comment by lordrepha1980** [comment]
Thank you for your response, do you have an event in the plugin which trigger continuous (every 60 seconds).

**Comment by christocracy** [comment]
The reason that Android has become a nightmare to develop with, requiring the existence of https://dontkillmyapp.com is because of developers killing the user's battery by attempting to spin the CPU "every 60 seconds".

You can try to do what you want using [capacitor-background-fetch](https://github.com/transistorsoft/capacitor-background-fetch).

**Comment by lordrepha1980** [comment]
Not Good, I did buy your Plugin, for this reason. Actualy is it not possible to send the Backgroundgeolocation continuose under Android. Is this Correct?

**Comment by christocracy** [comment]
This [Philosophy of Operation](https://github.com/transistorsoft/capacitor-background-geolocation/wiki/Philosophy-of-Operation) of this plugin is to track the location when the device is detected to be moving.

When the device is stationary, the plugin *strongly* desires to conserve energy.

**Comment by lordrepha1980** [comment]
ok but the device don't wake up when I move it or prevent 'terminate' the app in Background when i move it.

**Comment by christocracy** [comment]
How are you moving it.  You should go outside for a 1km walk.

if the plugin doesn’t engage tracking, it’s a fault of the device.  I test on the following devices:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 12.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by lordrepha1980** [comment]
Thank you

**Comment by christocracy** [comment]
As for the terminated behavior, your RN app no longer exists when app is terminated.

see api docs Config.stopOnTerminate, Config.enableHeadless

**Comment by lordrepha1980** [comment]
Sorry my app is in background but the app don't send the location onMotion, after 5 minutes the app 'sleep' is this the terminated status ?

**Comment by christocracy** [comment]
sleep != terminated.

>locationAuthorizationRequest: "WhenInUse",

With `WhenInUse`, you must *manually* engage the moving state by calling `.changePace(true)` while your app is in the foreground.  The plugin cannot *automatically* trigger location tracking with "WhenInUse".

**Comment by lordrepha1980** [comment]
ok i init the plugin with  

locationAuthorizationRequest: "WhenInUse",

then i set the config with 

BackgroundGeolocation.setConfig({
    locationAuthorizationRequest: 'Always'
});

this config Setting, i see on the device settings. Geolocation 'always'

understand you right? When I set the changePace(true) the device must be wake up after distance from 1km.

**Comment by lordrepha1980** [comment]
with IOS works the service perfekt. the heartbeat ping every 60 seconds the server and the app never sleep. Only for information.

**Comment by christocracy** [comment]
With `Always` authorization, the only thing you need to do is call `.start()`.  The plugin will *automatically* engage location-tracking when the device moves about *200 meters* -- You do not need to manually call `.changePace(true)` with `Always`.

With `Always` authorization, the plugin essentially *automatically* calls `.changePace(true)` **upon itself**.  Please read the wiki *Philosophy of Operation*.

>with IOS works the service perfekt. the heartbeat ping every 60 seconds the server and the app never sleep. Only for information.

Now disconnect your device from power and turn the screen off.  Let the device lie *still* without touching it for 5 minutes.  You will see that heartbeats stop.

Shaking the iOS device or lighting up the screen (without unlocking) will cause heartbeat events to resume again.

**Comment by christocracy** [comment]
Also, use `debug: true` so you can *hear* the debug sound-effect *boop* when heartbeat events fire.  See the API docs [Config.debug](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#debug)

**Comment by lordrepha1980** [comment]
Ok thank you for your response. The Plugin works fine but when i lock the device after 5 -10 minutes ( i think the app 'sleep'), the plugin don't execute my javascript code. I hear the sound for background geolocation. Do you have a solution for this?
