### ISSUE TITLE
Incorrect interface declaration for MotionActivityEvent

### ISSUE THREAD

**Issue by adin00** [transistorsoft/capacitor-background-geolocation#51]
## Environment
* Plugin version: 4.4.5
* Platform: iOS and Android

## Description
The [declaration](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/src/declarations/interfaces/MotionActivityEvent.d.ts) is:
```typescript
  interface MotionActivityEvent {
    /**
    * The reported device motion activity.
    *
    * | Activity Name  |
    * |----------------|
    * | `still`        |
    * | `walking`      |
    * | `on_foot`      |
    * | `running`      |
    * | `on_bicycle`   |
    * | `in_vehicle`   |
    */
    activity: string;
    /**
    * Confidence of the reported device motion activity in %.
    */
    confidence: number;
  }
```

but the actual object attached to `Location.activity` is
```javascript 
{type: 'still', confidence: 100}
```

**Comment by christocracy** [comment]
Because it's a complex issue.

**Comment by adin00** [comment]
oh, OK. I thought the fix should be a mere rename on either side (I assumed it will be on TS) but I clearly don't have an overall view. Meanwhile `eslint-disable-next-line` will work just fine
