### ISSUE TITLE
Error when calling isIgnoringBatteryOptimizations (worked fine with cordova version)

### ISSUE THREAD

**Issue by team-blue-transporeon** [transistorsoft/capacitor-background-geolocation#56]
## Your Environment
* Plugin version:
"@transistorsoft/capacitor-background-fetch": "0.0.6"
"@transistorsoft/capacitor-background-geolocation": "4.3.0"
Also tried with newest version (4.4.5)
* Platform: Android
* Device OS version: Android 9
* Device manufacturer / model: Huawei P20 Lite (Also tested with other devices -> emulators)
* Capacitor info (`npx cap doctor`)
  @capacitor/cli: 3.4.3    
  @capacitor/core: 3.4.3   
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3  
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
                locationAuthorizationRequest: "Always", 
                backgroundPermissionRationale: {
                    title: this.translate.instant("TITLE"),
                    message: this.translate.instant("EXPLANATION"),
                    positiveAction: this.translate.instant("PERMIT"),
                    negativeAction: this.translate.instant("CANCEL")
                }
```

## Expected Behavior
The plugin should return current state of the battery optimization for the app when isIgnoringBatteryOptimizations was called.

## Actual Behavior
When isIgnoringBatteryOptimizations  was called, an error "NativeModule.isIgnoringBatteryOptimizations.then is not a function" get thrown by the function. It works perfectly with the old Cordova plugin, but if we use the capacitor version, the function throws this error.

## Steps to Reproduce
1. Call function isIgnoringBatteryOptimizations with capacitor-background-geolocation

            let isIgnoring = await BackgroundGeolocation.deviceSettings.isIgnoringBatteryOptimizations().catch(
                (error) => {
                    console.error("IgnoringBatteryOptimizations failed", error);
                }

3. Error "NativeModule.isIgnoringBatteryOptimizations.then is not a function" is thrown. (Same code works with cordova version of the plugin)

## Context
Check if device is ignoring battery optimizations for the app.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
NativeModule.isIgnoringBatteryOptimizations.then is not a function
```

</details>

**Comment by christocracy** [comment]
This method seems to be missing from the [Javascript api](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/src/index.ts)

It exists in the [Native Android API](https://github.com/transistorsoft/capacitor-background-geolocation/blob/c4c8709357e5210ad144746a085fd0e7c2924565/android/src/main/java/com/transistorsoft/bggeo/capacitor/BackgroundGeolocationPlugin.java#L856-L861).  This is a simple task to add.

**Comment by panchazo** [comment]
I'm facing the exact same issue. Would you point out how to circumvent the issue in more detail please. Thanks!

**Comment by christocracy** [comment]
Actually, the method is not missing, it's just on a different module.  See the [API Docs](https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/devicesettings.html#isignoringbatteryoptimizations) and search "*isIgnoringBatteryOptimizations*".

**Comment by team-blue-transporeon** [comment]
Since it is unfortunately not clear to me from the answers above whether the problem is the plugin or my incorrect use of it, I would appreciate an answer again.

Should the function be called in the same way as the Cordova plugin?
`await BackgroundGeolocation.deviceSettings.isIgnoringBatteryOptimizations()`
Or do I have to use them differently with Capacitor?
