### ISSUE TITLE
Question about debug mode

### ISSUE THREAD

**Issue by gabriel-arrvda** [transistorsoft/capacitor-background-geolocation#6]
I'm developing an app and I didn't purchased the license yet so im trying to test the plugin in debug mode, but all of my tests i had the same "unimplimented" error, this error means that im building in production mode? If yes, how can I build in development mode? I've been building the app with `ng build` from angular without the `--prod` flag

**Comment by christocracy** [comment]
>had the same "unimplimented" error

I have no idea where you're getting this error.

The plugin is fully function in **DEBUG** builds only without a license.  It will **not** work in production builds without a license.

**Comment by gabriel-arrvda** [comment]
this may sounds silly but how cain build in debug mode in ionic?

**Comment by gabriel-arrvda** [comment]
alright i have built a debug app but while it was running on android studio I found this bug that my console log displayed 
![image](https://user-images.githubusercontent.com/73544831/124824061-43056b00-df48-11eb-8545-2967575d43f5.png)

**Comment by christocracy** [comment]
This plugin is implemented for both iOS & Android.  You're using Capacitor 3, right?

**Comment by christocracy** [comment]
Post your `package.json`

**Comment by gabriel-arrvda** [comment]
`"dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/fire": "^6.0.5",
    "@angular/forms": "~10.0.0",
    "@angular/material": "^10.2.7",
    "@angular/material-moment-adapter": "^11.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@capacitor-community/camera-preview": "^1.1.3",
    "@capacitor/android": "^3.0.2",
    "@capacitor/camera": "^1.0.2",
    "@capacitor/core": "^3.0.2",
    "@capacitor/ios": "^3.1.0",
    "@capacitor/push-notifications": "^1.0.2",
    "@ionic-native/android-permissions": "^5.32.1",
    "@ionic-native/background-geolocation": "^5.33.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/date-picker": "^5.29.0",
    "@ionic-native/firebase": "^5.29.0",
    "@ionic-native/location-accuracy": "^5.32.1",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
    "@transistorsoft/capacitor-background-fetch": "0.0.6",
    "@transistorsoft/capacitor-background-geolocation": "0.0.13",
    "cordova-plugin-android-permissions": "^1.1.2",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-res": "^0.15.2",
    "firebase": "^8.0.1",
    "hammerjs": "^2.0.8",
    "jetifier": "^1.6.6",
    "leaflet": "^1.7.1",
    "leaflet-routing-machine": "^3.2.12",
    "moment": "^2.29.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "vanilla-masker": "^1.2.0",
    "zone.js": "~0.10.3"
  },`

**Comment by gabriel-arrvda** [comment]
"dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/fire": "^6.0.5",
    "@angular/forms": "~10.0.0",
    "@angular/material": "^10.2.7",
    "@angular/material-moment-adapter": "^11.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@capacitor-community/camera-preview": "^1.1.3",
    "@capacitor/android": "^3.0.2",
    "@capacitor/camera": "^1.0.2",
    "@capacitor/core": "^3.0.2",
    "@capacitor/ios": "^3.1.0",
    "@capacitor/push-notifications": "^1.0.2",
    "@ionic-native/android-permissions": "^5.32.1",
    "@ionic-native/background-geolocation": "^5.33.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/date-picker": "^5.29.0",
    "@ionic-native/firebase": "^5.29.0",
    "@ionic-native/location-accuracy": "^5.32.1",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
    "@transistorsoft/capacitor-background-fetch": "0.0.6",
    "@transistorsoft/capacitor-background-geolocation": "0.0.13",
    "cordova-plugin-android-permissions": "^1.1.2",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-res": "^0.15.2",
    "firebase": "^8.0.1",
    "hammerjs": "^2.0.8",
    "jetifier": "^1.6.6",
    "leaflet": "^1.7.1",
    "leaflet-routing-machine": "^3.2.12",
    "moment": "^2.29.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "vanilla-masker": "^1.2.0",
    "zone.js": "~0.10.3"
  },

**Comment by christocracy** [comment]
>"@mauron85/cordova-plugin-background-geolocation": "^3.1.0",

Remove this.

**Comment by gabriel-arrvda** [comment]
I had already done that and nothing changes

**Comment by gabriel-arrvda** [comment]
now it is working, after some tests i realize the camera plugin was not working too and i was struggling at the capacitor 3 update
