### ISSUE TITLE
Replace text "[CHANGEME] This app collets location data for FEATURE X and FEATURE Y"

### ISSUE THREAD

**Issue by eduboxgithub** [transistorsoft/capacitor-background-geolocation#64]
## Your Environment
* Plugin version: latest version, **4.4.6**
* Platform: **iOS and Android**
* Device OS version: **Android 11**
* Device manufacturer / model: **OnePlus 5T**
* XCode version: latest version, **13.2.1**
* Capacitor info
```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1
  @capacitor/cli: 3.4.1
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
const optionsGeofence: Config = 
{
        url: WebService.URL + "geofencing/event",
        params: 
        {
	        'global': this.GlobalService.Get(),
	        'device': pushRegistrationData,
        },
        headers: 
        {
	        'Content-Type': 'application/json',
	        'Authorization': `Bearer ${ session?.Token?.AccessToken }`
        },
        autoSync: true,
        persistMode: BackgroundGeolocation.PERSIST_MODE_ALL,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        geofenceModeHighAccuracy: true,
        geofenceProximityRadius: 2000,
        locationUpdateInterval: environment.production ? 10000 : 2000,
        distanceFilter: environment.production ? 5 : 2,
        stopTimeout: 5,
        logLevel: environment.production ? BackgroundGeolocation.LOG_LEVEL_OFF : BackgroundGeolocation.LOG_LEVEL_WARNING,
        debug: environment.production ? false :  true,
        stopOnTerminate: false, 
        startOnBoot: true,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale:
        {
	        title: 			this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_QUESTION"),
	        message: 		this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_DESCRIPTION"),
	        positiveAction:        this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_ACCEPT"),
	        negativeAction:       this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_REJECT"),
        },
        locationAuthorizationAlert: 
        {
	        titleWhenNotEnabled: this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_LOCATION_WHEN_NOT_ENABLED_QUESTION"),
	        titleWhenOff: 		 this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_LOCATION_WHEN_OFF_QUESTION"),
	        instructions: 		 this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_LOCATION_INSTRUCTIONS"),
	        cancelButton: 		 this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_LOCATION_CANCEL_BUTTON"),
	        settingsButton: 	 this.TranslateService.instant("BACKGROUND_GEOLOCATION_PERMISSION_LOCATION_SETTINGS")
        },
        notification: 
        {
	        title: this.TranslateService.instant("BACKGROUND_GEOLOCATION_NOTIFICATION_GEOFENCING_WHILE_IN_USE_TITLE"),
	        text: this.TranslateService.instant("BACKGROUND_GEOLOCATION_NOTIFICATION_GEOFENCING_WHILE_IN_USE_TEXT")
        }
}
```

## Expected Behavior
Show the permissions alerts with the correct texts.

## Actual Behavior
A default text is presented: _**[CHANGEME] This app collets location data for FEATURE X and FEATURE Y**_.

![image](https://user-images.githubusercontent.com/13800439/160810961-87fefe04-fd63-49b5-8e85-99d4cea7fed0.png)

## Steps to Reproduce
Setup a config object with translations and try to run the app on an Android device.

## Context
I'm using the Capacitor Background Geolocation plugin on a Capacitor/Ionic/Angular app.
In my app I use a Translation service to translate resources keys. The keys are correctly translated, but when they are set to the plugin one of the texts are not presented showing a default text value.

**Comment by christocracy** [comment]
See api docs Config.backgroundPermissionRationale

**Comment by christocracy** [comment]
And do not call any method that requests location until .ready() resolves (Eg .start())

The method .ready() is so-named for a reason (the plugin is not "ready" until .ready resolves.)

**Comment by adin00** [comment]
also consider using reset() instead of ready()

**Comment by adin00** [comment]
also consider using `.reset()` instead of `.ready()` to immediately reflect any changes (once set with some values, ready() will not update those values anymore):
```typescript
await BackgroundGeolocation.ready({});
await BackgroundGeolocation.reset(optionsGeofence);

**Comment by christocracy** [comment]
It's  because you are copy/pasting code from the example (`reset: false`).  Almost nobody but me needs `reset: false`.

The only reason `reset: false` exists is so that the *Settings* screen in the *example* app can control the config and not be reset to the Config provided to `.ready()` each time.  This is not a typical use-case for end-users.

Remove `reset: false` from your config and get rid of your call to `.reset()`.

**Comment by adin00** [comment]
oh well that's a bummer :( in my case I had a typo in `url` prop on first call, and even though it was fixed right away, it took a fair amount of time to figure out what was going on and why no calls were coming through
