### ISSUE TITLE
Different package name on Android and IOs

### ISSUE THREAD

**Issue by cmjunior** [transistorsoft/capacitor-background-geolocation#7]
Hi there.

I'm using different package names on Android and IOs for the same App, it did happend because I'm had to create another application on Android Play Store, after missed the keystone password.

Anyway, is there a problem in using the same license is this apps?

Or, should I try to change the package on IOs store?

Thanks in advice!

**Comment by christocracy** [comment]
iOS is free.  Only Android consumes license keys.  The plugin doesn't care about your iOS package name.
