### ISSUE TITLE
iOS 15 Background Geolocation didn't request to upgrade to "Always" when requesting locationAuthorizationRequest: 'Always'

### ISSUE THREAD

**Issue by pencilcheck** [transistorsoft/capacitor-background-geolocation#70]
## Your Environment
* Plugin version: 4.5.0
* Platform: iOS
* Device OS version: 15.3.1
* Device manufacturer / model: iPhone 11
* XCode version: 13.3
* Capacitor info (`npx cap doctor`): 

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.2
  @capacitor/core: 3.4.2
  @capacitor/android: 3.4.2
  @capacitor/ios: 3.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

* Plugin config provided to `#ready`: 
```javascript <!-- syntax-highlighting:  paste your code below -->
{
            // Debug
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            // Common
            distanceFilter: 0,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            disableElasticity: true,
            stopOnTerminate: false,
            startOnBoot: true,
            stopOnStationary: false,
            disableAutoSyncOnCellular: false,
            useSignificantChangesOnly: false,

            // Activity detection
            disableStopDetection: true,

            locationTimeout: 120,

            // HTTP
            autoSync: true,
            url: process.env.graphqlUrl,
            maxRecordsToPersist: -1,
            maxDaysToPersist: this.maxDaysToPersist,
            method: 'POST',
            httpRootProperty: 'variables',
            params: ... (hiding),
            locationTemplate: ... (hiding),

            // If token expires, we log user out so no need to refresh, we alert user in UI so they know they nee to relogin
            authorization: {
              strategy: "JWT",
              accessToken: token,
            },

            // Location permission
            locationAuthorizationRequest: 'Always',

            // -------------------------------

            // Android specific
            foregroundService: true,
            allowIdenticalLocations: true,
            locationUpdateInterval: this.pingTimeout,
            fastestLocationUpdateInterval: this.fastPingTimeout,
            scheduleUseAlarmManager: true,

            enableHeadless: true,

            // Banned in Android 10+ but leaving it here for < 10
            forceReloadOnBoot: true,
            forceReloadOnMotionChange: true,
            forceReloadOnGeofence: true,
            forceReloadOnHeartbeat: true,
            forceReloadOnSchedule: true,
            forceReloadOnLocationChange: true,

            // Android 11+ with targetSdkVersion 30+
            backgroundPermissionRationale: {
              title: "Allow access to this device's location in the background?",
              message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
              positiveAction: "Change to {backgroundPermissionOptionLabel}",
              negativeAction: "Cancel"
            },

            // ------------------------------------

            // iOS specific
            stationaryRadius: 100,

            showsBackgroundLocationIndicator: true,
            pausesLocationUpdatesAutomatically: false,
            locationAuthorizationAlert: {
              titleWhenNotEnabled: "Location-Services is not enabled",
              titleWhenOff: "Location-Services is OFF",
              instructions: "You must enable 'Always' in Location-Services",
              cancelButton: "Cancel",
              settingsButton: "Settings"
            }
          }
```

## Expected Behavior

Prompt for both two dialogs when requesting locations but instead it only request once. Then going into Settings, Location services -> App there should be an "Always" option

## Actual Behavior

Prompt for the first dialog that only allows "while in use", then nothing. Then going into Settings, Location services -> App there is no "Always" option

## Steps to Reproduce

1. await BackgroundGeolocation.ready(...)
2. BackgroundGeolocation.getCurrentPosition()
3. BackgroundGeolocation.start()
4. no fourth step

## Context

Trying to enable background geolocation for iOS 15 for the app.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> App there is no "Always" option

You made a mistake in the iOS Setup.

Go back to Setup Instructions and **very carefully** review the .plist Config.

**Comment by pencilcheck** [comment]
> > App there is no "Always" option
> 
> You made a mistake in the iOS Setup.
> 
> Go back to Setup Instructions and **very carefully** review the .plist Config.

I follow all instructions, including adding 
1. Privacy - Location Always and When in Use Usage Description
2. Privacy - Location When in Use Usage Description
3. Privacy - Motion Usage Description
4. Permitted background task scheduler identifiers
5. Added AppDelegate.swift for background fetch

Checked capabilities
<img width="698" alt="Screen Shot 2022-04-03 at 1 34 29 PM" src="https://user-images.githubusercontent.com/116532/161447428-d24a18e4-3423-4ba1-8f96-f44400904e7a.png">
<img width="868" alt="Screen Shot 2022-04-03 at 1 34 41 PM" src="https://user-images.githubusercontent.com/116532/161447433-b7076434-271a-4814-bc77-c352f57cf693.png">

<img width="442" alt="Screen Shot 2022-04-03 at 1 34 50 PM" src="https://user-images.githubusercontent.com/116532/161447442-78b11137-bd77-4444-8e2d-b13dd8511ee3.png">

**Comment by christocracy** [comment]
You've not posted any logs.

**Comment by christocracy** [comment]
The presence of the "Always" option in your app settings is not controlled by the plugin.  It is controlled by your own .plist file.

**Comment by pencilcheck** [comment]
that is so weird, I had to open Info.plist from a text editor to see that the key for "NSLocationAlwaysAndWhenInUseUsageDescription" is somehow not the right one but instead the display text. After manually replace the key it is showing up now.
