### ISSUE TITLE
insert in sql lite DB, only specific geographic coordinates

### ISSUE THREAD

**Issue by thoarca** [transistorsoft/capacitor-background-geolocation#72]
Platform: iOS and Android 

## Context
Hi, is it possible to add only the coordinates of a specific geographical area? For example, before entering the coordinates in the sql lite database, check the position and decide whether or not to enter the coordinates in the SQLite database.

Thanks

**Comment by christocracy** [comment]
There is an undocumented way to do this using the plugin's native APIs but I cannot get it to work in Capacitor.  It is easy to do with React Native and Flutter but Capacitor  seems to organize dependencies in an unexpected manner, preventing one from interacting directly with the plugin's native SDK in the iOS `AppDelegate.swift` / Android `Application.java`.

I don't know what you're  trying to do but maybe you want to use geofences.  When the device enters a geofence, you tell the plugin to start recording location (`.start()`).  When the device exits a geofence,  you place the plugin into geofence-only mode (`.startGeofences()`).

**Comment by christocracy** [comment]
After some tinkering, I may have found a way.  Note:  it requires you to write separate native callbacks for both iOS (Swift) and Android (Java).

**Comment by christocracy** [comment]
For iOS, try this:

#### Step 1:  *Frameworks, Libraries, and Embedded Content.
- Click `[+]`.
- Find and add `TSLocationManager.xcframework`

<img width="1079" alt="Screen Shot 2022-04-21 at 9 50 10 AM" src="https://user-images.githubusercontent.com/14999/164473077-a34645be-2543-4f67-af1e-edd03e3f16a0.png">

<img width="410" alt="Screen Shot 2022-04-21 at 9 53 04 AM" src="https://user-images.githubusercontent.com/14999/164473269-8ca599f3-6a92-4df2-bb2e-a1e2ac74ca69.png">

#### Step 2:  `AppDelegate.swift`
- Add the following code:

```diff
import UIKit
import Capacitor
import CoreAudio
+import TSLocationManager;

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
+    /// BackgroundGeolocation location handler.  
+    /// Return an AnyHashable object to be INSERTed into the plugin's SQLite database or nil to cancel the INSERT.
+    /// location.toDictionary() returns the plugin's default schema.
+    ///
+    func onLocation(tsLocation:TSLocation?) -> [AnyHashable:Any]? {
+        let location = tsLocation?.location;
+        let lat = location?.coordinate.latitude
+        let lng = location?.coordinate.longitude;
+        
+        print("onLocation: ", lat!, lng!);
+        
+        if ((lat! > 0) && (lng! < 0) ) {
+            return tsLocation!.toDictionary();
+        } else {
+            return nil;
+        }
+    }
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
+        let locationManager = TSLocationManager.sharedInstance();
+        locationManager?.beforeInsertBlock = onLocation
        return true
    }
```
