### ISSUE TITLE
Can the plugin still register onLocation events after the app has been automatically terminated (e.g. after a week)?

### ISSUE THREAD

**Issue by LucaMueller1** [transistorsoft/capacitor-background-geolocation#75]
## Your Environment
* Plugin version: @transistorsoft/capacitor-background-geolocation@4.4.5, @transistorsoft/capacitor-background-fetch@0.0.6
* Platform: iOS
* Device OS version: iOS 15.4.1
* Device manufacturer / model: Apple iPhone 12 Pro
* XCode version:
* Capacitor info (`npx cap doctor`)
@capacitor/core: 3.4.3
@capacitor/android: 3.4.3
@capacitor/ios: 3.4.3
ionic version: 6.18.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      preventSuspend: true,
      distanceFilter: 10,
      stopTimeout: 5,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true
    })
```

## Expected Behavior
App continues to register onLocation events even after weeks or months of leaving the app in the background.

## Actual Behavior
App is terminated after having it open for a few days and thus reloads when opened again. This is more of a question, not a bug report. Is the plugin able to revive the app and register onLocation events even after leaving it in the background for months? I have read the Philosophy of Operation, but am still not 100% sure if that's achievable. Do I even need to have `preventSuspend` enabled for this? Do I need to leave the stationaryRadius after the app has been terminated in the background for it to register events again and is this the same for the `preventSuspend` option?

## Steps to Reproduce

1. Use the above config
2. Activate background tracking
3. Leave app running for a few days
4. Open the app again and it will reload everything

## Context
I am working on something that is comparable to a fleet tracking application, which needs to get the users location whenever he moves. This needs to be working for months without touching the App on iOS and Android. Is that even possible? Would appreciate some help

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
iOS will relaunch your app in the background when the device moves about 200 meters from last known location.

For Android, see api docs Config.enableHeadless

Also see Config.url.  The plugin has its own built-in http service which will automatically upload recorded locations for you, in native code.

**Comment by ikleiman** [comment]
Regarding this same matter, it's necessary to enable Config.enableHeadless for the app to start on boot in Android? Because it's not working, if I reboot the device it doesn't start tracking unless I manually open the app first. Please let me know if I need to open a new issue for this.

**Comment by christocracy** [comment]
> Config.enableHeadless for the app to start on boot in Android?

No.  enableHeadless is only required if you have custom business logic you’d like to execute.

Are you observing `$ adb logcat` logs from your device after reboot?  The plug-in logs are very verbose and everything it does is logged there.  See wiki *Debugging*.

**Comment by ikleiman** [comment]
Thanks Chris, just did that test. Paired the device over wifi, ran the app, closed the app and walked around the office (about 20 linear meters), logcat showed up the location change events correctly. Then rebooted the device, paired over wifi again, ran adb logcat and walked again the same route, but logcat doesn't show anything. Any ideas?

**Comment by christocracy** [comment]
I'm not interested in what happens when you walk around after reboot.  I am only interested in the following log messages seen after rebooting **and first unlocked the device**.

```
03-20 11:23:21.712  9521  9764 I TSLocationManager: [c.t.l.logger.LoggerFacade$a a]
03-20 11:23:21.712  9521  9764 I TSLocationManager: ╔═════════════════════════════════════════════
03-20 11:23:21.712  9521  9764 I TSLocationManager: ║ BootReceiver: com.transistorsoft.bggeo.demo
03-20 11:23:21.712  9521  9764 I TSLocationManager: ╠═════════════════════════════════════════════
03-20 11:23:21.712  9521  9764 I TSLocationManager: ╟─ android.intent.action.BOOT_COMPLETED
```

**Comment by ikleiman** [comment]
I'm not seeing that kind of message after rebooting:

```
PS C:\Trabajo\Mercofrut\mercofrut-app> adb logcat *:S TSLocationManager:V chromium:V
--------- beginning of main
03-20 12:09:41.817 11241 11241 W chromium: [WARNING:instance_id_android.cc(99)] Non-zero TTL requested for InstanceID token, while TTLs are not supported by Android Firebase IID API.
```

Maybe it's important to mention that logcat gets disconnected on reboot and I need to pair the device again on Android Studio after the reboot in order to run it again?

**Comment by ikleiman** [comment]
Same behavior over USB:

```
PS C:\Trabajo\Mercofrut\mercofrut-app> adb logcat -s 78ee3766 *:S TSLocationManager:V chromium:V
--------- beginning of main
03-20 12:09:41.817 11241 11241 W chromium: [WARNING:instance_id_android.cc(99)] Non-zero TTL requested for InstanceID token, while TTLs are not supported by Android Firebase IID API.
-- when I reboot the device, it gets disconnected, then I run it again: --
PS C:\Trabajo\Mercofrut\mercofrut-app> adb logcat -s 78ee3766 *:S TSLocationManager:V chromium:V
--------- beginning of main
03-20 12:39:30.304 11477 11477 W chromium: [WARNING:instance_id_android.cc(99)] Non-zero TTL requested for InstanceID token, while TTLs are not supported by Android Firebase IID API.
```

Nothing related to TSLocationManager

**Comment by christocracy** [comment]
did you **unlock** the device?

Let it sit after unlocking.  You should also configure `debug: true` so you can **hear** it launch.

**Comment by ikleiman** [comment]
Yes, I did. Now I've activated debug mode, when I open the app everything works as expected, I can see the logs and I can hear the sounds.

Then I rebooted the device, ran logcat, unlocked it and left it unlocked for 5 minutes, I've heard no sound and the log just show 2 chromium related messages:

```
--------- beginning of main
03-20 13:11:59.666 11319 11319 W chromium: [WARNING:instance_id_android.cc(99)] Non-zero TTL requested for InstanceID token, while TTLs are not supported by Android Firebase IID API.
03-20 13:12:29.087 11319 11319 E chromium: [ERROR:merchant_viewer_data_manager.cc(103)] Clearing 0 merchants.
```

**Comment by christocracy** [comment]
The plugin registers an Android `BootReceiver` with the OS.  It's up to the OS to launch the registered `BootReceiver`.  

See https://dontkillmyapp.com

The plugin has been doing this for over 8 years.

**Comment by ikleiman** [comment]
Thanks Chris, that was it. I'm using a Xiaomi phone with MIUI 14, had to enable Autostart for the app, and now I'm seeing the logs and hearing the sounds after the reboot.

I guess I'm not the first user reporting this? Is there any plan of adding an autostart prompt feature to the plugin?
