### ISSUE TITLE
How can I tell if Motion&Fitness permission was granted?

### ISSUE THREAD

**Issue by adin00** [transistorsoft/capacitor-background-geolocation#78]
## Your Environment
* Plugin version: 4.4.6 (I tried to update to 4.5.0 but I've got compilation errors)
* Platform: Android and iOS
* Device OS version: N/A
* Device manufacturer / model: N/A
* XCode version:
* Capacitor info:
  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
        allowIdenticalLocations: false,
        isMoving: true,
        debug: false,
        disableMotionActivityUpdates: true,

        // ios
        preventSuspend: true,
        heartbeatInterval: 60,
        locationAuthorizationRequest: "WhenInUse",
        disableLocationAuthorizationAlert: true,
        stationaryRadius: 8,

        // android
        foregroundService: true,
        stopTimeout: 5,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        speedJumpFilter: 250,

        url: `http://10.0.2.2:3000/locations`,
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 50,

        stopOnTerminate: true,
        enableHeadless: false,
        startOnBoot: false,

        locationUpdateInterval: 2400,
        fastestLocationUpdateInterval: 1000,

        notification: {
          priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
          title: "Background tracking enabled",
        },
      }
```

## Expected Behavior
some event to listen to when Motion&Fitness Activity permission is granted/denied -- or maybe `Promise.reject('reason')` on `await BackgroundGeolocation.start()` with an enabler switch on config object

## Actual Behavior
Nothing

## Context
I am building a workout app with some additional gamification, and I need this permission to be granted (user should be locked in this step if he denies it)

**Comment by christocracy** [comment]
>Plugin version: 4.4.6 (I tried to update to 4.5.0 but I've got compilation errors)

You need to use a minimum `compileSdkVersion 31`.  Check your `android/variables.gradle`

**Comment by christocracy** [comment]
*Motion & Fitness* permission is not a crucial permission for the plugin; it can operate without it.  The plugin offers no mechanism for detecting whether that permission is denied.

You should be able to use a 3rd party plugin [like this](https://github.com/dariosalvi78/cordova-plugin-health) to detect permission status.

**Comment by christocracy** [comment]
> disableMotionActivityUpdates: true,

The way you've configured the plugin, it's not even going to ask for *Motion & Fitness* permission.

**Comment by adin00** [comment]
> > Plugin version: 4.4.6 (I tried to update to 4.5.0 but I've got compilation errors)
> 
> You need to use a minimum `compileSdkVersion 31`. Check your `android/variables.gradle`
Thank you. I'll give give it another go


> > disableMotionActivityUpdates: true,
> 
> The way you've configured the plugin, it's not even going to ask for _Motion & Fitness_ permission.

That is intentional for the moment, as I am exploring other ways to get the permission.
