### ISSUE TITLE
Permissions managements

### ISSUE THREAD

**Issue by luismtz0826** [transistorsoft/capacitor-background-geolocation#85]
## Your Environment
* Plugin version: 0.0.5
* Platform: iOS, Android
* Device OS version: Android 12, iOS 15.5
* Device manufacturer / model: Android: Xiaomi Mi Note 10 Lite - iOS Iphone 13 max
* XCode version: 13.4.1
* Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

## Expected Behavior
One single popup permission 

## Actual Behavior
Three permission popups are shown

## Context
Is it possible to unify the permission popups in one?

**Comment by christocracy** [comment]
No. 

btw, you’re using an old version.  Upgrade to latest.
