### ISSUE TITLE
Migration to Capacitor 4

### ISSUE THREAD

**Issue by phal0r** [transistorsoft/capacitor-background-geolocation#89]
## Your Environment
* Plugin version: latest
* Platform: iOSand Android
* Device OS version: all
* Device manufacturer / model: all
* XCode version: all
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Context
I just bought the Capacitor plugin for our company and we want to move to Capacitor 4, because most of the active plugins are in the process of migration or already have migrated. From the changelog it is not clear, what the plan for this plugin is. It is the only plugin we use, where migration is unclear.

As I could see in the PRs of other plugins, mostly variables (compileSdk, minimum iOS version, etc.) change. Do you already have a timeline to migrate?

Thanks in advance!

**Comment by christocracy** [comment]
I’m not aware of any required changes to the plugin architecture for Capacitor 4.

**Comment by christocracy** [comment]
The Android plugin [reads compileSdkVerison](https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/android/build.gradle#L40) from your app’s gradle ext vars, so that’s irrelevant.

The iOS plugin should not be affected by min iOS version.

**Comment by christocracy** [comment]
The Android lib itself is compiled with compileSdkVersion 33.

31 and 32 will work perfectly fine as well.

**Comment by phal0r** [comment]
Thanks for the information. Yeah, I think api does not change only minimum sdk versions. I will give the migration a try and will report my findings here.

**Comment by phal0r** [comment]
Works 👍
