### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by akhil5** [transistorsoft/capacitor-background-geolocation#9]
in /Users/user/Library/Developer/Xcode/DerivedData/App-cjkkwdgfpdtzlcbcuwkzytqcngbv/Build/Products/Debug-iphoneos/TSBackgroundFetch.framework/TSBackgroundFetch(TSBGTask.o), building for iOS, but linking in object file (/Users/user/Library/Developer/Xcode/DerivedData/App-cjkkwdgfpdtzlcbcuwkzytqcngbv/Build/Products/Debug-iphoneos/TSBackgroundFetch.framework/TSBackgroundFetch(TSBGTask.o)) built for Mac Catalyst, file '/Users/user/Library/Developer/Xcode/DerivedData/App-cjkkwdgfpdtzlcbcuwkzytqcngbv/Build/Products/Debug-iphoneos/TSBackgroundFetch.framework/TSBackgroundFetch' for architecture arm64

Xcode version 12.5

**Comment by christocracy** [comment]
>TSBackgroundFetch.framework/TSBackgroundFetch(TSBGTask.o)

Your issue is with `BackgroundFetch`, not `BackgroundGeolocation`.  Post an issue at [capacitor-background-fetch](https://github.com/transistorsoft/capacitor-background-fetch/issues)
