### ISSUE TITLE
BUG: locationTemplaze 

### ISSUE THREAD

**Issue by phal0r** [transistorsoft/capacitor-background-geolocation#92]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* Device OS version:
* Device manufacturer / model:
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Ignored issue template and provided *zero* information.

Edit your issue and provide the required information.

**Comment by phal0r** [comment]
sorry, I didn't realize, that this was actually being saved. I was in the middle of writing the ticket and somehow it was submitted.
