### ISSUE TITLE
BUG: locationTemplate not always enforced

### ISSUE THREAD

**Issue by phal0r** [transistorsoft/capacitor-background-geolocation#93]
## Your Environment
* Plugin version: 4.8.x
* Platform: Android
* Device OS version: Android 11
* Device manufacturer / model: Samsung Galaxy A22
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/ios: 4.1.0
  @capacitor/android: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
					locationAuthorizationRequest: 'Always',
					// Geolocation Config
					desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
					distanceFilter: 10,
					// Activity Recognition
					stopTimeout: 1,
					// Application config
					debug: true, // <-- enable this hear debug sounds.
					logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
					stopOnTerminate: true, // <-- Allow the background-service to continue tracking when app terminated.
					startOnBoot: false, // <-- Auto start tracking when device is powered-up.
					// HTTP / SQLite config
					url: url,
					locationTemplate:
						'{"name": "Driver Location", "lat": "<%= latitude %>","lon": "<%= longitude %>"}',
					httpRootProperty: '.',
					batchSync: false, // <-- Set true to sync locations to server in a single HTTP request.
					autoSync: true, // <-- Set true to sync each location to server as it arrives.
					headers: {
						Authorization: 'Bearer ' + token,
					},
				}
```

## Expected Behavior
Plugin generates location entries in the shape described by locationTemplate

## Actual Behavior
At least one of the location records has a "provider" object attached (see screenshot)

## Steps to Reproduce

Just ready the plugin and call start. Nothing more specific.

## Context
Sending location updates via http.

![image](https://user-images.githubusercontent.com/3658211/188894394-c747582b-8d5f-4ad4-86fa-0e4672157f26.png)

**Comment by christocracy** [comment]
When the state of location-services changes (eg: *Location disabled*, *Wifi disabled*), the Android plugin automatically records a location to let your server know *when and where* the `onProviderChange` event occurred.  Some customers are interested in know when/where their users disabled location-services.

The `provider` key, containing the location-provider state at that time is automatically appended to the JSON and there's no way to template it.

**Comment by phal0r** [comment]
Thanks for the insights and yeah I agree, that this information makes sense. My problem is, that the backend performs a strict validation of the payload and provider is not expected in the payload. 

Now while debugging, I can see, that the plugin tries to post this location to the server, it gets (correctly) rejected with statuscode 400 and the plugin stops now and from my understanding it will retry this record until it it reaches the maxDays attributes before it gets dropped and no  other location events are being send to the server.

If this is intended behaviour, how can I remove this record, so it won't clog the queue for several hours or even days? Can I filter this somehow locally or is there a way to get rid of the record?

**Comment by christocracy** [comment]
Currently, the only way the plugin will automatically destroy a record from its queue is from http 20x response.

However, I think it would make sense for the plugin to destroy the record from with status `400`, since:

![image](https://user-images.githubusercontent.com/14999/188955301-7ca62f34-990c-47ca-aafd-0e70779feebd.png)

However, in the meantime, try using the method [`.destroyLocation(uuid)`](https://transistorsoft.github.io/capacitor-background-geolocation/classes/backgroundgeolocation.html#destroylocation)

You can probably implement .destroyLocation(location.uuid) in the onProviderChange event-handler.  The POST will probably already have occurred by the time the event fires, but at least it will clear it from the queue.

**Comment by phal0r** [comment]
I agree with statuscode 400. 

However as a Developer, who uses this plugin I would appreciate to have full control of the data, that gets send. It would be cool to have a flag, that allows to disable the appending of the provider object, which defaults to true, so there is no breaking change for existing integrations. Or the provider object becomes part of the template, so we can control it with the template.

**Comment by christocracy** [comment]
>It would be cool to have a flag, that allows to disable the appending of the provider object,

Added new `Config.disableProviderChangeRecord` (default `false`).  Please test it out by installing from branch `#release-4.8.3`:

```
npm install https://github.com/transistorsoft/capacitor-background-geolocation.git#release-4.8.3
```

>Or the provider object becomes part of the template, so we can control it with the template.

This would be *very* difficult to template without *insisting* that the root key be named __`provider`__.  For example, someone might want to call it `location_services_change_event` and that would be impossible.

**Comment by christocracy** [comment]
<img width="987" alt="Screen Shot 2022-09-08 at 11 21 03 AM" src="https://user-images.githubusercontent.com/14999/189161433-5867cde2-e8da-4df8-86a0-894dce6d9b90.png">

**Comment by phal0r** [comment]
Cool, thanks. I will test it.

> This would be very difficult to template without insisting that the root key be named provider. For example, someone might want to call it location_services_change_event and that would be impossible.

Yeah, the only option would be to have a template key for each attribute of the object.

**Comment by phal0r** [comment]
I wanted to give it a try and executed 
```
npm install https://github.com/transistorsoft/capacitor-background-geolocation.git#release-4.8.3
```

to install from the branch. Unfortunately the dist folder is missing and the build complains. Do I need to execute more steps or is the branch just erroneous?

**Comment by christocracy** [comment]
Oh, right.  Yea, the repo needs to first be cloned, change to branch `release-4.8.3`, then run `npm run build`.

then npm install plugin from local path/to/clone

**Comment by phal0r** [comment]
Yeah, now it works, after configuring disableProviderChangeRecord, I could not see any locations with provider object (tested on Android 11)

**Comment by christocracy** [comment]
Good.  Android version won’t matter.

**Comment by phal0r** [comment]
@christocracy Do you have a ETA for this to be released?

**Comment by christocracy** [comment]
`4.8.3` is now merged to master and published

**Comment by phal0r** [comment]
Awesome, thank you @christocracy
