### ISSUE TITLE
Very inaccurate locations are sometimes provided.

### ISSUE THREAD

**Issue by MrMid** [transistorsoft/capacitor-background-geolocation#98]
## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* Device OS version: Android 12
* Device manufacturer / model: Nokia G20
* Capacitor info (`npx cap doctor`):
 💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1

[success] Android looking great! 👌

* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
			locationAuthorizationRequest: 'Always',
			backgroundPermissionRationale: {...},
			url: APILocation + 'locations',
			// Timestamp is in UTC and formatted as ISO-8601.
			locationTemplate: '{"time":"<%=timestamp%>","lat":<%=latitude%>,"lng":<%=longitude%>,"alt":<%=altitude%>,"acc":<%=accuracy%>,"spd":<%=speed%>,"prov":"gps","bat":<%=battery.level%>,"charging":<%=battery.is_charging%>}',
			httpRootProperty: "locations",
			batchSync: true,
			maxBatchSize: 50,
			maxDaysToPersist: 10,
			extras: {
				// To be sent with each location.
				"driver": this.driver,
				"mode": this.mode,
			},
			params: {
				// To be sent once while syncing.
				"ver": appVersion,
				"device": await this.device.getDeviceID(),
			},

			// Geolocation Config
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			// Activity Recognition
			stopTimeout: 25,
			// Application config
			debug: true, // Play sounds for background-geolocation life-cycle.
			logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
			foregroundService: true,
			stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
			startOnBoot: true,      // Auto start tracking when device is powered-up.
		}
```

## Expected Behavior
The logged track should have followed the red, drawn route.

![Screenshot_20220921_075714](https://user-images.githubusercontent.com/16018428/191434771-f3e9d11a-0f92-4e74-a939-896363e5e763.png)

## Actual Behavior
Actually, it zig-zags around. This is probably the most extreme example, but it happens often. Sometimes it's going well, sometimes it goes back-and-forth, sometimes zig-zags. Maybe in slower speeds it zig-zags, in higher speeds it works well.

## Steps to Reproduce

1. Ride a bike with the given config.
2. See what it did.

## Context
I want the app to reliably report the location in the background. All the battery optimizations are turned off, all the reporting goes through the plugin. Did i miss something? Is there anything I could improve in the config or somewhere else?

I bought the Nokia G20 specifically because of the Android One which I hoped wouldn't mess with background services so much.

## Debug logs

<details>
	<summary>Logs</summary>
Logcat doesn't let me go back that far in history to this occurrence. Maybe the app was killed by OS in the meantime? There was normally nothing interesting in logs, though.

I will provide logs of another such event, if it will be needed to understand this issue.

</details>

**Comment by christocracy** [comment]
The plugin is not responsible for the quality of locations returned by a particular device’s native location api.  Some devices are just better than others.

It’s your responsibility to filter locations as desired (see location.coords.accuracy)

**Comment by christocracy** [comment]
The quality of locations is affected by environment also (tall buildings, mountains, bodies of water).

**Comment by MrMid** [comment]
Well, thanks. What bothers me is that none of the locations in that section were accurate. But thanks for confirmation that there is nothing I can do configuring your plugin that would improve it.

May I ask you which (currently sold) Android phones work best in your experience?

**Comment by MrMid** [comment]
Thanks for your info. I will continue examining where the problem lies.
